// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_PackageInConnector
// ==================================================================
   [Association, UMLPackagePath ( "CIM::Physical::Connector" ),
    Version ( "2.6.0" ), Description (
       "Adapter cards and other 'packaging' are plugged into System "
       "Connectors for power and/or to transfer data. This "
       "relationship is defined by PackageInConnector. For example, it "
       "would be used to describe the insertion of a daughtercard onto "
       "another Card. Various subclasses of PackageInConnector are "
       "also defined. PackageInSlot and its subclass, CardInSlot, are "
       "two examples of subclasses.")]
class CIM_PackageInConnector : CIM_Dependency {

      [Override ( "Antecedent" ), Description (
          "The Connector into which the Package is inserted.")]
   CIM_PhysicalConnector REF Antecedent;

      [Override ( "Dependent" ), Max ( 1 ), Description (
          "The Package in the Connector.")]
   CIM_PhysicalPackage REF Dependent;
};
