// ===================================================================
// Title: CIM_Application
// $State: Exp $
// $Date: 2005/02/17 00:09:56 $
// $RCSfile: CIM_Application.mof,v $
// $Revision: 1.1 $
// ===================================================================
//#pragma inLine ("Includes/copyright.inc")
// Copyright 1998-2005 Distributed Management Task Force, Inc. (DMTF).
// All rights reserved.
// DMTF is a not-for-profit association of industry members dedicated
// to promoting enterprise and systems management and interoperability.
// DMTF specifications and documents may be reproduced for uses
// consistent with this purpose by members and non-members,
// provided that correct attribution is given.
// As DMTF specifications may be revised from time to time,
// the particular version and release date should always be noted.
// 
// Implementation of certain elements of this standard or proposed
// standard may be subject to third party patent rights, including
// provisional patent rights (herein "patent rights"). DMTF makes
// no representations to users of the standard as to the existence
// of such rights, and is not responsible to recognize, disclose, or
// identify any or all such third party patent right, owners or
// claimants, nor for any incomplete or inaccurate identification or
// disclosure of such rights, owners or claimants. DMTF shall have no
// liability to any party, in any manner or circumstance, under any
// legal theory whatsoever, for failure to recognize, disclose, or
// identify any such third party patent rights, or for such party's
// reliance on the standard or incorporation thereof in its product,
// protocols or testing procedures. DMTF shall have no liability to
// any party implementing such standard, whether such implementation
// is foreseeable or not, nor to any patent owner or claimant, and shall
// have no liability or responsibility for costs or losses incurred if
// a standard is withdrawn or modified after publication, and shall be
// indemnified and held harmless by any party implementing the
// standard from any and all claims of infringement by a patent owner
// for such implementations.
// 
// For information about patents held by third-parties which have
// notified the DMTF that, in their opinion, such patent may relate to
// or impact implementations of DMTF standards, visit
// http://www.dmtf.org/about/policies/disclosures.php.
//#pragma inLine
// ===================================================================
// Description: These object classes define the DMTF Application Model
//      and include classes to represent software elements, products
//      and systems entities as well as the elements required to
//      manage the deployment of software.
// 
//      The object classes below are listed in an order that
//      avoids forward references. Required objects, defined
//      by other working groups, are omitted.
// ==================================================================

#pragma locale ("en_US")


// ==================================================================
// Application Model Includes
// Compile prerequisite:  Core and System MOFs
// System MOF required for 2 includes (SystemSoftware and
//    BIOS) - Specifically, System28_SystemElements.mof,
//    System27_SystemSoftware.mof and System28_Diagnostics.mof
//    are needed from the System MOF
// ==================================================================
#pragma include ("Application_DeploymentModel.mof")
#pragma include ("Application_InstalledProduct.mof")
#pragma include ("Application_CheckAction.mof")
#pragma include ("Application_SystemSoftware.mof")
#pragma include ("Application_BIOS.mof")
#pragma include ("Application_AppRuntime.mof")
#pragma include ("Application_J2eeAppServer.mof")
#pragma include ("Application_J2eeAppServerStats.mof")


// ==================================================================
// end of file
// ==================================================================
