// ===================================================================
// Title: CIM_Network
// $State: Exp $
// $Date: 2005/02/17 00:09:56 $
// $RCSfile: CIM_Network.mof,v $
// $Revision: 1.1 $
// ===================================================================
//#pragma inLine ("Includes/copyright.inc")
// Copyright 1998-2005 Distributed Management Task Force, Inc. (DMTF).
// All rights reserved.
// DMTF is a not-for-profit association of industry members dedicated
// to promoting enterprise and systems management and interoperability.
// DMTF specifications and documents may be reproduced for uses
// consistent with this purpose by members and non-members,
// provided that correct attribution is given.
// As DMTF specifications may be revised from time to time,
// the particular version and release date should always be noted.
// 
// Implementation of certain elements of this standard or proposed
// standard may be subject to third party patent rights, including
// provisional patent rights (herein "patent rights"). DMTF makes
// no representations to users of the standard as to the existence
// of such rights, and is not responsible to recognize, disclose, or
// identify any or all such third party patent right, owners or
// claimants, nor for any incomplete or inaccurate identification or
// disclosure of such rights, owners or claimants. DMTF shall have no
// liability to any party, in any manner or circumstance, under any
// legal theory whatsoever, for failure to recognize, disclose, or
// identify any such third party patent rights, or for such party's
// reliance on the standard or incorporation thereof in its product,
// protocols or testing procedures. DMTF shall have no liability to
// any party implementing such standard, whether such implementation
// is foreseeable or not, nor to any patent owner or claimant, and shall
// have no liability or responsibility for costs or losses incurred if
// a standard is withdrawn or modified after publication, and shall be
// indemnified and held harmless by any party implementing the
// standard from any and all claims of infringement by a patent owner
// for such implementations.
// 
// For information about patents held by third-parties which have
// notified the DMTF that, in their opinion, such patent may relate to
// or impact implementations of DMTF standards, visit
// http://www.dmtf.org/about/policies/disclosures.php.
//#pragma inLine
// ===================================================================
// Description: The Network Model defines both general and specific
//              networking concepts. This is the primary include file
//              for the basic segments of the DMTF Network Model.
// 
//              The includes are listed in an order that
//              avoids forward references. Required objects, defined
//              by other working groups, are omitted.
// ==================================================================

#pragma locale ("en_US")


// ==================================================================
// Compile prerequisite for all includes:  Core and System MOFs
// System MOF needed in Network28_Systems - System28_SystemElements
//    is needed
// ==================================================================


// ==================================================================
// Network Systems and Services
// ==================================================================
#pragma include ("Network_Systems.mof")

// ==================================================================
// Network Collections (LogicalNetwork, RangeOfIPAddresses, etc.)
// ==================================================================
#pragma include ("Network_Collections.mof")

// ==================================================================
// Protocol Endpoints
// ==================================================================
#pragma include ("Network_ProtocolEndpoints.mof")

// ==================================================================
// FilterLists and FilterEntryBases
// ==================================================================
#pragma include ("Network_Filtering.mof")

// ==================================================================
// Routing and Forwarding Network Services
// ==================================================================
#pragma include ("Network_RoutingForwarding.mof")

// ==================================================================
// Network Routes
// ==================================================================
#pragma include ("Network_Routes.mof")

// ==================================================================
// Network Pipes
// ==================================================================
#pragma include ("Network_Pipes.mof")

// ==================================================================
// Network Buffers
// ==================================================================
#pragma include ("Network_Buffers.mof")

// ==================================================================
// SNMP Management
// ==================================================================
#pragma include ("Network_SNMP.mof")

// ==================================================================
// OSPF Model
// ==================================================================
#pragma include ("Network_OSPF.mof")

// ==================================================================
// BGP Model
// ==================================================================
#pragma include ("Network_BGP.mof")

// ==================================================================
// Spanning Tree Model
// ==================================================================
#pragma include ("Network_SwitchingBridging.mof")

// ==================================================================
// QoS Model
// ==================================================================
#pragma include ("Network_QoS.mof")

// ==================================================================
// IPsec Security Associations
// ==================================================================
#pragma include ("Network_IPsec.mof")

// ==================================================================
// VLAN Model
// ==================================================================
#pragma include ("Network_VLAN.mof")



// ===================================================================
// end of file
// ===================================================================
