// ===================================================================
// Title: CIM_Database
// $State: Exp $
// $Date: 2005/02/17 00:09:56 $
// $RCSfile: CIM_Database.mof,v $
// $Revision: 1.1 $
// ===================================================================
//#pragma inLine ("Includes/copyright.inc")
// Copyright 1998-2005 Distributed Management Task Force, Inc. (DMTF).
// All rights reserved.
// DMTF is a not-for-profit association of industry members dedicated
// to promoting enterprise and systems management and interoperability.
// DMTF specifications and documents may be reproduced for uses
// consistent with this purpose by members and non-members,
// provided that correct attribution is given.
// As DMTF specifications may be revised from time to time,
// the particular version and release date should always be noted.
// 
// Implementation of certain elements of this standard or proposed
// standard may be subject to third party patent rights, including
// provisional patent rights (herein "patent rights"). DMTF makes
// no representations to users of the standard as to the existence
// of such rights, and is not responsible to recognize, disclose, or
// identify any or all such third party patent right, owners or
// claimants, nor for any incomplete or inaccurate identification or
// disclosure of such rights, owners or claimants. DMTF shall have no
// liability to any party, in any manner or circumstance, under any
// legal theory whatsoever, for failure to recognize, disclose, or
// identify any such third party patent rights, or for such party's
// reliance on the standard or incorporation thereof in its product,
// protocols or testing procedures. DMTF shall have no liability to
// any party implementing such standard, whether such implementation
// is foreseeable or not, nor to any patent owner or claimant, and shall
// have no liability or responsibility for costs or losses incurred if
// a standard is withdrawn or modified after publication, and shall be
// indemnified and held harmless by any party implementing the
// standard from any and all claims of infringement by a patent owner
// for such implementations.
// 
// For information about patents held by third-parties which have
// notified the DMTF that, in their opinion, such patent may relate to
// or impact implementations of DMTF standards, visit
// http://www.dmtf.org/about/policies/disclosures.php.
//#pragma inLine
// ===================================================================
// Description:
//       The database model provides a set of classes and
//       associations for managing database systems.
// 
//       This MOF describes a three level model for a database
//       environment.
//          1) The database system software that has been deployed
//          2) The common database entity and associated storage
//          3) The database runtime services which perform tasks for the
//             database, such as coordinating user access
// 
//       The classes and associations provided in this model are
//       intended to be common across all database organizations
//       and vendor implementations.  The database model
//       represents the entities, associations, and properties that
//       at an abstract level are appropriate for all database
//       organizations and vendor implementations.  For readability
//       purposes, the term database when used in this MOF refers to
//       the common database entity.
// 
//       The object classes below are listed in an order that
//       avoids forward references. Required objects that have been
//       defined by other working groups are omitted.
// 
//       The includes are listed in an order that avoids forward
//       references.  Dependent classes or associations that are
//       part of other models have been omitted.
// ==================================================================

#pragma locale ("en_US")


// ==================================================================
// Compile prerequisite:  Core, User-Security, Application and
//                        System MOFs
//    User-Security MOF required - User28_Org.mof
//    Application MOF required - Application28_DeploymentModel.mof
//    System MOF required - System28_SystemResources.mof
//                          System28_FileElements.mof
// ==================================================================


// ==================================================================
// Database System
// ==================================================================
#pragma include ("Database_System.mof")

// ==================================================================
// Database Storage
// ==================================================================
#pragma include ("Database_Storage.mof")

// ==================================================================
// Database Statistics
// ==================================================================
#pragma include ("Database_Statistics.mof")

// ===================================================================
// end of file
// ===================================================================
