// ==================================================================
// PG_TestElement
// ================================================================== 
   [Abstract, Version ("2.2.0"), Description (
   "PG_TestElement is an abstract class that provides a common "  
        "superclass (or top of the inheritance tree) for the "
        "non-association classes in the test Schema.")]
   class PG_TestElement   
   {  
      [Key, MaxLen (256),
       Description (
          "CreationClassName indicates the name of the class or the "
          "subclass used in the creation of an instance. When used "
          "with the other key properties of this class, this property "
          "allows all instances of this class and its subclasses to "
          "be uniquely identified.")]
     string CreationClassName;

      [Key, 
       Description (  
          "An identifier that uniquely identifies each instance "
          "of the PG_TestElement hierarchy.") ]   
     uint64 InstanceId;  
   };

     

// ===================================================================
// PG_TestPropertyTypes
// ===================================================================
   
   [Version ("2.2.0"), Description (
   "PG_TestPropertyTypes is a concrete class derived from PG_TestElement"),
    provider("PG_TestPropertyTypes")
   ] 
class PG_TestPropertyTypes:PG_TestElement 
{
      [Maxlen (256), Description (
       "a string property of PG_TestPropertyTypes")]
   string PropertyString;

      [Description (
       "a uint8 property of PG_TestPropertyTypes")]
   uint8 PropertyUint8;

      [Description (
      "a uint16 property of PG_TestPropertyTypes")]
   uint16 PropertyUint16;

      [Description (
      "a uint32 property of PG_TestPropertyTypes")]
   uint32 PropertyUint32;

      [Description (
      "a uint64 property of PG_TestPropertyTypes")]
   uint64 PropertyUint64;

      [Description (
      "a sint8 property of PG_TestPropertyTypes")]
   sint8 PropertySint8;

      [Description (
       "a sint16 property of PG_TestPropertyTypes")]
   sint16 PropertySint16;

      [Description (
      "a sint32 property of PG_TestPropertyTypes")]
   sint32 PropertySint32;

      [Description (
      "a sint64 property of PG_TestPropertyTypes")]
   sint64 PropertySint64;

      [Description (
      "a boolean property of PG_TestPropertyTypes")]
   boolean PropertyBoolean;

     [Description (
      "a real32 property of PG_TestPropertyTypes")]
   real32 PropertyReal32;

     [Description (
      "a real64 property of PG_TestPropertyTypes")]
   real64 PropertyReal64;

      [Description (
      "a datetime property of PG_TestPropertyTypes")]
   datetime PropertyDatetime;

      [Description (
      "a char16 property of PG_TestPropertyTypes")]
   char16 PropertyChar16;
      
};
