instance of PG_ProviderModule 
{
   Name = "PG_TestPropertyTypesModule";
   Location = "PG_TestPropertyTypes";
   Vendor = "OpenPegasus";
   Version = "2.0.0";
   InterfaceType = "C++Default";
   InterfaceVersion = "2.1.0";
};

instance of PG_Provider 
{
   ProviderModuleName = "PG_TestPropertyTypesModule";
   Name = "PG_TestPropertyTypes";
};

instance of PG_ProviderCapabilities 
{
   ProviderModuleName = "PG_TestPropertyTypesModule";
   ProviderName = "PG_TestPropertyTypes";
   CapabilityID = "1";
   ClassName = "PG_TestElement";
   Namespaces = {"test/static"};
   ProviderType = { 2 }; // Instance
   SupportedProperties = NULL; // All properties
   SupportedMethods = NULL; // All methods
};

instance of PG_ProviderCapabilities 
{
   ProviderModuleName = "PG_TestPropertyTypesModule";
   ProviderName = "PG_TestPropertyTypes";
   CapabilityID = "2";
   ClassName = "PG_TestPropertyTypes";
   Namespaces = {"test/static"};
   ProviderType = { 2 }; // Instance
   SupportedProperties = NULL; // All properties
   SupportedMethods = NULL; // All methods
};
