// Copyright (c) 2011 DMTF.  All rights reserved.
   [Association, Experimental, Aggregation, Version ( "2.28.0" ), 
    UMLPackagePath ( "CIM::Database::Sql" ), 
    Description ( 
       "DatabaseContainsTable specifies the defined tables in a "
       "relational database." )]
class CIM_DatabaseContainsTable : CIM_Component {

      [Experimental, Key, Aggregate, Override ( "GroupComponent" ), 
       Max ( 1 ), 
       Description ( "The relational database." )]
   CIM_CommonDatabase REF GroupComponent;

      [Experimental, Key, Override ( "PartComponent" ), 
       Description ( "The SqlTable contained within the database." )]
   CIM_SqlTable REF PartComponent;


};
