// Copyright (c) 2011 DMTF.  All rights reserved.
   [Version ( "2.28.0" ), 
    UMLPackagePath ( "CIM::Database::Storage" ), 
    Description ( 
       "RelationalDatabaseCapabilities extends "
       "CommonDatabaseCapabilities to specify the capabilities for "
       "relational database service. A relational database service "
       "process queries by SQL. Supported SQL operations depend on the "
       "target SQL objects (database, table or column) and the "
       "implementation of the relational data base service. The "
       "properties of the RelationalDatabaseCapabilities specifies the "
       "supported SQL operations." )]
class CIM_RelationalDatabaseCapabilities : CIM_CommonDatabaseCapabilities {

      [Experimental, Description ( 
          "An array of enumerated values representing the SQL "
          "operations to databases. In general, a set of supported "
          "operations depends on the database service "
          "implementation. The value map explicitly lists the "
          "common database operations such as GRANT and CREATE, "
          "which are derived from the SQL92 specification and "
          "typical database implementations including Oracle, "
          "MySQL, etc. The operation information is used as the "
          "action type in the database access control management." ), 
       ValueMap { "1", "2", "3", "4", "..", "0x8000.." }, 
       Values { "Alter", "Create", "Drop", "Grant", "DMTF Reserved", 
          "Vendor Reserved" }]
   uint16 SupportedDBOperations[];

      [Experimental, Description ( 
          "An array of enumerated values representing the SQL "
          "operations to database tables. Set of supported "
          "operations depends on the database service "
          "implementation. The operation information is used as the "
          "action type in the database access control management." ), 
       ValueMap { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", 
          "11", "..", "0x8000.." }, 
       Values { "Alter", "Create", "Drop", "Grant", "Delete", 
          "Insert", "Index", "Lock", "References", "Select", 
          "Update", "DMTF Reserved", "Vendor Reserved" }]
   uint16 SupportedTableOperations[];

      [Experimental, Description ( 
          "An array of enumerated values representing the SQL "
          "operations to table columns. Set of supported operations "
          "depends on the database service implementation. The "
          "operation information is used as the action type in the "
          "database access control management." ), 
       ValueMap { "1", "4", "6", "7", "9", "10", "11", "..", 
          "0x8000.." }, 
       Values { "Alter", "Grant", "Insert", "Index", "References", 
          "Select", "Update", "DMTF Reserved", "Vendor Reserved" }]
   uint16 SupportedColumnOperations[];


};
