// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="CIMCoreCR00669.002" type = "new"> Add
// SupportedConnectivityMemberTypes to
// ZoneCapabilities</change>
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_ZoneCapabilities
// ==================================================================
   [Version ( "2.10.0" ), 
    UMLPackagePath ( "CIM::Device::FC" ), 
    Description ( 
       "ZoneCapabilities exposes the capabilities for zoning of an "
       "AdminDomain." )]
class CIM_ZoneCapabilities : CIM_Capabilities {

      [Description ( 
          "The maximum length for the Zone Name that the "
          "AdminDomain is capable of supporting." )]
   uint32 ZoneNameMaxLen;

      [Description ( 
          "The ZoneNameFormat supported by the AdminDomain." ), 
       ValueMap { "0", "2", "3", "..", "0x8000.." }, 
       Values { "Unknown", "Numeric", "Alpha Numeric", 
          "DMTF Reserved", "Vendor Reserved" }]
   uint16 ZoneNameFormat;

      [Description ( 
          "The maximum number of ZoneSets that the AdminDomain is "
          "capable of supporting." )]
   uint32 MaxNumZoneSets;

      [Description ( 
          "The maximum number of Zones that the AdminDomain is "
          "capable of supporting." )]
   uint32 MaxNumZone;

      [Description ( 
          "The maximum number of ZoneMembers that the AdminDomain "
          "is capable of supporting." )]
   uint32 MaxNumZoneMembers;

      [Description ( 
          "The maximum number of Zones per ZoneSet that the "
          "AdminDomain is capable of supporting." )]
   uint32 MaxNumZonesPerZoneSet;

      [Description ( 
          "The maximum number of ZoneAliases that the AdminDomain "
          "is capable of supporting." )]
   uint32 MaxNumZoneAliases;


};
