// Copyright (c) 2006 DMTF.  All rights reserved.

// ==================================================================
// Optional Qualifiers
// Defined in the CIM Infrastructure Specification Section 2.5.3 
// ==================================================================

Qualifier Alias : string = null,
    Scope(property, reference, method),
    Flavor(Translatable);

Qualifier Delete : boolean = false,
    Scope(association, reference);

Qualifier Expensive : boolean = false,
    Scope(any);

Qualifier Ifdeleted : boolean = false,
    Scope(association, reference);

Qualifier Invisible : boolean = false,
    Scope(reference, association, class, property, method);

Qualifier Large : boolean = false,
    Scope(property, class);

Qualifier PropertyUsage : string = "CurrentContext",
    Scope(property);

Qualifier Provider : string = null,
    Scope(any);

Qualifier SyntaxType : string = null,
    Scope(property, reference, method, parameter);

Qualifier Syntax : string = null,
    Scope(property, reference, method, parameter);

Qualifier TriggerType : string = null,
    Scope(class, property, reference, method, association, indication);

Qualifier UnknownValues : string[],
    Scope(property),
    Flavor(DisableOverride);

Qualifier UnsupportedValues : string[],
    Scope(property),
    Flavor(DisableOverride);


