#!/bin/bash

# If its already built
# 	- remove it first
# 	- compile it.
# 	- compile the repository from scratch

make clean
make
make repository

# Unregister the provider if its already there and then Re-register it

make unregister
make regprovider

# Restart the cimserver (setting the authentication property to be true) for
# reloading the modified repository.

#cimserver -s; cimserver enableAuthentication=true
cimserver -s; cimserver
