#!/bin/bash
#
#
cimuser -r -u subodh
cimuser -r -u guest

cimuser -a -u subodh -w soni
cimuser -a -u guest -w guest
cimuser -l >> users
diff users users.mst
retval="$?"
echo $retval
if [ $retval != "0" ]
then
	echo "User configuration failed .... exiting .....try again"
	exit
else
	echo "Users Addition successfully completed...Now proceeding with the tests"
fi
