// Copyright (c) 2013 DMTF.  All rights reserved.
   [Association, Experimental, Version ( "2.40.0" ), 
    UMLPackagePath ( "CIM::Network::Routes" ), 
    Description ( 
       "CIM_VRFRoute associates a next hop route to a Virtual Routing "
       "and Forwarding context." )]
class CIM_VRFRoute : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Max ( 1 ), 
       Description ( "The VRF of  the route." )]
   CIM_VirtualRoutingAndForwardingTable REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( "The route." )]
   CIM_NextHopRoute REF Dependent;


};
