// Copyright (c) 2013 DMTF.  All rights reserved.
   [Version ( "2.40.0" ), 
    UMLPackagePath ( "CIM::Network::IP" ), 
    Description ( 
       "CIM_IPConfigurationService provides management of the IP "
       "configuration associated with a LANEndpoint or "
       "IPProtocolEndpoint or IPNetworkConnection or the global IP "
       "configuration for the ComputerSystem. "
       "CIM_IPConfigurationService also provides methods to support "
       "the additon and removal of an IPProtocolEndpoint to support "
       "the addition of a Layer 3 interface to a port, system or "
       "network." )]
class CIM_IPConfigurationService : CIM_Service {


      [Experimental, Description ( 
          "Add a CIM_StaticIPAssignmentSettingData configuration to "
          "the specified IPAssignmentSettingData instance. This "
          "will also create an instance of CIM_ConcreteDependency "
          "which associates the specified "
          "CIM_IPAssignmentSettingData instance with the newly "
          "created CIM_StaticIPAssignmentSettingData instance. The "
          "newly created instance of StaticIPAssignmentSettingData "
          "contains the IP configuration of an additional "
          "CIM_IPProtocolEndpoint which will be created. When the "
          "CIM_IPProtocolEndpoint is created depends on the value "
          "of the IsCurrent property of the CIM_ElementSettingData "
          "association which associates the "
          "CIM_IPAssignmentSettingData instance with the the "
          "CIM_LANEndpoint instance. If the IsCurrent property has "
          "a value of \"true\", the CIM_IPProtocolEndpoint will be "
          "created immediately. The instance of "
          "CIM_StaticIPAssignmentSettingData identified by the "
          "StaticSetting parameter will be associated with the "
          "newly created instance of CIM_IPProtocolEndpoint via an "
          "instance of CIM_ElementSettingData. If the the value of "
          "the IsCurrent property is \"false\", the "
          "CIM_IPProtocolEndpoint will be created the next time the "
          "IPAssignmentSettingData is applied to the LANEndpoint. "
          "Note: this method may be deprecated in the future in "
          "lieu of intrinsics once the limitations in CIM "
          "operations are addressed." ), 
       ValueMap { "0", "1", "2", "3", "4", "5..32767", "32768..65535" }, 
       Values { "Completed with No Error", "Not Supported", 
          "Unknown/Unspecified Error", "Failed", 
          "Invalid Parameter", "DMTF Reserved", "Vendor Reserved" }]
   uint32 AddStaticIPv4Interface(
         [Required, IN, Description ( 
             "The IPAssignmentSettingData to which a static IP "
             "interface will be added." )]
      CIM_IPAssignmentSettingData REF Configuration, 
         [IN ( false ), OUT, Description ( 
             "The created StaticIPAssignmentSettingData." )]
      CIM_StaticIPAssignmentSettingData REF StaticSetting, 
         [Required, IN, Description ( 
             "The IPv4 address requested." )]
      string Address, 
         [Required, IN, Description ( 
             "The requested subnet mask." )]
      string SubnetMask, 
         [IN, Description ( 
             "The requested default gateway. If \"null\", the "
             "GatewayIPv4Address property of the created "
             "CIM_StaticIPAssignmentSettingData instance will "
             "have a value of 0.0.0.0." )]
      string Gateway);

      [Experimental, Description ( 
          "Apply the configuration represented by the "
          "IPAssignmentSettingData to the specified LANEndpoint. "
          "This will result in the value of the IsCurrent property "
          "of the CIM_ElementSettingData which associates the "
          "specified CIM_IPAssignmentSettingData and specified "
          "CIM_LANEndpoint have a value of \"true\". The IsCurrent "
          "property of any other instances of "
          "CIM_ElementSettingData which reference the specified "
          "CIM_LANEndpoint and an instance of "
          "CIM_IPAssignmentSettingData will have a value of "
          "\"false\". Each instance of "
          "CIM_StaticIPAssignmentSettingData which is aggregated "
          "into the target CIM_IPAssignmentSettingData instance "
          "will result in the creation of an instance of "
          "CIM_IPProtocolEndpoint associated with the target "
          "CIM_LANEndpoint instance via an instance of the "
          "CIM_BindsTo association. The created "
          "CIM_IPProtocolEndpoint instance will have the values "
          "specified in the CIM_StaticIPAssignmentSettingData "
          "instance." ), 
       ValueMap { "0", "1", "2", "3", "4", "5", "4096", "..", 
          "32768..65535" }, 
       Values { "Completed with No Error", "Not Supported", 
          "Unknown/Unspecified Error", "Failed", 
          "Invalid Parameter", "Busy", 
          "Method Parameters Checked - Job Started", 
          "DMTF Reserved", "Vendor Reserved" }]
   uint32 ApplySettingToLANEndpoint(
         [Required, IN, Description ( 
             "The IPAssignmentSettingData to apply." )]
      CIM_IPAssignmentSettingData REF Configuration, 
         [Required, IN, Description ( 
             "The LANEndpoint to which the configuration will be applied."
              )]
      CIM_LANEndpoint REF Endpoint, 
         [IN ( false ), OUT, Description ( 
             "Reference to the job spawned if the operation "
             "continues after the method returns. (may be null "
             "if task completed)." )]
      CIM_ConcreteJob REF Job);

      [Description ( 
          "Apply the configuration represented by the "
          "CIM_IPAssignmentSettingData to the specified "
          "IPProtocolEndpoint. This will result in the value of the "
          "IsCurrent property of the CIM_ElementSettingData which "
          "associates the specified CIM_IPAssignmentSettingData and "
          "specified CIM_IPProtocolEndpoint having a value of "
          "\"true\". The IsCurrent property of any other instances "
          "of CIM_ElementSettingData which reference the specified "
          "CIM_IPProtocolEndpoint and an instance of "
          "CIM_IPAssignmentSettingData will have a value of "
          "\"false\". Each instance of CIM_IPAssignmentSettingData "
          "which is aggregated into the target "
          "CIM_IPAssignmentSettingData instance will be applied to "
          "the CIM_ProtocolEndpoint to which it is associated via "
          "an instance of CIM_ElementSettingData where the "
          "CIM_ProtocolEndpoint is associated with the target "
          "CIM_IPProtocolEndpoint via an instance of "
          "CIM_EndpointIdentity." ), 
       ValueMap { "0", "1", "2", "3", "4", "5", "4096", "..", 
          "32768..65535" }, 
       Values { "Completed with No Error", "Not Supported", 
          "Unknown/Unspecified Error", "Failed", 
          "Invalid Parameter", "Busy", 
          "Method Parameters Checked - Job Started", 
          "DMTF Reserved", "Vendor Reserved" }]
   uint32 ApplySettingToIPProtocolEndpoint(
         [Required, IN, Description ( 
             "The IPAssignmentSettingData to apply." )]
      CIM_IPAssignmentSettingData REF Configuration, 
         [Required, IN, Description ( 
             "The IPProtocolEndpoint to which the configuration "
             "will be applied." )]
      CIM_IPProtocolEndpoint REF Endpoint, 
         [IN ( false ), OUT, Description ( 
             "Reference to the job spawned if the operation "
             "continues after the method returns. This parameter "
             "MUST NOT be null if a value of 4096 is returned. "
             "This parameter MUST be null if any other value is "
             "returned by the method." )]
      CIM_ConcreteJob REF Job);

      [Description ( 
          "Apply the IP Version respresented by the "
          "CIM_IPVersionSettingData to the specified "
          "ComputerSystem. The IP Version may take effect or "
          "disable immediatley or may be set to take effect or "
          "disable in the next boot, depending on ComputerSystem "
          "and the value specified for Mode. This will reflect in "
          "the IsCurrent & IsNext property of "
          "CIM_ElementSettingData associating the "
          "IPVersionSettingData with the ComputerSystem. Refer the "
          "description for the Mode parameter for more details." ), 
       ValueMap { "0", "1", "2", "4096", "..", "32768..65535" }, 
       Values { "Completed with No Error", "Not Supported", 
          "Failed", "Job Started", "DMTF Reserved", "Vendor Reserved" }]
   uint32 ApplySettingToComputerSystem(
         [Required, IN, Description ( 
             "The IPVersionSettingData to be apply." )]
      CIM_IPVersionSettingData REF IPVersionSettingData, 
         [Required, IN, Description ( 
             "The ComputerSystem to which the setting will be applied"
              )]
      CIM_ComputerSystem REF ComputerSystem, 
         [Required, IN, Description ( 
             "The mode in which the configuration need to be "
             "applied to the ComputerSystem.\n"
             "Mode 0 - implies use Mode 1 if allowed, else Mode 2.\n"
             "Mode 1 - Results in IsNext = 1 (Is Next), "
             "IsCurrent = 1 (Is Current) for the "
             "CIM_ElementSettingData associating the setting "
             "with ComputerSystem.\n"
             "Mode 2 - Results in IsNext = 1 (Is Next) for the "
             "CIM_ElementSettingData associating the setting "
             "with ComputerSystem. The value of IsCurrent will "
             "not be affected.\n"
             "Mode 3 - implies use Mode 4 if allowed, else Mode 5.\n"
             "Mode 4 - Results in IsNext = 2 (Is Not Next), "
             "IsCurrent = 2 (Is Not Current) for the "
             "CIM_ElementSettingData associating the setting "
             "with ComputerSystem.\n"
             "Mode 5 - Results in IsNext = 2 (Is Not Next) for "
             "the CIM_ElementSettingData associating the setting "
             "with ComputerSystem. The value of IsCurrent will "
             "not be affected.\n"
             "Mode 6 - Results in IsNext = 3 (Is Next For Single "
             "Use)for the CIM_ElementSettingData associating the "
             "setting with ComputerSystem. The value of "
             "IsCurrent will not be affected. To change the "
             "IsNext=3 (Is Next For Single Use) for a Setting, "
             "invoke the method with any of the other values for "
             "the mode." ), 
          ValueMap { "0", "1", "2", "3", "4", "5", "6", "..", 
             "32768..65535" }, 
          Values { "Mode 0", "Mode 1", "Mode 2", "Mode 3", 
             "Mode 4", "Mode 5", "Mode 6", "DMTF Reserved", 
             "Vendor Reserved" }]
      uint16 Mode, 
         [IN ( false ), OUT, Description ( 
             "Reference to the job spawned if the operation "
             "continues after the method returns. (may be null "
             "if task completed)." )]
      CIM_ConcreteJob REF Job);

      [Description ( 
          "Apply the IP setting respresented by the "
          "CIM_IPAssignmentSettingData and/or the IPVersion Setting "
          "respresented by the CIM_IPVersionSettingData to the "
          "specified IPNetworkConnection. The settings may take "
          "effect or disable immediatley or may be set to take "
          "effect or disable in the next boot, depending on system, "
          "IPNetworkConnection, Setting and the value specified for "
          "Mode. This will reflect in the IsCurrent & IsNext "
          "property of instances of CIM_ElementSettingData "
          "associating the SettingData and or IPVersionSettingData "
          "with the IPNetworkConnection. For cases, enabling one "
          "setting can result in automatic disabling of another "
          "setting, it will be refelected in the properties of "
          "ElementSettingData associating those settings to the "
          "IPNetworkConnection.Refer the description for the Mode "
          "parameter for more details.\n"
          "At least one of the SettingData or IPVersionSettingData "
          "is required in the method call; both may be specified on "
          "the same method call." ), 
       ValueMap { "0", "1", "2", "4096", "..", "32768..65535" }, 
       Values { "Completed with No Error", "Not Supported", 
          "Failed", "Job Started", "DMTF Reserved", "Vendor Reserved" }]
   uint32 ApplySettingToIPNetworkConnection(
         [IN, Description ( 
             "The IPAssignmentSettingData to apply." )]
      CIM_IPAssignmentSettingData REF SettingData, 
         [IN, Description ( 
             "The IPVersionSettingData to be apply." )]
      CIM_IPVersionSettingData REF IPVersionSettingData, 
         [Required, IN, Description ( 
             "The IPNetworkConnection to which the setting will be applied"
              )]
      CIM_IPNetworkConnection REF IPNetworkConnection, 
         [Required, IN, Description ( 
             "The mode in which the configuration need to be "
             "applied to the IPNetworkConnection.\n"
             "Mode 0 - implies use Mode 1 if allowed, else Mode 2.\n"
             "Mode 1 - Results in IsNext = 1 (Is Next), "
             "IsCurrent = 1 (Is Current) for the "
             "CIM_ElementSettingData associating the setting "
             "with IPNetworkConnection.\n"
             "Mode 2 - Results in IsNext = 1 (Is Next) for the "
             "CIM_ElementSettingData associating the setting "
             "with IPNetworkConnection. The value of IsCurrent "
             "will not be affected.\n"
             "Mode 3 - implies use Mode 4 if allowed, else Mode 5.\n"
             "Mode 4 - Results in IsNext = 2 (Is Not Next), "
             "IsCurrent = 2 (Is Not Current) for the "
             "CIM_ElementSettingData associating the setting "
             "with IPNetworkConnection.\n"
             "Mode 5 - Results in IsNext = 2 (Is Not Next) for "
             "the CIM_ElementSettingData associating the setting "
             "with IPNetworkConnection. The value of IsCurrent "
             "will not be affected.\n"
             "Mode 6 - Results in IsNext = 3 (Is Next For Single "
             "Use)for the CIM_ElementSettingData associating the "
             "setting with IPNetworkConnection. The value of "
             "IsCurrent will not be affected. To change the "
             "IsNext=3 (Is Next For Single Use) for a Setting, "
             "invoke the method with any of the other values for "
             "the mode." ), 
          ValueMap { "0", "1", "2", "3", "4", "5", "6", "..", 
             "32768..65535" }, 
          Values { "Mode 0", "Mode 1", "Mode 2", "Mode 3", 
             "Mode 4", "Mode 5", "Mode 6", "DMTF Reserved", 
             "Vendor Reserved" }]
      uint16 Mode, 
         [IN ( false ), OUT, Description ( 
             "Reference to the job spawned if the operation "
             "continues after the method returns. (may be null "
             "if task completed)." )]
      CIM_ConcreteJob REF Job);

      [Experimental, Description ( 
          "Defines and assigns an CIM_IPProtocolEndpoint subclass "
          "to a CIM_ComputerSystem, CIM_EthernetPort or a "
          "CIM_Network instance. The provider should use default "
          "values for properites that are not populated in the "
          "embedded instance." ), 
       ValueMap { "0", "1", "2", "3", "4", "5", "4096", "..", 
          "32768..65535" }, 
       Values { "Completed with No Error", "Not Supported", 
          "Unknown/Unspecified Error", "Failed", 
          "Invalid Parameter", "Busy", 
          "Method Parameters Checked - Job Started", 
          "DMTF Reserved", "Vendor Reserved" }]
   uint32 AddIPProtocolEndpoint(
         [Description ( 
             "Optional reference to an associated interface or "
             "system. This is usally an instance of "
             "CIM_EthernetPort, or a VLANNetwork. If no value is "
             "provided the new IPProtocolEndpoint \r\n"
             "instances are associated with the ComputerSystem "
             "instance representing the host of the service. The "
             "new IPProtocolEndpoint instance should also be "
             "associated though an instance of "
             "CIM_ServiceAffectsElement to the instance of "
             "IPConfigurationService from which the method was "
             "called." )]
      CIM_ManagedElement REF TargetInterface, 
         [Description ( 
             "An array of string containing embedded instances "
             "of the class-subclass of CIM_IPProtocolEndpoint "
             "that describes the configuration of the new "
             "IPProtocolEndpoints" ), 
          EmbeddedInstance ( "CIM_IPProtocolEndpoint" )]
      string IPProtocolEndpoint[], 
         [Description ( 
             "An array of strings each containing an embedded "
             "instance of class-subclass of CIM_SettingData that "
             "are to be associated with the new IP protocol "
             "endpoint. Generally these should be associated to "
             "the CIM_IPProtocolEndpoint instance through an "
             "instance of CIM_ElementSettingData. This array of "
             "instances shall be indexed one to one with the "
             "embedded instances contained in the "
             "IPProtocolEndpoint parameter." ), 
          EmbeddedInstance ( "CIM_SettingData" )]
      string EndpointSettings[], 
         [In ( false ), Out, Description ( 
             "If the addition of a protocol endpoint is "
             "successfully, a reference to the instance of class "
             "CIM_IPProtocolEndpoint that represents the newly "
             "defined endpoints are returned." )]
      CIM_IPProtocolEndpoint REF ResultingEndpoint[], 
         [In ( false ), Out, Description ( 
             "If the operation is long running, then optionally "
             "a job may be returned." )]
      CIM_ConcreteJob REF Job);

      [Experimental, Description ( 
          "Removes one more IPProtocolEndpoint classes or "
          "subclasses instances." ), 
       ValueMap { "0", "1", "2", "3", "4", "5", "4096", "..", 
          "32768..65535" }, 
       Values { "Completed with No Error", "Not Supported", 
          "Unknown/Unspecified Error", "Failed", 
          "Invalid Parameter", "Busy", 
          "Method Parameters Checked - Job Started", 
          "DMTF Reserved", "Vendor Reserved" }]
   uint32 RemoveIPProtocolEndpoint(
         [Description ( 
             "Reference to the targeted instances of CIM_ProtocolEndpoint."
              )]
      CIM_IPProtocolEndpoint REF Endpoint[], 
         [In ( false ), Out, Description ( 
             "If the operation is long running, then optionally "
             "a job may be returned." )]
      CIM_ConcreteJob REF Job);

};
