// Copyright (c) 2012 DMTF.  All rights reserved.
   [Version ( "2.35.0" ), 
    UMLPackagePath ( "CIM::Network::IP" ), 
    Description ( 
       "\"CIM_IPNetworkConnection class represents service access "
       "point for the IP interface configuration in the system, Eg. "
       "\"IP stack configuration on a Local Area Connection\",\"IP "
       "stack configuration on a ethernet interface\". \n"
       "An IP network connection is an aggregation point of different "
       "types of settings that can be applied to an IP interface to "
       "represent protocol end points\"." )]
class CIM_IPNetworkConnection : CIM_ServiceAccessPoint {

      [Description ( 
          "This shall contain a free form string, that identifies "
          "the IP network connection." )]
   string ID;


};
