// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_LogicalDisk
// ==================================================================
   [UMLPackagePath ( "CIM::Device::StorageExtents" ),
    Version ( "2.6.0" ), Description (
       "A LogicalDisk is a presentation of a contiguous range of "
       "logical blocks that is identifiable by a FileSystem via the "
       "Disk's DeviceId (key) field. For example in a Windows "
       "environment, the DeviceID field would contain a drive letter. "
       "In a Unix environment, it would contain the access path; and "
       "in a NetWare environment, DeviceID would contain the volume "
       "name. LogicalDisks are typically built on a DiskPartition or "
       "Storage Volume (for example, exposed by a software volume "
       "manager) using the LogicalDiskBasedOnPartition or "
       "LogicalDiskBasedOn Volume associations. However, it can be "
       "based on other StorageExtents, like CIM_Memory, in the case of "
       "a RAM disk. The latter is described using the "
       "LogicalDiskBasedOnExtent relationship. (Indeed, the "
       "BasedOnExtent association is the superclass for the "
       "BasedOnPartition and BasedOnVolume relationships.)")]
class CIM_LogicalDisk : CIM_StorageExtent {
};
