// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_VideoController
// ==================================================================
   [UMLPackagePath ( "CIM::Device::Controller" ), Version ( "2.8.0" ), 
    Description (
       "Capabilities and management of the VideoController.")]
class CIM_VideoController : CIM_Controller {

      [Override ( "Description" ), 
       MappingStrings { "MIF.DMTF|Video|004.18" }]
   string Description;

      [Description (
          "A free-form string describing the video "
          "processor/Controller.")]
   string VideoProcessor;

      [Description (
          "An integer enumeration indicating the type of video memory."), 
       ValueMap { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10",
          "11", "12", "13" }, 
       Values { "Other", "Unknown", "VRAM", "DRAM", "SRAM", "WRAM",
          "EDO RAM", "Burst Synchronous DRAM", "Pipelined Burst SRAM", 
          //10 
          "CDRAM", "3DRAM", "SDRAM", "SGRAM" }, 
       MappingStrings { "MIF.DMTF|Video|004.6" }]
   uint16 VideoMemoryType;

      [Description (
          "Number of video pages supported given the current "
          "resolutions and available memory.")]
   uint32 NumberOfVideoPages;

      [Description (
          "Maximum amount of memory supported in bytes."), 
       Units ( "Bytes" )]
   uint32 MaxMemorySupported;

      [Description (
          "An array of integers indicating the graphics and 3D "
          "capabilities of the VideoController."), 
       ValueMap { "0", "1", "2", "3", "4", "5", "6", "7", "8" }, 
       Values { "Unknown", "Other", "Graphics Accelerator",
          "3D Accelerator", "PCI Fast Write", "MultiMonitor Support",
          "PCI Mastering", "Second Monochrome Adapter Support",
          "Large Memory Address Support" }, ArrayType ( "Indexed" ), 
       ModelCorrespondence { 
          "CIM_VideoController.CapabilityDescriptions" }]
   uint16 AcceleratorCapabilities[];

      [Description (
          "An array of free-form strings providing more detailed "
          "explanations for any of the video Accelerator features "
          "indicated in the Capabilities array. Note, each entry of "
          "this array is related to the entry in the Capabilities "
          "array that is located at the same index."), 
       ArrayType ( "Indexed" ), 
       ModelCorrespondence { 
          "CIM_VideoController.AcceleratorCapabilities" }]
   string CapabilityDescriptions[];

      [Description (
          "The number of bits used to display each pixel."), 
       Units ( "Bits" ), 
       MappingStrings { "MIF.DMTF|Video|004.12" }]
   uint32 CurrentBitsPerPixel;

      [Description (
          "Current number of horizontal pixels."), 
       Units ( "Pixels" ), 
       MappingStrings { "MIF.DMTF|Video|004.11" }]
   uint32 CurrentHorizontalResolution;

      [Description (
          "Current number of vertical pixels."), 
       Units ( "Pixels" ), 
       MappingStrings { "MIF.DMTF|Video|004.10" }]
   uint32 CurrentVerticalResolution;

      [Description (
          "Maximum refresh rate of the VideoController in Hertz."), 
       Units ( "Hertz" ), 
       MappingStrings { "MIF.DMTF|Video|004.5" }]
   uint32 MaxRefreshRate;

      [Description (
          "Minimum refresh rate of the Video Controller in Hertz."), 
       Units ( "Hertz" ), 
       MappingStrings { "MIF.DMTF|Video|004.4" }]
   uint32 MinRefreshRate;

      [Description (
          "Current refresh rate in Hertz."), 
       Units ( "Hertz" ), 
       MappingStrings { "MIF.DMTF|Video|004.15" }]
   uint32 CurrentRefreshRate;

      [Description (
          "Current scan mode. \"Interlaced\" (value=3) or \"Non "
          "Interlaced\" (4) can be defined using this property."), 
       ValueMap { "1", "2", "3", "4" }, 
       Values { "Other", "Unknown", "Interlaced", "Non Interlaced" }, 
       MappingStrings { "MIF.DMTF|Video|004.8" }]
   uint16 CurrentScanMode;

      [Description (
          "If in character mode, number of rows for this Video "
          "Controller. Otherwise, enter 0."), 
       MappingStrings { "MIF.DMTF|Video|004.13" }]
   uint32 CurrentNumberOfRows;

      [Description (
          "If in character mode, number of columns for this "
          "VideoController. Otherwise, enter 0."), 
       MappingStrings { "MIF.DMTF|Video|004.14" }]
   uint32 CurrentNumberOfColumns;

      [Description (
          "Number of colors supported at the current resolutions.")]
   uint64 CurrentNumberOfColors;
};
