// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_QueueForPrintService
// ==================================================================
   [Association, UMLPackagePath ( "CIM::Device::Printing" ),
       Version ( "2.6.0" ), Description (
       "This association indicates that a PrintService utilizes a "
       "particular PrintQueue.")]
class CIM_QueueForPrintService : CIM_Dependency {

      [Override ( "Antecedent" ), Description (
          "The PrintQueue that the Service utilizes.")]
   CIM_PrintQueue REF Antecedent;

      [Override ( "Dependent" ), Description (
          "The PrintService that puts Jobs on the Queue.")]
   CIM_PrintService REF Dependent;

      [Description (
          "Indicates that the PrintService can accept Jobs and place "
          "them on the Queue.")]
   boolean QueueAcceptingFromService;
};
