// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_PCVideoController
// ==================================================================
   [UMLPackagePath ( "CIM::Device::Controller" ), Version ( "2.6.0" ), 
    Description (
       "Capabilities and management of a PCVideoController, a subtype "
       "of VideoController.")]
class CIM_PCVideoController : CIM_VideoController {

      [Description (
          "The video architecture. For example, VGA (value=5) or PC-98 "
          "(160) may be specified."), 
       ValueMap { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10",
          "11", "12", "160" }, 
       Values { "Other", "Unknown", "CGA", "EGA", "VGA", "SVGA", "MDA",
          "HGC", "MCGA", 
          // 10                
          "8514A", "XGA", "Linear Frame Buffer", "PC-98" }, 
       MappingStrings { "MIF.DMTF|Video|004.2" }]
   uint16 VideoArchitecture;

      [Description (
          "Current video mode."), 
       MappingStrings { "MIF.DMTF|Video|004.3" }]
   uint16 VideoMode;

      [Description (
          "Current number of color planes. If this value is not "
          "applicable for the current video configuration, enter 0.")]
   uint16 NumberOfColorPlanes;
};
