// Copyright (c) 2005 DMTF.  All rights reserved.
   [Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::User::SecurityServices" ), 
    Description ( 
       "CIM_CredentialManagementService issues credentials and manages "
       "the credential lifecycle." )]
class CIM_CredentialManagementService : CIM_AuthenticationService {


};
