//Copyright c 2007 DMTF.  All rights reserved.
   [Experimental, Version ( "2.16.0" ), 
    UMLPackagePath ( "CIM::Device::CoolingAndPower" ), 
    Description ( 
       "CIM_PowerTopologyCapabilities describes the capabilities of "
       "the associated CIM_PowerConfigurationService." )]
class CIM_PowerTopologyCapabilities : CIM_EnabledLogicalElementCapabilities {

      [Description ( 
          "Each enumeration corresponds to support for the "
          "like-named method of the PowerTopologyService." ), 
       ValueMap { "2", "3", "..", "0x8000.." }, 
       Values { "ChangeAffectedElementsAssignedSequence", 
          "ConfigureExternalPowerSources", "DMTF Reserved", 
          "Vendor Specific" }]
   uint16 SupportedMethods[];


};
