// Copyright (c) 2011 DMTF.  All rights reserved.
   [Association, Experimental, Aggregation, Version ( "2.28.0" ), 
    UMLPackagePath ( "CIM::Device::ComponentElement" ), 
    Description ( 
       "This aggregates Pool view class instances to the CIM_System "
       "that scopes the underlying Pools of the View Classes." )]
class CIM_HostedStoragePoolView : CIM_AbstractComponent {

      [Key, Override ( "GroupComponent" ), 
       Description ( 
          "The CIM_System instance that scopes the underlying Pool "
          "instance of the view class." )]
   CIM_System REF GroupComponent;

      [Key, Override ( "PartComponent" ), 
       Description ( 
          "The view class instance that is a Pool on the CIM_System instance."
           )]
   CIM_StoragePoolView REF PartComponent;


};
