// Copyright (c) 2012 DMTF.  All rights reserved.
   [Experimental, Version ( "2.34.0" ), 
    UMLPackagePath ( "CIM::Device::StorageServices" ), 
    Description ( 
       "A RemoteReplicationCollection collects all paths (for example, "
       "ProtocolEndpoints) that provide access to a remote system for "
       "replication operations." )]
class CIM_RemoteReplicationCollection : CIM_ConnectivityCollection {

      [Override ( "ElementName" ), 
       Write, Description ( 
          "A user-friendly name for the RemoteReplicationCollection." )]
   string ElementName;

      [Write, Description ( 
          "Indicates that this RemoteReplicationCollection is "
          "currently active and allows replication traffic to/from "
          "remote elements." )]
   boolean Active = true;

      [Write, Description ( 
          "The instance of RemoteReplicationCollection will be "
          "deleted when it is no longer associated with an access "
          "point." )]
   boolean DeleteOnUnassociated = false;

      [Write, Description ( 
          "The property indicates if hardware compression is "
          "enabled -- the transmitted/received data is compressed "
          "by hardware." )]
   boolean HardwareCompressionEnabled = false;

      [Write, Description ( 
          "The property indicates if software compression is "
          "enabled -- the transmitted/received data is compressed "
          "by sofware." )]
   boolean SoftwareCompressionEnabled = false;


};
