// Copyright (c) 2005 DMTF.  All rights reserved.
   [Experimental, Version ( "2.10.0" ), 
    UMLPackagePath ( "CIM::Device::PowerMgmt" ), 
    Description ( 
       "Statistical information related to the powered-on time of a "
       "Managed Element." )]
class CIM_PoweredStatisticalData : CIM_StatisticalData {

      [Description ( 
          "The amount of consecutive time that the managed element "
          "has been powered on." )]
   datetime PowerOnHours;

      [Description ( 
          "The total amount of time that the managed element has "
          "been powered on." )]
   datetime TotalPowerOnHours;


};
