// Copyright (c) 2012 DMTF.  All rights reserved.
   [Version ( "2.34.0" ), 
    UMLPackagePath ( "CIM::Device::Ports" ), 
    Description ( 
       "This class defines the current configuration of a data center "
       "ethernet (DCE) port." )]
class CIM_DataCenterEthernetPort : CIM_LLDPEthernetPort {

      [Description ( 
          "The allowance made for round-trip propagation delay of "
          "the link in bits. The value of this object must be "
          "retained across reinitializations of the management "
          "system." ), 
       MappingStrings { 
          "MIB.IEEE|IEEE8021-PFC-MIB.ieee8021PfcLinkDelayAllowance" }]
   uint32 PfcLinkDelayAllowance;

      [Description ( 
          "This property determines whether the IEEE 802.1 "
          "organizationally defined ETS Configuration TLV "
          "transmission is allowed on a given LLDP transmission "
          "capable port." ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxConfigETSConfigurationTxEnable" }]
   boolean ETSConfigurationTxEnable;

      [Description ( 
          "This property determines whether the IEEE 802.1 "
          "organizationally defined ETS Recommendation TLV "
          "transmission is allowed on a given LLDP transmission "
          "capable port." ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxConfigETSRecommendationTxEnable" }]
   boolean ETSRecommendationTxEnable;

      [Description ( 
          "This property determines whether the IEEE 802.1 "
          "organizationally defined Priority-based Flow Control TLV "
          "transmission is allowed on a given LLDP transmission "
          "capable port." ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxConfigPFCTxEnable" }]
   boolean PFCTxEnable;

      [Description ( 
          "This property determines whether the IEEE 802.1 "
          "organizationally defined Application Priority TLV "
          "transmission is allowed on a given LLDP transmission "
          "capable port." ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxConfigApplicationPriorityTxEnable" }]
   boolean ApplicationPriorityTxEnable;

      [Description ( 
          "Indicates if the credit-based shaper Traffic Selection "
          "Algorithm is supported on this port." ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxLocETSConCreditBasedShaperSupport" }]
   boolean LocETSConCreditBasedShaperSupport;

      [Description ( 
          "Indicates the number of traffic classes supported on this port."
           ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxLocETSConTrafficClassesSupported" }]
   uint8 LocETSConTrafficClassesSupported;

      [Description ( 
          "Indicates if the local system is willing to accept the "
          "ETS configuration recommended by the remote system." ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxLocETSConWilling" }]
   boolean LocETSConWilling;

      [Description ( 
          "Indicates the priorities that are assigned to traffic classes."
           ), 
       ArrayType ( "Indexed" ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxLocETSConPriority" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.LocETSConPriTrafficClass" }]
   uint8 LocETSConPriority[];

      [Description ( 
          "Indicates the traffic classes to which priorities are assigned."
           ), 
       ArrayType ( "Indexed" ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxLocETSConPriTrafficClass" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.LocETSConPriority" }]
   uint8 LocETSConPriTrafficClass[];

      [Description ( 
          "Indicates the traffic classes to which bandwidth values "
          "indicated by the "
          "CIM_DataCenterEthernetPort.LocETSConTrafficClassBandwidth "
          "apply." ), 
       ArrayType ( "Indexed" ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxLocETSConTrafficClass" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.LocETSConTrafficClassBandwidth" }]
   uint8 LocETSConTrafficClass[];

      [Description ( 
          "Indicates the % of link bandwidths assigned to traffic "
          "classes. The sum of % bandwidths in this array shall be "
          "100." ), 
       ArrayType ( "Indexed" ), 
       MinValue ( 0 ), 
       MaxValue ( 100 ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxLocETSConTrafficClassBandwidth" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.LocETSConTrafficClass" }, 
       PUnit ( "percent" )]
   uint8 LocETSConTrafficClassBandwidth[];

      [Description ( 
          "Indicates the traffic classes that are assigned traffic "
          "selection algorithms." ), 
       ArrayType ( "Indexed" ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxLocETSConTSATrafficClass" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.LocETSConTrafficSelectionAlgorithm" }]
   uint8 LocETSConTSATrafficClass[];

      [Description ( 
          "Indicates the Traffic Selection Algorithms to which "
          "traffic classes are assigned.\"" ), 
       ValueMap { "0", "1", "2", "..", "255" }, 
       Values { "Strict Priority", "Credit-based shaper", 
          "Enhanced transmission selection", "DMTF Reserved", 
          "Vendor Reserved" }, 
       ArrayType ( "Indexed" ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxLocETSConTrafficSelectionAlgorithm" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.LocETSConTSATrafficClass" }]
   uint8 LocETSConTrafficSelectionAlgorithm[];

      [Description ( 
          "Indicates the traffic classes to which bandwidths apply. "
          "Used for recommendation TLV." ), 
       ArrayType ( "Indexed" ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxLocETSRecoTrafficClass" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.LocETSRecoTrafficClassBandwidth" }]
   uint8 LocETSRecoTrafficClass[];

      [Description ( 
          "Indicates the bandwidths assigned to traffic classes for "
          "recommendation TLV." ), 
       ArrayType ( "Indexed" ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxLocETSRecoTrafficClassBandwidth" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.LocETSRecoTrafficClass" }, 
       PUnit ( "bit / second" )]
   uint64 LocETSRecoTrafficClassBandwidth[];

      [Description ( 
          "Indicates the traffic classes that are assigned to "
          "traffic selection algorithms. Used for Recommendation "
          "TLV." ), 
       ArrayType ( "Indexed" ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxETSRecoTSATrafficClass" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.LocETSRecoTrafficSelectionAlgorithm" }]
   uint8 LocETSRecoTSATrafficClass[];

      [Description ( 
          "Indicates the Traffic Selection Algorithms to which "
          "traffic classes are to be assigned. Used for "
          "Recommendation TLV." ), 
       ValueMap { "0", "1", "2", "..", "255" }, 
       Values { "Strict Priority", "Credit-based shaper", 
          "Enhanced transmission selection", "DMTF Reserved", 
          "Vendor Reserved" }, 
       ArrayType ( "Indexed" ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxLocETSRecoTrafficSelectionAlgorithm" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.LocETSRecoTSATrafficClass" }]
   uint8 LocETSRecoTrafficSelectionAlgorithm[];

      [Description ( 
          "Indicates if the local system is willing to accept the "
          "PFC configuration of the remote system on this port." ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxLocPFCWilling" }, 
       ModelCorrespondence { "CIM_DataCenterEthernetPort.LocPFCMBC", 
          "CIM_DataCenterEthernetPort.LocPFCCap" }]
   boolean LocPFCWilling;

      [Description ( 
          "Indicates if the local system is capable of bypassing "
          "MACsec processing when MACsec is disabled." ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxLocPFCMBC" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.LocPFCWilling", 
          "CIM_DataCenterEthernetPort.LocPFCCap" }]
   boolean LocPFCMBC;

      [Description ( 
          "Indicates the number of traffic classes on the local "
          "port that may simultaneously have PFC enabled." ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxLocPFCCap" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.LocPFCWilling", 
          "CIM_DataCenterEthernetPort.LocPFCMBC" }]
   uint8 LocPFCCap;

      [Description ( "Prioity for which PFC is enabled / disabled" ), 
       ArrayType ( "Indexed" ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxLocPFCEnablePriority" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.LocPFCEnableEnabled" }]
   uint8 LocPFCEnablePriority[];

      [Description ( 
          "Indicates if PFC is enabled on the corresponding priority."
           ), 
       ArrayType ( "Indexed" ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxLocPFCEnableEnabled" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.LocPFCEnablePriority" }]
   boolean LocPFCEnableEnabled[];

      [Description ( "Indicates the contents of the protocol object" ), 
       ValueMap { "1", "2", "3", "4", ".." }, 
       Values { "Ethertype", "Well Known Port number over TCP/SCTP", 
          "Well Known Port number over UDP/DCCP", 
          "Well Known Port number over TCP/SCTP/UDP/DCCP", 
          "DMTF Reserved" }, 
       ArrayType ( "Indexed" ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxLocApplicationPriorityAESelector" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.LocApplicationPriorityAEProtocol", 
          "CIM_DataCenterEthernetPort.LocApplicationPriorityAEPriority" }]
   uint16 LocApplicationPriorityAESelector[];

      [Description ( 
          "The protocol indicator of the type indicated by "
          "LocApplicationPriorityAESelector." ), 
       ArrayType ( "Indexed" ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxLocApplicationPriorityAEProtocol" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.LocApplicationPriorityAESelector", 
          "CIM_DataCenterEthernetPort.LocApplicationPriorityAEPriority" }]
   uint16 LocApplicationPriorityAEProtocol[];

      [Description ( 
          "The priority code point that should be used in frames "
          "transporting the protocol indicated by\n"
          "LocApplicationPriorityAESelector and\n"
          "LocApplicationPriorityAEProtocol properties." ), 
       ArrayType ( "Indexed" ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxLocApplicationPriorityAEPriority" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.LocApplicationPriorityAESelector", 
          "CIM_DataCenterEthernetPort.LocApplicationPriorityAEProtocol" }]
   uint8 LocApplicationPriorityAEPriority[];

      [Write ( false ), Description ( 
          "Indicates if the credit-based shaper Traffic Selection "
          "Algorithm is supported on the remote port." ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxRemETSConCreditBasedShaperSupport" }]
   boolean RemETSConCreditBasedShaperSupport;

      [Write ( false ), Description ( 
          "Indicates the number of traffic classes supported on the "
          "remote port." ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxRemETSConTrafficClassesSupported" }]
   uint8 RemETSConTrafficClassesSupported;

      [Write ( false ), Description ( 
          "Indicates if the remote system is willing to accept the "
          "ETS configuration recommended by the local system." ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxRemETSConWilling" }]
   boolean RemETSConWilling;

      [Write ( false ), Description ( 
          "Indicates the priorities that are assigned to traffic "
          "classes on the remote port." ), 
       ArrayType ( "Indexed" ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxRemETSConPriority" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.RemETSConPriTrafficClass" }]
   uint8 RemETSConPriority[];

      [Write ( false ), Description ( 
          "Indicates the traffic classes to which priorities are "
          "assigned on the remote port." ), 
       ArrayType ( "Indexed" ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxRemETSConPriTrafficClass" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.RemETSConPriority" }]
   uint8 RemETSConPriTrafficClass[];

      [Write ( false ), Description ( 
          "Indicates the traffic classes to which bandwidth values "
          "indicated by the "
          "CIM_DataCenterEthernetPort.RemETSConTrafficClassBandwidth "
          "apply." ), 
       ArrayType ( "Indexed" ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxRemETSConTrafficClass" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.RemETSConTrafficClassBandwidth" }]
   uint8 RemETSConTrafficClass[];

      [Write ( false ), Description ( 
          "Indicates the % of link bandwidths assigned to traffic "
          "classes on the remote port. The sum of % bandwidths in "
          "this array shall be 100." ), 
       ArrayType ( "Indexed" ), 
       MinValue ( 0 ), 
       MaxValue ( 100 ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxRemETSConTrafficClassBandwidth" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.RemETSConTrafficClass" }, 
       PUnit ( "percent" )]
   uint8 RemETSConTrafficClassBandwidth[];

      [Write ( false ), Description ( 
          "Indicates the traffic classes that are assigned traffic "
          "selection algorithms on the remote port." ), 
       ArrayType ( "Indexed" ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxRemETSConTSATrafficClass" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.RemETSConTrafficSelectionAlgorithm" }]
   uint8 RemETSConTSATrafficClass[];

      [Write ( false ), Description ( 
          "Indicates the Traffic Selection Algorithms to which "
          "traffic classes are assigned on the remote port.\"" ), 
       ValueMap { "0", "1", "2", "..", "255" }, 
       Values { "Strict Priority", "Credit-based shaper", 
          "Enhanced transmission selection", "DMTF Reserved", 
          "Vendor Reserved" }, 
       ArrayType ( "Indexed" ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxRemETSConTrafficSelectionAlgorithm" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.RemETSConTSATrafficClass" }]
   uint8 RemETSConTrafficSelectionAlgorithm[];

      [Description ( 
          "Indicates the traffic classes to which bandwidths apply "
          "on the remote port. Used for recommendation TLV." ), 
       ArrayType ( "Indexed" ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxRemETSRecoTrafficClass" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.RemETSRecoTrafficClassBandwidth" }]
   uint8 RemETSRecoTrafficClass[];

      [Write ( false ), Description ( 
          "Indicates the bandwidths assigned to traffic classes for "
          "recommendation TLV on the remote port." ), 
       ArrayType ( "Indexed" ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxRemETSRecoTrafficClassBandwidth" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.RemETSRecoTrafficClass" }, 
       PUnit ( "bit / second" )]
   uint64 RemETSRecoTrafficClassBandwidth[];

      [Write ( false ), Description ( 
          "Indicates the traffic classes that are assigned to "
          "traffic selection algorithms on the remote port. Used "
          "for Recommendation TLV." ), 
       ArrayType ( "Indexed" ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxRemETSRecoTSATrafficClass" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.RemETSRecoTrafficSelectionAlgorithm" }]
   uint8 RemETSRecoTSATrafficClass[];

      [Write ( false ), Description ( 
          "Indicates the Traffic Selection Algorithms to which "
          "traffic classes are to be assigned on the remote port. "
          "Used for Recommendation TLV." ), 
       ValueMap { "0", "1", "2", "..", "255" }, 
       Values { "Strict Priority", "Credit-based shaper", 
          "Enhanced transmission selection", "DMTF Reserved", 
          "Vendor Reserved" }, 
       ArrayType ( "Indexed" ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxRemETSRecoTrafficSelectionAlgorithm" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.RemETSRecoTSATrafficClass" }]
   uint8 RemETSRecoTrafficSelectionAlgorithm[];

      [Write ( false ), Description ( 
          "Indicates if the remote system is willing to accept the "
          "PFC configuration of the local system on this port." ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxRemPFCWilling" }, 
       ModelCorrespondence { "CIM_DataCenterEthernetPort.RemPFCMBC", 
          "CIM_DataCenterEthernetPort.RemPFCCap" }]
   boolean RemPFCWilling;

      [Write ( false ), Description ( 
          "Indicates if the remote system is capable of bypassing "
          "MACsec processing when MACsec is disabled." ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxRemPFCMBC" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.RemPFCWilling", 
          "CIM_DataCenterEthernetPort.RemPFCCap" }]
   boolean RemPFCMBC;

      [Write ( false ), Description ( 
          "Indicates the number of traffic classes on the remote "
          "port that may simultaneously have PFC enabled." ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxRemPFCCap" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.RemPFCWilling", 
          "CIM_DataCenterEthernetPort.RemPFCMBC" }]
   uint8 RemPFCCap;

      [Write ( false ), Description ( 
          "Priority for which PFC is enabled / disabled on the remote port."
           ), 
       ArrayType ( "Indexed" ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxRemPFCEnablePriority" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.RemPFCEnableEnabled" }]
   uint8 RemPFCEnablePriority[];

      [Write ( false ), Description ( 
          "Indicates if PFC is enabled on the corresponding "
          "priority on the remote port." ), 
       ArrayType ( "Indexed" ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxRemPFCEnableEnabled" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.RemPFCEnablePriority" }]
   boolean RemPFCEnableEnabled[];

      [Write ( false ), Description ( 
          "Indicates the contents of the protocol object" ), 
       ValueMap { "1", "2", "3", "4", ".." }, 
       Values { "Ethertype", "Well Known Port number over TCP/SCTP", 
          "Well Known Port number over UDP/DCCP", 
          "Well Known Port number over TCP/SCTP/UDP/DCCP", 
          "DMTF Reserved" }, 
       ArrayType ( "Indexed" ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxRemApplicationPriorityAESelector" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.RemApplicationPriorityAEProtocol", 
          "CIM_DataCenterEthernetPort.RemApplicationPriorityAEPriority" }]
   uint16 RemApplicationPriorityAESelector[];

      [Write ( false ), Description ( 
          "The protocol indicator of the type indicated by "
          "RemApplicationPriorityAESelector." ), 
       ArrayType ( "Indexed" ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxRemApplicationPriorityAEProtocol" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.RemApplicationPriorityAESelector", 
          "CIM_DataCenterEthernetPort.RemApplicationPriorityAEPriority" }]
   uint16 RemApplicationPriorityAEProtocol[];

      [Write ( false ), Description ( 
          "The priority code point that should be used in frames "
          "transporting the protocol indicated by\n"
          "RemApplicationPriorityAESelector and\n"
          "RemApplicationPriorityAEProtocol properties." ), 
       ArrayType ( "Indexed" ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxRemApplicationPriorityAEPriority" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.RemApplicationPriorityAESelector", 
          "CIM_DataCenterEthernetPort.RemApplicationPriorityAEProtocol" }]
   uint8 RemApplicationPriorityAEPriority[];

      [Description ( 
          "Indicates support for the credit-based shaper Traffic "
          "Selection Algorithm." ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxAdminETSConCreditBasedShaperSupport" }]
   boolean AdminETSConCreditBasedShaperSupport;

      [Description ( 
          "Indicates the number of traffic classes supported on this port."
           ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxAdminETSConTrafficClassesSupported" }]
   uint8 AdminETSConTrafficClassesSupported;

      [Write, Description ( 
          "Indicates if the local system is willing to accept the "
          "ETS configuration recommended by the remote system." ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxAdminETSConWilling" }]
   boolean AdminETSConWilling;

      [Description ( 
          "Indicates the priorities that are assigned to traffic classes."
           ), 
       ArrayType ( "Indexed" ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxAdminETSConPriority" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.AdminETSConPriTrafficClass" }]
   uint8 AdminETSConPriority[];

      [Write, Description ( 
          "Indicates the traffic classes to which priorities are assigned."
           ), 
       ArrayType ( "Indexed" ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxAdminETSConPriTrafficClass" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.AdminETSConPriority" }]
   uint8 AdminETSConPriTrafficClass[];

      [Description ( 
          "Indicates the traffic classes to which bandwidth values "
          "indicated by the "
          "CIM_DataCenterEthernetPort.AdminETSConTrafficClassBandwidth "
          "apply." ), 
       ArrayType ( "Indexed" ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxAdminETSConTrafficClass" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.AdminETSConTrafficClassBandwidth" }]
   uint8 AdminETSConTrafficClass[];

      [Write, Description ( 
          "Indicates the % of link bandwidths assigned to traffic "
          "classes. The sum of % bandwidths in this array shall be "
          "100." ), 
       ArrayType ( "Indexed" ), 
       MinValue ( 0 ), 
       MaxValue ( 100 ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxAdminETSConTrafficClassBandwidth" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.AdminETSConTrafficClass" }, 
       PUnit ( "percent" )]
   uint8 AdminETSConTrafficClassBandwidth[];

      [Description ( 
          "Indicates the traffic classes that are assigned traffic "
          "selection algorithms." ), 
       ArrayType ( "Indexed" ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxAdminETSConTSATrafficClass" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.AdminETSConTrafficSelectionAlgorithm" }]
   uint8 AdminETSConTSATrafficClass[];

      [Write, Description ( 
          "Indicates the Traffic Selection Algorithms to which "
          "traffic classes are assigned.\"" ), 
       ValueMap { "0", "1", "2", "..", "255" }, 
       Values { "Strict Priority", "Credit-based shaper", 
          "Enhanced transmission selection", "DMTF Reserved", 
          "Vendor Reserved" }, 
       ArrayType ( "Indexed" ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxAdminETSConTrafficSelectionAlgorithm" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.AdminETSConTSATrafficClass" }]
   uint8 AdminETSConTrafficSelectionAlgorithm[];

      [Description ( 
          "Indicates the traffic classes to which bandwidths apply. "
          "Used for recommendation TLV." ), 
       ArrayType ( "Indexed" ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxAdminETSRecoTrafficClass" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.AdminETSRecoTrafficClassBandwidth" }]
   uint8 AdminETSRecoTrafficClass[];

      [Write, Description ( 
          "Indicates the bandwidths assigned to traffic classes for "
          "recommendation TLV." ), 
       ArrayType ( "Indexed" ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxAdminETSRecoTrafficClassBandwidth" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.AdminETSRecoTrafficClass" }, 
       PUnit ( "bit / second" )]
   uint64 AdminETSRecoTrafficClassBandwidth[];

      [Description ( 
          "Indicates the traffic classes that are assigned to "
          "traffic selection algorithms. Used for Recommendation "
          "TLV." ), 
       ArrayType ( "Indexed" ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxETSRecoTSATrafficClass" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.AdminETSRecoTrafficSelectionAlgorithm" }]
   uint8 AdminETSRecoTSATrafficClass[];

      [Write, Description ( 
          "Indicates the Traffic Selection Algorithms to which "
          "traffic classes are to be assigned. Used for "
          "Recommendation TLV." ), 
       ValueMap { "0", "1", "2", "..", "255" }, 
       Values { "Strict Priority", "Credit-based shaper", 
          "Enhanced transmission selection", "DMTF Reserved", 
          "Vendor Reserved" }, 
       ArrayType ( "Indexed" ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxAdminETSRecoTrafficSelectionAlgorithm" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.AdminETSRecoTSATrafficClass" }]
   uint8 AdminETSRecoTrafficSelectionAlgorithm[];

      [Write, Description ( 
          "Indicates if the local system is willing to accept the "
          "PFC configuration of the remote system on this port." ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxAdminPFCWilling" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.AdminPFCMBC", 
          "CIM_DataCenterEthernetPort.AdminPFCCap" }]
   boolean AdminPFCWilling;

      [Description ( 
          "Indicates if the local system is capable of bypassing "
          "MACsec processing when MACsec is disabled." ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxAdminPFCMBC" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.AdminPFCWilling", 
          "CIM_DataCenterEthernetPort.AdminPFCCap" }]
   boolean AdminPFCMBC;

      [Description ( 
          "Indicates the number of traffic classes on the local "
          "port that may simultaneously have PFC enabled." ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxAdminPFCCap" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.AdminPFCWilling", 
          "CIM_DataCenterEthernetPort.AdminPFCMBC" }]
   uint8 AdminPFCCap;

      [Description ( "Prioity for which PFC is enabled / disabled" ), 
       ArrayType ( "Indexed" ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxAdminPFCEnablePriority" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.AdminPFCEnableEnabled" }]
   uint8 AdminPFCEnablePriority[];

      [Write, Description ( 
          "Indicates if PFC is enabled on the corresponding priority."
           ), 
       ArrayType ( "Indexed" ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxAdminPFCEnableEnabled" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.AdminPFCEnablePriority" }]
   boolean AdminPFCEnableEnabled[];

      [Description ( "Indicates the contents of the protocol object" ), 
       ValueMap { "1", "2", "3", "4", ".." }, 
       Values { "Ethertype", "Well Known Port number over TCP/SCTP", 
          "Well Known Port number over UDP/DCCP", 
          "Well Known Port number over TCP/SCTP/UDP/DCCP", 
          "DMTF Reserved" }, 
       ArrayType ( "Indexed" ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxAdminApplicationPriorityAESelector" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.AdminApplicationPriorityAEProtocol", 
          "CIM_DataCenterEthernetPort.AdminApplicationPriorityAEPriority" }]
   uint16 AdminApplicationPriorityAESelector[];

      [Description ( 
          "The protocol indicator of the type indicated by "
          "AdminApplicationPriorityAESelector." ), 
       ArrayType ( "Indexed" ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxAdminApplicationPriorityAEProtocol" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.AdminApplicationPriorityAESelector", 
          "CIM_DataCenterEthernetPort.AdminApplicationPriorityAEPriority" }]
   uint16 AdminApplicationPriorityAEProtocol[];

      [Write, Description ( 
          "The priority code point that should be used in frames "
          "transporting the protocol indicated by\n"
          "AdminApplicationPriorityAESelector and\n"
          "AdminApplicationPriorityAEProtocol properties." ), 
       ArrayType ( "Indexed" ), 
       MappingStrings { 
          "IEEE.MIB|LLDP-EXT-DOT1-V2-MIB.lldpXdot1dcbxAdminApplicationPriorityAEPriority" }, 
       ModelCorrespondence { 
          "CIM_DataCenterEthernetPort.AdminApplicationPriorityAESelector", 
          "CIM_DataCenterEthernetPort.AdminApplicationPriorityAEProtocol" }]
   uint8 AdminApplicationPriorityAEPriority[];


};
