// Copyright (c) 2012 DMTF.  All rights reserved.
   [Association, Version ( "2.31.0" ), 
    UMLPackagePath ( "CIM::Device::StorageServices" ), 
    Description ( 
       "AssociatedTierPolicy defines the storage tiering policy "
       "associated to a given storage tier." )]
class CIM_AssociatedTierPolicy : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Description ( "Defines the policy rule." )]
   CIM_PolicyRule REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( "Defines the storage tier." )]
   CIM_StorageTier REF Dependent;

      [Description ( 
          "The maximum percentage of the capacity of the element "
          "that can be allocated from the storage tier. Must be an "
          "integer value between 0 and 100." ), 
       Units ( "Percentage" ), 
       MinValue ( 0 ), 
       MaxValue ( 100 ), 
       PUnit ( "percent" )]
   uint16 MaxPercentAllocated;


};
