// Copyright (c) 2011 DMTF.  All rights reserved.
   [Experimental, Version ( "2.29.0" ), 
    UMLPackagePath ( "CIM::Device::Views" ), 
    Description ( 
       "The CIM_MappingProtocolControllerView instance is a view that "
       "is derived from CIM_LogicalPort, CIM_ProtocolController, "
       "CIM_ProtocolEndpoint, CIM_AuthorizedPrivilege and CIM_StorageHardwareID.\n"
       "CIM_ElementView may associate "
       "CIM_MappingProtocolControllerView to its underlying elements "
       "(regardless of whether or not they are instantiated)." )]
class CIM_MappingProtocolControllerView : CIM_LogicalDeviceView {

      [Key, Description ( 
          "The SystemCreationClassName for the ProtocolController "
          "as reported in the underlying ProtocolController "
          "instance." ), 
       ModelCorrespondence { 
          "CIM_ProtocolController.SystemCreationClassName" }]
   string PCSystemCreationClassName;

      [Key, Description ( 
          "The SystemName for the ProtocolController as reported in "
          "the underlying ProtocolController instance." ), 
       ModelCorrespondence { "CIM_ProtocolController.SystemName" }]
   string PCSystemName;

      [Key, Description ( 
          "The CreationClassName for the ProtocolController as "
          "reported in the underlying ProtocolController instance." ), 
       ModelCorrespondence { 
          "CIM_ProtocolController.CreationClassName" }]
   string PCCreationClassName;

      [Key, Description ( 
          "An opaque identifier of the underlying ProtocolController."
           ), 
       ModelCorrespondence { "CIM_ProtocolController.DeviceID" }]
   string PCDeviceID;

      [Key, Description ( 
          "The InstanceID of the StorageHardwareID as reported in "
          "its underlying StorageHardwareID." ), 
       ModelCorrespondence { "CIM_StorageHardwareID.InstanceID" }]
   string SHIDInstanceID;

      [Description ( 
          "The StorageID of the StorageHardwareID as reported in "
          "its underlying StorageHardwareID." ), 
       ModelCorrespondence { "CIM_StorageHardwareID.StorageID" }]
   string SHIDStorageID;

      [Description ( 
          "The IDType value supported by the StorageHardwareID as "
          "reported in its underlying StorageHardwareID." ), 
       ModelCorrespondence { "CIM_StorageHardwareID.IDType" }]
   uint16 SHIDIDType;

      [Key, Description ( 
          "The SystemCreationClassName for the ProtocolEndpoint as "
          "reported in the underlying ProtocolEndpoint instance." ), 
       ModelCorrespondence { 
          "CIM_ProtocolEndpoint.SystemCreationClassName" }]
   string PEPSystemCreationClassName;

      [Key, Description ( 
          "The CreationClassName for the ProtocolEndpoint as "
          "reported in the underlying ProtocolEndpoint instance." ), 
       ModelCorrespondence { "CIM_ProtocolEndpoint.CreationClassName" }]
   string PEPCreationClassName;

      [Key, Description ( 
          "The SystemName for the ProtocolEndpoint as reported in "
          "the underlying ProtocolEndpoint instance." ), 
       ModelCorrespondence { "CIM_ProtocolEndpoint.SystemName" }]
   string PEPSystemName;

      [Key, Description ( 
          "The Name for the ProtocolEndpoint as reported in the "
          "underlying ProtocolEndpoint instance." ), 
       ModelCorrespondence { "CIM_ProtocolEndpoint.Name" }]
   string PEPName;

      [Description ( 
          "The ProtocolIFType for the ProtocolEndpoint as reported "
          "in the underlying ProtocolEndpoint instance." ), 
       ModelCorrespondence { "CIM_ProtocolEndpoint.ProtocolIFType" }]
   uint16 PEPProtocolIFType;

      [Description ( 
          "The OtherTypeDescription for the ProtocolEndpoint as "
          "reported in the underlying ProtocolEndpoint instance." ), 
       ModelCorrespondence { 
          "CIM_ProtocolEndpoint.OtherTypeDescription" }]
   string PEPOtherTypeDescription;

      [Description ( 
          "The Role for the ProtocolEndpoint as reported in the "
          "underlying ProtocolEndpoint instance." )]
   uint16 PEPRole;

      [Description ( 
          "The ConnectionType for the ProtocolEndpoint as reported "
          "in the underlying ProtocolEndpoint instance." )]
   uint16 PEPConnectionType;

      [Description ( 
          "The InstanceID of the AuthorizedPrivilege as reported in "
          "its underlying AuthorizedPrivelege." ), 
       ModelCorrespondence { "CIM_AuthorizedPrivilege.InstanceID" }]
   string APInstanceID;

      [Description ( 
          "The PrivilegeGranted property of the AuthorizedPrivilege "
          "as reported in its underlying AuthorizedPrivelege." ), 
       ModelCorrespondence { 
          "CIM_AuthorizedPrivilege.PrivilegeGranted" }]
   boolean APPrivilegeGranted = true;

      [Description ( 
          "The Activities property of the AuthorizedPrivilege as "
          "reported in its underlying AuthorizedPrivelege." ), 
       ModelCorrespondence { "CIM_AuthorizedPrivilege.Activities" }]
   uint16 APActivities[];

      [Description ( 
          "The ElementName for the underlying AuthorizedPrivilege." ), 
       ModelCorrespondence { "CIM_AuthorizedPrivilege.ElementName" }]
   string APElementName;

      [Description ( 
          "The SystemCreationClassName for the LogicalPort as "
          "reported in the underlying LogicalPort instance." ), 
       ModelCorrespondence { 
          "CIM_LogicalPort.SystemCreationClassName" }]
   string LPSystemCreationClassName;

      [Description ( 
          "The SystemName for the LogicalPort as reported in the "
          "underlying LogicalPort instance." ), 
       ModelCorrespondence { "CIM_LogicalPort.SystemName" }]
   string LPSystemName;

      [Description ( 
          "The CreationClassName for the LogicalPort as reported in "
          "the underlying LogicalPort instance." ), 
       ModelCorrespondence { "CIM_LogicalPort.CreationClassName" }]
   string LPCreationClassName;

      [Description ( 
          "An opaque identifier of the underlying LogicalPort." ), 
       ModelCorrespondence { "CIM_LogicalPort.DeviceID" }]
   string LPDeviceID;

      [Description ( 
          "The OperationalStatus for the LogicalPort as reported in "
          "the underlying LogicalPort instance." ), 
       ModelCorrespondence { "CIM_LogicalPort.OperationalStatus" }]
   uint16 LPOperationalStatus[];

      [Description ( 
          "The UsageRestriction for the LogicalPort as reported in "
          "the underlying LogicalPort instance." ), 
       ModelCorrespondence { "CIM_LogicalPort.UsageRestriction" }]
   uint16 LPUsageRestriction;

      [Description ( 
          "The PortType for the LogicalPort as reported in the "
          "underlying LogicalPort instance." ), 
       ModelCorrespondence { "CIM_LogicalPort.PortType" }]
   uint16 LPPortType;


};
