// Copyright (c) 2011 DMTF.  All rights reserved.
   [Experimental, Version ( "2.29.0" ), 
    UMLPackagePath ( "CIM::Device::Views" ), 
    Description ( 
       "The CIM_DiskDriveView instance is a view that is derived from "
       "CIM_StorageExtent, CIM_MediaPresent, CIM_DiskDrive, "
       "CIM_Realizes, CIM_PhysicalPackage, CIM_ElementSoftwareIdentity "
       "and CIM_SoftwareIdentity." )]
class CIM_DiskDriveView : CIM_LogicalDeviceView {

      [Description ( 
          "The SystemCreationClassName for the StorageExtent of the "
          "Disk Drive as reported in the underlying primordial "
          "StorageExtent instance for the Disk Drive." ), 
       ModelCorrespondence { 
          "CIM_StorageExtent.SystemCreationClassName" }]
   string SESystemCreationClassName;

      [Description ( 
          "The SystemName for the StorageExtent of the Disk Drive "
          "as reported in the underlying primordial StorageExtent "
          "instance for the Disk Drive." ), 
       ModelCorrespondence { "CIM_StorageExtent.SystemName" }]
   string SESystemName;

      [Description ( 
          "The CreationClassName for the StorageExtent of the Disk "
          "Drive as reported in the underlying primordial "
          "StorageExtent instance for the Disk Drive." ), 
       ModelCorrespondence { "CIM_StorageExtent.CreationClassName" }]
   string SECreationClassName;

      [Description ( 
          "The DeviceID for the StorageExtent of the Disk Drive as "
          "reported in the underlying primordial StorageExtent "
          "instance for the Disk Drive." ), 
       ModelCorrespondence { "CIM_StorageExtent.DeviceID" }]
   string SEDeviceID;

      [Description ( 
          "The BlockSize for the StorageExtent of the Disk Drive as "
          "reported in the underlying primordial StorageExtent "
          "instance for the Disk Drive." ), 
       ModelCorrespondence { "CIM_StorageExtent.BlockSize" }]
   uint64 SEBlockSize;

      [Description ( 
          "The NumberOfBlocks for the StorageExtent of the Disk "
          "Drive as reported in the underlying primordial "
          "StorageExtent instance for the Disk Drive." ), 
       ModelCorrespondence { "CIM_StorageExtent.NumberOfBlocks" }]
   uint64 SENumberOfBlocks;

      [Description ( 
          "The ConsumableBlocks for the StorageExtent of the Disk "
          "Drive as reported in the underlying primordial "
          "StorageExtent instance for the Disk Drive." ), 
       ModelCorrespondence { "CIM_StorageExtent.ConsumableBlocks" }]
   uint64 SEConsumableBlocks;

      [Description ( 
          "The ExtentStatus for the StorageExtent of the Disk Drive "
          "as reported in the underlying primordial StorageExtent "
          "instance for the Disk Drive." ), 
       ModelCorrespondence { "CIM_StorageExtent.ExtentStatus" }]
   uint16 SEExtentStatus[];

      [Description ( 
          "The OperationalStatus for the StorageExtent of the Disk "
          "Drive as reported in the underlying primordial "
          "StorageExtent instance for the Disk Drive." ), 
       ModelCorrespondence { "CIM_StorageExtent.OperationalStatus" }]
   uint16 SEOperationalStatus[];

      [Key, Description ( 
          "The SystemCreationClassName for the Disk Drive as "
          "reported in the underlying DiskDrive instance." ), 
       ModelCorrespondence { "CIM_DiskDrive.SystemCreationClassName" }]
   string DDSystemCreationClassName;

      [Key, Description ( 
          "The SystemName for the Disk Drive as reported in the "
          "underlying DiskDrive instance." ), 
       ModelCorrespondence { "CIM_DiskDrive.SystemName" }]
   string DDSystemName;

      [Key, Description ( 
          "The CreationClassName for the Disk Drive as reported in "
          "the underlying DiskDrive instance." ), 
       ModelCorrespondence { "CIM_DiskDrive.CreationClassName" }]
   string DDCreationClassName;

      [Key, Description ( 
          "The DeviceID for the Disk Drive as reported in the "
          "underlying DiskDrive instance." ), 
       ModelCorrespondence { "CIM_DiskDrive.DeviceID" }]
   string DDDeviceID;

      [Description ( 
          "The Name for the Disk Drive as reported in the "
          "underlying DiskDrive instance." ), 
       ModelCorrespondence { "CIM_DiskDrive.Name" }]
   string DDName;

      [Description ( 
          "The OperationalStatus for the Disk Drive as reported in "
          "the underlying DiskDrive instance." ), 
       ModelCorrespondence { "CIM_DiskDrive.OperationalStatus" }]
   uint16 DDOperationalStatus[];

      [Description ( 
          "The CreationClassName for the PhysicalPackage of the "
          "Disk Drive as reported in the underlying PhysicalPackage "
          "instance for the Disk Drive." ), 
       ModelCorrespondence { "CIM_PhysicalPackage.CreationClassName" }]
   string PPCreationClassName;

      [Description ( 
          "The Tag for the PhysicalPackage of the Disk Drive as "
          "reported in the underlying PhysicalPackage instance for "
          "the Disk Drive." ), 
       ModelCorrespondence { "CIM_PhysicalPackage.Tag" }]
   string PPTag;

      [Description ( 
          "The Manufacturer for the PhysicalPackage of the Disk "
          "Drive as reported in the underlying PhysicalPackage "
          "instance for the Disk Drive." ), 
       ModelCorrespondence { "CIM_PhysicalPackage.Manufacturer" }]
   string PPManufacturer;

      [Description ( 
          "The Model for the PhysicalPackage of the Disk Drive as "
          "reported in the underlying PhysicalPackage instance for "
          "the Disk Drive." ), 
       ModelCorrespondence { "CIM_PhysicalPackage.Model" }]
   string PPModel;

      [Description ( 
          "The InstanceID for the SoftwareIdentity of the Disk "
          "Drive as reported in the underlying SoftwareIdentity "
          "instance for the Disk Drive." ), 
       ModelCorrespondence { "CIM_SoftwareIdentity.InstanceID" }]
   string SIInstanceID;

      [Description ( 
          "The VersionString for the SoftwareIdentity of the Disk "
          "Drive as reported in the underlying SoftwareIdentity "
          "instance for the Disk Drive." ), 
       ModelCorrespondence { "CIM_SoftwareIdentity.VersionString" }]
   string SIVersionString;

      [Description ( 
          "The LocationIndicator for the Disk Drive as reported in "
          "the underlying DiskDrive instance." ), 
       ModelCorrespondence { "CIM_DiskDrive.LocationIndicator" }]
   uint16 DDLocationIndicator;

      [Description ( 
          "The SerialNumber for the PhysicalPackage of the Disk "
          "Drive as reported in the underlying PhysicalPackage "
          "instance for the Disk Drive." ), 
       ModelCorrespondence { "CIM_PhysicalPackage.SerialNumber" }]
   string PPSerialNumber;

      [Description ( 
          "The PartNumber for the PhysicalPackage of the Disk Drive "
          "as reported in the underlying PhysicalPackage instance "
          "for the Disk Drive." ), 
       ModelCorrespondence { "CIM_PhysicalPackage.PartNumber" }]
   string PPPartNumber;

      [Description ( 
          "The Manufacturer for the SoftwareIdentity of the Disk "
          "Drive as reported in the underlying SoftwareIdentity "
          "instance for the Disk Drive." ), 
       ModelCorrespondence { "CIM_SoftwareIdentity.Manufacturer" }]
   string SIManufacturer;

      [Description ( 
          "The BuildNumber for the SoftwareIdentity of the Disk "
          "Drive as reported in the underlying SoftwareIdentity "
          "instance for the Disk Drive." ), 
       ModelCorrespondence { "CIM_SoftwareIdentity.BuildNumber" }]
   uint16 SIBuildNumber;

      [Description ( 
          "The MajorVersion for the SoftwareIdentity of the Disk "
          "Drive as reported in the underlying SoftwareIdentity "
          "instance for the Disk Drive." ), 
       ModelCorrespondence { "CIM_SoftwareIdentity.MajorVersion" }]
   uint16 SIMajorVersion;

      [Description ( 
          "The RevisionNumber for the SoftwareIdentity of the Disk "
          "Drive as reported in the underlying SoftwareIdentity "
          "instance for the Disk Drive." ), 
       ModelCorrespondence { "CIM_SoftwareIdentity.RevisionNumber" }]
   uint16 SIRevisionNumber;

      [Description ( 
          "The MinorVersion for the SoftwareIdentity of the Disk "
          "Drive as reported in the underlying SoftwareIdentity "
          "instance for the Disk Drive." ), 
       ModelCorrespondence { "CIM_SoftwareIdentity.MinorVersion" }]
   uint16 SIMinorVersion;


};
