// Copyright (c) 2009 DMTF.  All rights reserved.
   [Association, Version ( "2.23.0" ), 
    UMLPackagePath ( "CIM::Device::StorageServices" ), 
    Description ( 
       "CIM_AssociatedMaskingGroup is the association that assembles "
       "the ProtocolControllers view and the participating "
       "MaskingGroups." )]
class CIM_AssociatedMaskingGroup : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Description ( "The ProtocolController." )]
   CIM_ProtocolController REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( 
          "The MaskingGroup \'behind\' the ProtocolController." )]
   CIM_MaskingGroup REF Dependent;


};
