// Copyright (c) 2013 DMTF.  All rights reserved.
   [Association, Experimental, Version ( "2.38.0" ), 
    UMLPackagePath ( "CIM::Device::StorageServices" ), 
    Description ( 
       "CIM_ResourcePoolExtentDependency is used to show dependency "
       "between a storage extent and resource pools." )]
class CIM_ResourcePoolExtentDependency : CIM_Dependency {

      [Key, Override ( "Antecedent" ), 
       Description ( 
          "Antecedent represents the independent storage extent in "
          "this association." )]
   CIM_StorageExtent REF Antecedent;

      [Key, Override ( "Dependent" ), 
       Description ( 
          "Dependent represents the resource pool that is dependent "
          "on the disk drive." )]
   CIM_LogicalElement REF Dependent;


};
