// Copyright (c) 2011 DMTF.  All rights reserved.
   [Experimental, Version ( "2.29.0" ), 
    UMLPackagePath ( "CIM::Device::FC" ), 
    Description ( 
       "The CIM_FCPortResourceUsage class contains data representing "
       "current SRR & Abort count, MIN, MAX thresholds for SRR & Abort "
       "counters" )]
class CIM_FCPortResourceUsage : CIM_FCPortStatistics {

      [Description ( 
          "The number of SRRs that have occured (Sequence "
          "Retransmission Requests) for this FCPort." ), 
       Read]
   uint64 SRRCount;

      [Description ( 
          "The number of Aborts that have occured for this FCPort." ), 
       Read]
   uint64 AbortCount;

      [Description ( 
          "The threshold for a warning notification on the number "
          "of SRRs that have occurred." ), 
       Read]
   uint64 MinSRRCount;

      [Description ( 
          "The threshold for a error notification on the number of "
          "SRRs that have occurred." ), 
       Read]
   uint64 MaxSRRCount;

      [Description ( 
          "The threshold for a warning notification on the number "
          "of aborts that have occurred." ), 
       Read]
   uint64 MinAbortCount;

      [Description ( 
          "The threshold for a error notification on the number of "
          "aborts that have occurred." ), 
       Read]
   uint64 MaxAbortCount;


};
