// Copyright (c) 2008 DMTF.  All rights reserved.
   [Experimental, Version ( "2.21.0" ), 
    UMLPackagePath ( "CIM::Device" ), 
    Description ( 
       "FingerprintReader is the logical representation of the "
       "Fingerprint Reader biometric Device. It is composed of "
       "biometric information detection sensors." )]
class CIM_FingerprintReader : CIM_LogicalDevice {

      [Description ( 
          "An array of integer enumeration that indicates the types "
          "of Sensors. Contact sensors are the traditional postage "
          "stamp-shaped fingerprint sensors that require pressing "
          "down flat and hold to detect the fingerprint image. "
          "Slide sensors require sliding or swiping the finger "
          "across the reader to get the fingerprint image. Optical "
          "sensors scan the fingerprint like a copier. Electrical "
          "field sensors measure variations in the conductivity of "
          "layers of skin under the fingerprints. Capacitive "
          "sensors measure the difference in electrical capacity "
          "between the fingerprint ridges and the air between the "
          "ridges. Ultrasonic sensors sense the difference in "
          "acoustic conductivity between the ridges and the air "
          "between the ridges. Temperature sensors measure the "
          "difference in the temperature between the ridges and the "
          "air between the ridges. Pressure sensors detect the "
          "pressure of the ridges pushing against the glass of the "
          "sensor. A fingerprint reader device can be a "
          "combinations of these biometric sensors." ), 
       ValueMap { "0", "3", "4", "5", "6", "7", "8", "9", "10", 
          "..", "32768..65535" }, 
       Values { "Unknown", "Contact", "Slide", "Optical", 
          "Electrical Field", "Capacitive", "Ultrasonic", 
          "Temperature", "Pressure", "DMTF Reserved", 
          "Vendor Specified" }]
   uint16 SensorTypes[];


};
