// Copyright (c) 2009 DMTF.  All rights reserved.
   [Experimental, Version ( "2.23.0" ), 
    UMLPackagePath ( "CIM::Device::StorageServices" ), 
    Description ( "Initiator Port Masking Group (StorageHardwareIDs)." )]
class CIM_InitiatorMaskingGroup : CIM_MaskingGroup {

      [Override ( "ElementName" ), 
       Write]
   string ElementName;

      [Write, Description ( 
          "Indicates the device numbers for a volume visible to the "
          "same initiator though different paths must be the same." )]
   boolean ConsistentLogicalUnitNumber = true;


};
