// Copyright (c) 2009 DMTF.  All rights reserved.
   [Experimental, Version ( "2.24.0" ), 
    UMLPackagePath ( "CIM::Device::StorageExtents" ), 
    Description ( 
       "GPT is a newer partitioning style that supports volumes larger "
       "than the 2 terabyte max of other partition styles. GPT in "
       "general is associated with PC X86 architectures, but GPT "
       "partitions are OS and platform independent. GPT uses 16 byte "
       "GUIDs (Globally Unique IDs) for certain properties. The "
       "DeviceId property inherited from LogicalDevice should be a "
       "GUID for GPTDiskPartitions; this string property should be "
       "formatted as a 32 character string with two text bytes "
       "representing each binary byte. GPT specifications call for a "
       "Protective MBR table (PMBR) in block 0 followed by an GPT "
       "(GUID Partition Table). The MBR must describe a single active "
       "partition - the GPT Partition that occupies the rest of the "
       "disk. The user only sees the GPT style partitions in this "
       "second MBR partition. This could be modelled as two tiers, but "
       "since the specification requires this precise behavior with no "
       "management at the MBR level, only the GPT style partitions are "
       "exposed through the CIM model." )]
class CIM_GPTDiskPartition : CIM_GenericDiskPartition {

      [Description ( 
          "The PartitionType as defined in the GPT specs and "
          "platform specific documentation - GUID format. This "
          "string property MUST be formatted with two text bytes "
          "representing each binary byte." )]
   string PartitionType;


};
