// Copyright (c) 2005 DMTF.  All rights reserved.
   [Association, Aggregation, Composition, Version ( "2.7.0" ), 
    UMLPackagePath ( "CIM::System::SystemResources" ), 
    Description ( 
       "An association between a ComputerSystem and the System "
       "Resources available on it." )]
class CIM_ComputerSystemResource : CIM_ResourceOfSystem {

      [Aggregate, Override ( "GroupComponent" ), 
       Min ( 1 ), 
       Max ( 1 ), 
       Description ( "The ComputerSystem." )]
   CIM_ComputerSystem REF GroupComponent;

      [Override ( "PartComponent" ), 
       Description ( "A SystemResource of the ComputerSystem." )]
   CIM_SystemResource REF PartComponent;


};
