// Copyright (c) 2011 DMTF.  All rights reserved.
   [Association, Experimental, Abstract, Version ( "2.28.0" ), 
    UMLPackagePath ( "CIM::Core::Resource" ), 
    Description ( 
       "AbstractElementAllocatedFromPool associates an instance of "
       "CIM_ManagedElement representing an allocated Resource with the "
       "CIM_ManagedElement from which it was allocated" )]
class CIM_AbstractElementAllocatedFromPool : CIM_Dependency {

      [Key, Override ( "Antecedent" ), 
       Description ( 
          "A reference to the ManagedElement that represents a pool "
          "from which an element is allocated." )]
   CIM_ManagedElement REF Antecedent;

      [Key, Override ( "Dependent" ), 
       Description ( 
          "A reference to the element that is alloocated from the "
          "antecedent pool." )]
   CIM_ManagedElement REF Dependent;


};
