// Copyright (c) 2013 DMTF.  All rights reserved.
   [Association, Experimental, Version ( "2.37.0" ), 
    UMLPackagePath ( "CIM::Core" ), 
    Description ( "ComputerSystem Setting Data" )]
class CIM_ComputerSystemElementSettingData : CIM_ElementSettingData {

      [Key, Override ( "ManagedElement" ), 
       Description ( "The ComputerSystem." )]
   CIM_ComputerSystem REF ManagedElement;


};
