// Copyright (c) 2013 DMTF.  All rights reserved.
   [Association, Experimental, Composition, Version ( "2.38.0" ), 
    ClassConstraint { 
       "inv: Service.LoSID <> null and Option.SoID <> null" }, 
    UMLPackagePath ( "CIM::Core::Settings" ), 
    Description ( 
       "ServiceOption is a relationship between a Service instance "
       "that represents an ITIL service and a SettingData instance "
       "that represents an ITIL service option." )]
class CIM_ServiceOption {

      [Key, Aggregate, Max ( 1 ), 
       Description ( "The service." )]
   CIM_Service REF Service;

      [Key, Description ( 
          "The SettingData object that is associated with the element."
           )]
   CIM_SettingData REF Option;

      [Description ( 
          "An enumerated integer that indicates that the referenced "
          "setting is a default setting for the element or that "
          "this information is unknown." ), 
       ValueMap { "0", "1", "2" }, 
       Values { "Unknown", "Is Default", "Is Not Default" }]
   uint16 IsDefault;


};
