// Copyright (c) 2011 DMTF.  All rights reserved.
   [Association, Version ( "2.28.0" ), 
    UMLPackagePath ( "CIM::Core::Resource" ), 
    Description ( 
       "ElementAllocatedFromPool associates an instance of "
       "CIM_LogicalElement representing an allocated Resource with the "
       "CIM_ResourcePool from which it was allocated." )]
class CIM_ElementAllocatedFromPool : CIM_AbstractElementAllocatedFromPool {

      [Override ( "Antecedent" ), 
       Description ( "The resource pool." )]
   CIM_ResourcePool REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( "The allocated resource." )]
   CIM_LogicalElement REF Dependent;


};
