// Copyright (c) 2013 DMTF.  All rights reserved.
   [Association, Version ( "2.40.0" ), 
    UMLPackagePath ( "CIM::Core::Settings" ), 
    Description ( 
       "CollectionSetting represents the association between a "
       "CollectionOfMSEs class and the Setting classes that are "
       "defined for it." )]
class CIM_CollectionSetting {

      [Key, Description ( "The Collection." )]
   CIM_Collection REF Collection;

      [Key, Description ( 
          "The Setting object that is associated with the Collection."
           )]
   CIM_Setting REF Setting;


};
