// Copyright (c) 2013 DMTF.  All rights reserved.
   [Association, Experimental, Version ( "2.37.0" ), 
    UMLPackagePath ( "CIM::Core" ), 
    Description ( 
       "The depdencies for the StorageHardwareIDManagementService." )]
class CIM_StorageHardwareIDManagementServiceDependency : CIM_ConcreteDependency {

      [Key, Override ( "Antecedent" ), 
       Description ( "The StorageHardwareIDManagementService." )]
   CIM_StorageHardwareIDManagementService REF Antecedent;


};
