// Copyright (c) 2013 DMTF.  All rights reserved.
   [Abstract, Version ( "2.40.0" ), 
    UMLPackagePath ( "CIM::Core::CoreElements" ), 
    Description ( 
       "CIM_AllocatedLogicalElement is the base class that models "
       "things that are allocated. Allocated things have an allocation "
       "state." )]
class CIM_AllocatedLogicalElement : CIM_EnabledLogicalElement {

      [Experimental, Description ( 
          "Allocation state of the managed element." ), 
       EmbeddedInstance ( "CIM_SettingData" )]
   string AllocationState;


};
