// Copyright (c) 2008 DMTF.  All rights reserved.
   [Experimental, Version ( "2.20.0" ), 
    UMLPackagePath ( "CIM::Core::Statistics" ), 
    Description ( 
       "This class defines the monitoring, availability, and traffic "
       "ImagingStatisticalData associated with an imaging system "
       "(e.g., ComputerSystem), imaging service (e.g., PrintService), "
       "imaging device (e.g., Printer), imaging job (e.g., PrintJob), "
       "or any other imaging element. \n"
       "See: Section 4 Overview in PWG Counter MIB v2 (PWG 5106.3)." )]
class CIM_ImagingMonitorStatisticalData : CIM_ImagingStatisticalData {

      [Description ( 
          "Total configuration changes that have occurred on this "
          "managed element (i.e., changes to description, "
          "capabilities, or settings but NOT changes to state, "
          "alerts, counters, etc." ), 
       MappingStrings { 
          "MIB.PWG|PWG-IMAGING-COUNTER-MIB.icMonitorConfigChanges" }]
   uint32 ConfigChanges;

      [Description ( 
          "Total alerts that have occurred on this managed element." ), 
       MappingStrings { 
          "MIB.PWG|PWG-IMAGING-COUNTER-MIB.icMonitorTotalAlerts" }, 
       ModelCorrespondence { "CIM_Printer.AllAlerts" }]
   uint32 TotalAlerts;

      [Description ( 
          "Critical alerts that have occurred on this managed element."
           ), 
       MappingStrings { 
          "MIB.PWG|PWG-IMAGING-COUNTER-MIB.icMonitorCriticalAlerts" }, 
       ModelCorrespondence { "CIM_Printer.CriticalAlerts" }]
   uint32 CriticalAlerts;

      [Description ( 
          "Total jobs that have been aborted (by the system "
          "software) on this managed element." ), 
       MappingStrings { 
          "MIB.PWG|PWG-IMAGING-COUNTER-MIB.icMonitorAbortedJobs" }]
   uint32 AbortedJobs;

      [Description ( 
          "Total jobs that have been canceled (by an authorized "
          "user) on this managed element." ), 
       MappingStrings { 
          "MIB.PWG|PWG-IMAGING-COUNTER-MIB.icMonitorCanceledJobs" }]
   uint32 CanceledJobs;

      [Description ( 
          "Total jobs that have been completed (successfully or "
          "with warnings/errors) on this managed element." ), 
       MappingStrings { 
          "MIB.PWG|PWG-IMAGING-COUNTER-MIB.icMonitorCompletedJobs" }]
   uint32 CompletedJobs;

      [Description ( 
          "Total jobs that have been completed (successfully or "
          "with warnings and errors) and for which any finishing "
          "process was performed on this managed element." ), 
       MappingStrings { 
          "MIB.PWG|PWG-IMAGING-COUNTER-MIB.icMonitorCompletedFinisherJobs" }]
   uint32 CompletedFinisherJobs;

      [Description ( 
          "Total times that data stored by this managed element to "
          "local memory caused a memory allocation failure." ), 
       MappingStrings { 
          "MIB.PWG|PWG-IMAGING-COUNTER-MIB.icMonitorMemoryAllocErrors" }]
   uint32 MemoryAllocErrors;

      [Description ( 
          "Total times that data stored by this managed element to "
          "local memory exceeded an implementation-defined or "
          "administratively configured memory allocation threshold." ), 
       MappingStrings { 
          "MIB.PWG|PWG-IMAGING-COUNTER-MIB.icMonitorMemoryAllocWarnings" }]
   uint32 MemoryAllocWarnings;

      [Description ( 
          "Total times that data stored by this managed element to "
          "a local or remote file system caused a storage "
          "allocation failure." ), 
       MappingStrings { 
          "MIB.PWG|PWG-IMAGING-COUNTER-MIB.icMonitorStorageAllocErrors" }]
   uint32 StorageAllocErrors;

      [Description ( 
          "Total times that data stored by this managed element to "
          "a local or remote file system exceeded an "
          "implementation-defined or administratively configured "
          "storage allocation threshold." ), 
       MappingStrings { 
          "MIB.PWG|PWG-IMAGING-COUNTER-MIB.icMonitorStorageAllocWarnings" }]
   uint32 StorageAllocWarnings;

      [Description ( 
          "Total amount of data stored by this managed element to a "
          "local file system." ), 
       MappingStrings { 
          "MIB.PWG|PWG-IMAGING-COUNTER-MIB.icMonitorLocalStorageKOctets" }, 
       Punit ( "byte * 10^3" )]
   uint32 LocalStorageKOctets;

      [Description ( 
          "Total amount of data stored by this managed element to a "
          "remote file system." ), 
       MappingStrings { 
          "MIB.PWG|PWG-IMAGING-COUNTER-MIB.icMonitorRemoteStorageKOctets" }, 
       Punit ( "byte * 10^3" )]
   uint32 RemoteStorageKOctets;

      [Description ( 
          "Total amount of data received on ALL supported job "
          "channels by this managed element (e.g., a Print "
          "service)." ), 
       MappingStrings { 
          "MIB.PWG|PWG-IMAGING-COUNTER-MIB.icTrafficInputKOctets" }, 
       Punit ( "byte * 10^3" )]
   uint32 InputKOctets;

      [Description ( 
          "Total amount of data sent on ALL supported job channels "
          "by this managed element (e.g., a Fax service)." ), 
       MappingStrings { 
          "MIB.PWG|PWG-IMAGING-COUNTER-MIB.icTrafficOutputKOctets" }, 
       Punit ( "byte * 10^3" )]
   uint32 OutputKOctets;

      [Description ( 
          "Total messages received on ALL supported job channels by "
          "this managed element (e.g., an Email service)." ), 
       MappingStrings { 
          "MIB.PWG|PWG-IMAGING-COUNTER-MIB.icTrafficInputMessages" }]
   uint32 InputMessages;

      [Description ( 
          "Total messages sent on ALL supported job channels by "
          "this managed element (e.g., a Fax service)." ), 
       MappingStrings { 
          "MIB.PWG|PWG-IMAGING-COUNTER-MIB.icTrafficOutputMessages" }]
   uint32 OutputMessages;


};
