// Copyright (c) 2008 DMTF.  All rights reserved.
   [Association, Experimental, Version ( "2.21.0" ), 
    UMLPackagePath ( "CIM::View::Core" ), 
    Description ( 
       "CIM_ScopedView is used to associate an instance of CIM_System "
       "with a View instance representing the denormalized view of a "
       "managed resource related to the system. The type of "
       "relationship is not constrained. Examples include hosting, "
       "aggregation, composition, dependencies, etc." )]
class CIM_ScopedView : CIM_Dependency {

      [Key, Override ( "Antecedent" ), 
       Description ( 
          "Antecedent shall be a reference to a CIM_System that has "
          "a relationship with the managed resource." )]
   CIM_System REF Antecedent;

      [Key, Override ( "Dependent" ), 
       Description ( 
          "Dependent shall be a reference to an instance of "
          "CIM_View that represents a de-normalized or aggregate "
          "view of a managed resource that is related to the "
          "CIM_System referenced by the Antecedent property." )]
   CIM_View REF Dependent;


};
