// Copyright (c) 2013 DMTF.  All rights reserved.
   [Association, Experimental, Aggregation, Version ( "2.38.0" ), 
    UMLPackagePath ( "CIM::Core::Settings" ), 
    Description ( 
       "This aggregation relates a SettingData instance that "
       "represents an ITIL service option with other SettingData "
       "instances that represent aspects of this service option." )]
class CIM_ServiceOptionAspect {

      [Key, Aggregate, Description ( 
          "The ServiceOption that is aggregating aspects from other "
          "service options." )]
   CIM_SettingData REF ServiceOption;

      [Key, Description ( 
          "A reference to a service option that is an aspect of the "
          "aggregating service option." )]
   CIM_SettingData REF Aspect;


};
