// Copyright (c) 2013 DMTF.  All rights reserved.
   [Association, Experimental, Version ( "2.41.0" ), 
    UMLPackagePath ( "CIM::Core::Settings" ), 
    Description ( 
       "CollectionSettingData represents the association between a "
       "Collection class and the SettingData classes that are defined "
       "for it." )]
class CIM_CollectionSettingData {

      [Key, Description ( "The Collection." )]
   CIM_Collection REF Collection;

      [Key, Description ( 
          "The SettingData object that is associated with the Collection."
           )]
   CIM_SettingData REF SettingData;


};
