// Copyright (c) 2011 DMTF.  All rights reserved.
   [Association, Experimental, Aggregation, Version ( "2.28.0" ), 
    UMLPackagePath ( "CIM::Core::CoreElements" ), 
    Description ( 
       "The CIM_ConcreteComponentView instance is a view that is "
       "derived from the CIM_ConcreteComponent between a base "
       "CIM_ManagedElement (e.g., CIM_StorageExtent of a Disk Drive) "
       "and the CIM_ManagedElement it is a component of (e.g., its "
       "primordial CIM_StoragePool)." )]
class CIM_ConcreteComponentView : CIM_AbstractComponent {

      [Key, Override ( "GroupComponent" ), 
       Description ( 
          "The CIM_ManagedElement (e.g., CIM_StoragePool) to which "
          "the CIM_Managedelement (e.g., CIM_StorageExtent of the "
          "Disk Drive) is assigned." )]
   CIM_ManagedElement REF GroupComponent;

      [Key, Override ( "PartComponent" ), 
       Description ( 
          "A View Class (e.g., CIM_DiskDriveView) instance that is "
          "assigned to the CIM_ManagedElement (e.g., "
          "CIM_StoragePool)." )]
   CIM_View REF PartComponent;


};
