// Copyright (c) 2012 DMTF.  All rights reserved.
   [Association, Version ( "2.34.0" ), 
    UMLPackagePath ( "CIM::Core::CoreElements" ), 
    Description ( 
       "CIM_ElementView is used to associate an instance of CIM_View "
       "with an instance representing one or more instances of managed "
       "resources that contribute to the view." )]
class CIM_ElementView : CIM_Dependency {

      [Key, Override ( "Antecedent" ), 
       Description ( 
          "Antecedent shall be a reference to a CIM_ManagedElement "
          "that is an instance in the normalized representation of "
          "the managed resource that contributes to the view." )]
   CIM_ManagedElement REF Antecedent;

      [Key, Override ( "Dependent" ), 
       Description ( 
          "Dependent shall be a reference to an instance of "
          "CIM_View that represents a de-normalized or aggregate "
          "view of one or more instances that contribute to the "
          "view." )]
   CIM_View REF Dependent;


};
