// Copyright (c) 2008 DMTF.  All rights reserved.
   [Experimental, Version ( "2.20.0" ), 
    UMLPackagePath ( "CIM::Core::Statistics" ), 
    Description ( 
       "This class defines media used (for accounting and billing) "
       "ImagingStatisticalData associated with an imaging system "
       "(e.g., ComputerSystem), imaging service (e.g., PrintService), "
       "imaging device (e.g., Printer), imaging job (e.g., PrintJob), "
       "or any other imaging element. \n"
       "See: Section 4 Overview in PWG Counter MIB v2 (PWG 5106.3)." )]
class CIM_ImagingMediaUsedStatisticalData : CIM_ImagingStatisticalData {

      [Description ( 
          "A unique value used by the scoping imaging element "
          "(e.g., PrintService) to identify this instance of "
          "specific media. Note: This property is necessary to "
          "correlate counter and event information between CIM and "
          "SNMP interfaces." ), 
       MinValue ( 1 ), 
       MaxValue ( 2147483647 ), 
       MappingStrings { 
          "MIB.PWG|PWG-IMAGING-COUNTER-MIB.icMediaUsedIndex" }]
   uint32 SNMPRowId;

      [Description ( 
          "Total sheets of this specific media printed by this "
          "managed element (e.g., PrintService or PrintMarker)." ), 
       MappingStrings { 
          "MIB.PWG|PWG-IMAGING-COUNTER-MIB.icMediaUsedTotalSheets" }]
   uint32 TotalSheets;

      [Description ( 
          "Monochrome sheets of this specific media printed by this "
          "managed element (e.g., PrintService or PrintMarker)." ), 
       MappingStrings { 
          "MIB.PWG|PWG-IMAGING-COUNTER-MIB.icMediaUsedMonochromeSheets" }]
   uint32 MonochromeSheets;

      [Description ( 
          "Blank sheets of this specific media printed by this "
          "managed element (e.g., PrintService or PrintMarker)." ), 
       MappingStrings { 
          "MIB.PWG|PWG-IMAGING-COUNTER-MIB.icMediaUsedBlankSheets" }]
   uint32 BlankSheets;

      [Description ( 
          "Full color sheets of this specific media printed by this "
          "managed element (e.g., PrintService or PrintMarker)." ), 
       MappingStrings { 
          "MIB.PWG|PWG-IMAGING-COUNTER-MIB.icMediaUsedFullColorSheets" }]
   uint32 FullColorSheets;

      [Description ( 
          "Highlight color sheets of this specific media printed by "
          "this managed element (e.g., PrintService or "
          "PrintMarker)." ), 
       MappingStrings { 
          "MIB.PWG|PWG-IMAGING-COUNTER-MIB.icMediaUsedHighlightColorSheets" }]
   uint32 HighlightColorSheets;

      [Description ( 
          "The media size self-describing name for this specific "
          "media, for use with remote network management scripts "
          "and GUIs, specified as a visible US-ASCII string (ANSI "
          "X.3-1968) that shall not contain any US-ASCII control "
          "characters (0x00 to 0x1F inclusive, or 0x7F). This media "
          "size name shall not be localized. For example: "
          "na_letter_8.5x11in." ), 
       MinLen ( 0 ), 
       MaxLen ( 255 ), 
       MappingStrings { 
          "MIB.PWG|PWG-IMAGING-COUNTER-MIB.icMediaUsedMediaSizeName" }]
   string MediaSizeName;

      [Description ( 
          "The localized description of this specific media, for "
          "use with remote network management scripts and GUIs, "
          "specified as a Unicode string in the locale of the "
          "scoping managed element (e.g., "
          "CIM_Printer.CurrentNaturalLanguage). For example: Light "
          "blue deckle-edge letter stock. This media description "
          "should clearly distinguish different instances of the "
          "same media size (for example, by including specific "
          "media color, weight, etc.)." ), 
       MinLen ( 0 ), 
       MaxLen ( 255 ), 
       MappingStrings { 
          "MIB.PWG|PWG-IMAGING-COUNTER-MIB.icMediaUsedMediaInfo" }]
   string MediaInfo;

      [Description ( 
          "The friendly locally unique name for this specific "
          "media, for use with remote network management scripts "
          "and GUIs, specified as a Unicode string. This locally "
          "unique media name may be specified in any natural "
          "language, but shall not be localized. For example: "
          "customer-reply or na-letter-colored. \n"
          "Note: PWG Media Standardized Names (PWG 5101.1) "
          "restricts even custom media names to use US-ASCII "
          "strings (ANSI X.3-1968), although they may be specified "
          "in any natural language that can be represented in or "
          "transliterated into a US-ASCII string. On the other "
          "hand, IPP/1.1 (RFC 2911) and Job Mon MIB (RFC 2707) "
          "allow custom media names to use UTF-8 strings (RFC "
          "3629)." ), 
       MinLen ( 0 ), 
       MaxLen ( 255 ), 
       MappingStrings { 
          "MIB.PWG|PWG-IMAGING-COUNTER-MIB.icMediaUsedMediaName" }]
   string MediaName;

      [Description ( 
          "The locally unique accounting key for this specific "
          "media, for use with remote accounting systems, network "
          "management systems, fleet management based on SLAs "
          "(service level agreements), etc., specified as a visible "
          "US-ASCII string (ANSI X.3-1968) that shall not contain "
          "any US-ASCII control characters (0x00 to 0x1F inclusive, "
          "or 0x7F). This locally unique media accounting key may "
          "be specified in any natural language that can be "
          "represented in or transliterated into US-ASCII, but "
          "shall not be localized. \n"
          "This media accounting key should conform to the ABNF in "
          "Appendix A Media Accounting Key Format of PWG 5106.3 for "
          "interoperability. \n"
          "This media accounting key may contain characters not "
          "permitted in IPP keyword or name datatypes, unlike the "
          "corresponding (but more restricted) IPP media-key "
          "attribute defined in IPP Production Printing Set1 "
          "(IEEE/ISTO PWG 5100.3)." ), 
       MinLen ( 0 ), 
       MaxLen ( 255 ), 
       MappingStrings { 
          "MIB.PWG|PWG-IMAGING-COUNTER-MIB.icMediaUsedMediaAccountingKey" }]
   string MediaAccountingKey;


};
