// Copyright (c) 2013 DMTF.  All rights reserved.
   [Association, Experimental, Aggregation, Composition, Version ( 
       "2.37.0" ), 
    UMLPackagePath ( "CIM::Core" ), 
    Description ( 
       "The SCSI Protocol Controllers that are a component on a System" )]
class CIM_SystemSCSIProtocolController : CIM_SystemDevice {

      [Key, Override ( "PartComponent" ), 
       Weak, Description ( 
          "The SCSIProtocolController that is a component of a System."
           )]
   CIM_SCSIProtocolController REF PartComponent;


};
