// Copyright (c) 2011 DMTF.  All rights reserved.
   [Association, Experimental, Abstract, Version ( "2.28.0" ), 
    UMLPackagePath ( "CIM::Core::Statistics" ), 
    Description ( 
       "CIM_AbstractElementStatisticalData is an association that "
       "relates a ManagedElement (or a view of a ManagedElement) to "
       "its StatisticalData." )]
class CIM_AbstractElementStatisticalData {

      [Key, Description ( 
          "The ManagedElement (or view of the ManagedElement) for "
          "which statistical or metric data is defined." )]
   CIM_ManagedElement REF ManagedElement;

      [Key, Description ( "The statistic information/object." )]
   CIM_StatisticalData REF Stats;


};
