// Copyright (c) 2013 DMTF.  All rights reserved.
   [Deprecated { "No value" }, 
    Abstract, Version ( "2.37.0" ), 
    UMLPackagePath ( "CIM::Interop" ), 
    Description ( 
       "An abstract class for WBEM services such as the ObjectManager "
       "(CIM Server), Providers, protocol adapters, or other pluggable "
       "components. A type of CIM_Service that provides associated "
       "capabilities and details about the communication capabilities, "
       "namespaces, etc. for a specific WBEMService." )]
class CIM_WBEMService : CIM_Service {


};
