// Copyright (c) 2013 DMTF.  All rights reserved.
   [Version ( "2.38.0" ), 
    UMLPackagePath ( "CIM::Interop::WBEMProtocol" ), 
    Description ( 
       "WS-Management Capabiltiies. For more information see the "
       "WS-Management specification, DSP0226." )]
class CIM_WSManagementCapabilities : CIM_WBEMProtocolServiceCapabilities {

      [Description ( 
          "Enumeration of XPath features supported by an Object "
          "Manager or Provider associated via ElementCapabilities. "
          "For more information refer to the WS-Management "
          "Specification, DSP0226 1.0, Annex D \"XPath Support\"." ), 
       ValueMap { "2", "3", ".." }, 
       Values { 
          "Level 1 with basic node selector support and no filtering", 
          "Level 2 with basic filtering support", "DMTF Reserved" }]
   uint16 XPathFeatures;


};
