// Copyright (c) 2013 DMTF.  All rights reserved.
   [Version ( "2.38.0" ), 
    UMLPackagePath ( "CIM::Interop::WBEMProtocol" ), 
    Description ( 
       "The capabilities for the CIM-XML protocol. For more "
       "information, see DSP0200, DSP0201 and DSP0203." )]
class CIM_CIMXMLCapabilities : CIM_WBEMProtocolServiceCapabilities {

      [Required, Description ( 
          "Multiple operations conveniently allow multiple method "
          "invocations to be batched into a single HTTP message. "
          "This value shall be true if multiple operations are "
          "supported; false otherwise." )]
   boolean MultipleOperationsSupported;

      [Required, Description ( 
          "Describes whether the CIM Server is strictly validating "
          "(validates the XML document against the DTD) or not "
          "(loosely validating)." )]
   boolean Validated;


};
