// Copyright (c) 2013 DMTF.  All rights reserved.
   [Deprecated { "CIM_RegisteredProfile" }, 
    Version ( "2.37.0" ), 
    UMLPackagePath ( "CIM::Interop" ), 
    Description ( 
       "A RegisteredSubProfile subclasses RegisteredProfile to "
       "indicate that a scoping profile is required to provide "
       "context. The latter is specified by the mandatory association, "
       "SubProfileRequiresProfile." )]
class CIM_RegisteredSubProfile : CIM_RegisteredProfile {


};
