// Copyright (c) 2013 DMTF.  All rights reserved.
   [Association, Deprecated { "CIM_HostedDependency" }, 
    Version ( "2.39.0" ), 
    UMLPackagePath ( "CIM::Interop" ), 
    Description ( 
       "CIM_NamespaceInManager is deprecated. See "
       "CIM_WBEMServerNamespace and CIM_HostedDependency to model the "
       "relationship between a WBEMServer and the hosted namespaces.\r\n"
       "NamespaceInManager is an association describing the Namespaces "
       "hosted by a CIM ObjectManager." )]
class CIM_NamespaceInManager : CIM_HostedDependency {

      [Override ( "Antecedent" ), 
       Min ( 1 ), 
       Max ( 1 ), 
       Description ( "The ObjectManager containing a Namespace." )]
   CIM_ObjectManager REF Antecedent;

      [Override ( "Dependent" ), 
       Weak, Description ( "The Namespace in an ObjectManager." )]
   CIM_Namespace REF Dependent;


};
