// Copyright (c) 2014 DMTF.  All rights reserved.
   [Version ( "2.40.0" ), 
    UMLPackagePath ( "CIM::Network::Routes" ), 
    Description ( "NextHopIPRoute specifies routing in an IP network." )]
class CIM_NextHopIPRoute : CIM_NextHopRoute {

      [Description ( 
          "An enumerated integer indicating how the route was "
          "derived. This is useful for display and query purposes." ), 
       ValueMap { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", 
          "10", "11" }, 
       Values { "Unknown", "Other", "Connected", "User-Defined", 
          "IGRP", "EIGRP", "RIP", "Hello", "EGP", "BGP", "ISIS", 
          "OSPF" }, 
       ModelCorrespondence { "CIM_NextHopIPRoute.OtherDerivation" }]
   uint16 RouteDerivation;

      [Description ( 
          "A string describing how the route was derived when the "
          "RouteDerivation property is 1 (\"Other\")." ), 
       ModelCorrespondence { "CIM_NextHopIPRoute.RouteDerivation" }]
   string OtherDerivation;

      [Description ( "The mask for the Ipv4 destination address." ), 
       ModelCorrespondence { "CIM_IPProtocolEndpoint.SubnetMask" }]
   string DestinationMask;

      [Description ( 
          "The prefix length for the IPv6 destination address." ), 
       ModelCorrespondence { 
          "CIM_IPProtocolEndpoint.IPv6SubnetPrefixLength" }]
   uint8 PrefixLength;

      [Description ( 
          "An enumeration that describes the format of the address "
          "properties." ), 
       ValueMap { "0", "1", "2" }, 
       Values { "Unknown", "IPv4", "IPv6" }]
   uint16 AddressType;


};
