// Copyright (c) 2011 DMTF.  All rights reserved.
   [Association, Experimental, Aggregation, Version ( "2.28.0" ), 
    UMLPackagePath ( "CIM::Physical::ComponentElement" ), 
    Description ( 
       "The CIM_ContainerView instance is a view that is derived from "
       "the CIM_Container between the View Class of a physical element "
       "(e.g., the Disk Drive View) and the CIM_PhysicalPackage of the "
       "ComputerSystem." )]
class CIM_ContainerView : CIM_AbstractComponent {

      [Key, Override ( "GroupComponent" ), 
       Description ( 
          "The CIM_PhysicalPackage for the ComputerSystem instance "
          "that groups the View Class of the physical element "
          "(e.g., the CIM_PhysicalPackage of the Disk Drive)." )]
   CIM_PhysicalPackage REF GroupComponent;

      [Key, Override ( "PartComponent" ), 
       Description ( 
          "A View Class instance that includes CIM_PhysicalPackage "
          "information (e.g., for a CIM_DiskDrive)" )]
   CIM_View REF PartComponent;


};
