//%LICENSE////////////////////////////////////////////////////////////////
//
// Licensed to The Open Group (TOG) under one or more contributor license
// agreements.  Refer to the OpenPegasusNOTICE.txt file distributed with
// this work for additional information regarding copyright ownership.
// Each contributor licenses this file to you under the OpenPegasus Open
// Source License; you may not use this file except in compliance with the
// License.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included
// in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
// CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
// SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//
//////////////////////////////////////////////////////////////////////////
[Version ("1.0.0")] class benchmarkClassP00001S04000I00001
{
        [key] uint32 Identifier;
	string Property0001;
};

[Version ("1.0.0")] class benchmarkClassP00001S34000I00001
{
        [key] uint32 Identifier;
	string Property0001;
};

[Version ("1.0.0")] class benchmarkClassP00001S34000I00100
{
        [key] uint32 Identifier;
	string Property0001;
};

[Version ("1.0.0")] class benchmarkClassP00010S00400I00001
{
        [key] uint32 Identifier;
	string Property0001;
	string Property0002;
	string Property0003;
	string Property0004;
	string Property0005;
	string Property0006;
	string Property0007;
	string Property0008;
	string Property0009;
	string Property0010;
};

[Version ("1.0.0")] class benchmarkClassP00100S00040I00001
{
        [key] uint32 Identifier;
	string Property0001;
	string Property0002;
	string Property0003;
	string Property0004;
	string Property0005;
	string Property0006;
	string Property0007;
	string Property0008;
	string Property0009;
	string Property0010;
	string Property0011;
	string Property0012;
	string Property0013;
	string Property0014;
	string Property0015;
	string Property0016;
	string Property0017;
	string Property0018;
	string Property0019;
	string Property0020;
	string Property0021;
	string Property0022;
	string Property0023;
	string Property0024;
	string Property0025;
	string Property0026;
	string Property0027;
	string Property0028;
	string Property0029;
	string Property0030;
	string Property0031;
	string Property0032;
	string Property0033;
	string Property0034;
	string Property0035;
	string Property0036;
	string Property0037;
	string Property0038;
	string Property0039;
	string Property0040;
	string Property0041;
	string Property0042;
	string Property0043;
	string Property0044;
	string Property0045;
	string Property0046;
	string Property0047;
	string Property0048;
	string Property0049;
	string Property0050;
	string Property0051;
	string Property0052;
	string Property0053;
	string Property0054;
	string Property0055;
	string Property0056;
	string Property0057;
	string Property0058;
	string Property0059;
	string Property0060;
	string Property0061;
	string Property0062;
	string Property0063;
	string Property0064;
	string Property0065;
	string Property0066;
	string Property0067;
	string Property0068;
	string Property0069;
	string Property0070;
	string Property0071;
	string Property0072;
	string Property0073;
	string Property0074;
	string Property0075;
	string Property0076;
	string Property0077;
	string Property0078;
	string Property0079;
	string Property0080;
	string Property0081;
	string Property0082;
	string Property0083;
	string Property0084;
	string Property0085;
	string Property0086;
	string Property0087;
	string Property0088;
	string Property0089;
	string Property0090;
	string Property0091;
	string Property0092;
	string Property0093;
	string Property0094;
	string Property0095;
	string Property0096;
	string Property0097;
	string Property0098;
	string Property0099;
	string Property0100;
};

[Version ("1.0.0")] class benchmarkClassP00200S00020I00001
{
        [key] uint32 Identifier;
	string Property0001;
	string Property0002;
	string Property0003;
	string Property0004;
	string Property0005;
	string Property0006;
	string Property0007;
	string Property0008;
	string Property0009;
	string Property0010;
	string Property0011;
	string Property0012;
	string Property0013;
	string Property0014;
	string Property0015;
	string Property0016;
	string Property0017;
	string Property0018;
	string Property0019;
	string Property0020;
	string Property0021;
	string Property0022;
	string Property0023;
	string Property0024;
	string Property0025;
	string Property0026;
	string Property0027;
	string Property0028;
	string Property0029;
	string Property0030;
	string Property0031;
	string Property0032;
	string Property0033;
	string Property0034;
	string Property0035;
	string Property0036;
	string Property0037;
	string Property0038;
	string Property0039;
	string Property0040;
	string Property0041;
	string Property0042;
	string Property0043;
	string Property0044;
	string Property0045;
	string Property0046;
	string Property0047;
	string Property0048;
	string Property0049;
	string Property0050;
	string Property0051;
	string Property0052;
	string Property0053;
	string Property0054;
	string Property0055;
	string Property0056;
	string Property0057;
	string Property0058;
	string Property0059;
	string Property0060;
	string Property0061;
	string Property0062;
	string Property0063;
	string Property0064;
	string Property0065;
	string Property0066;
	string Property0067;
	string Property0068;
	string Property0069;
	string Property0070;
	string Property0071;
	string Property0072;
	string Property0073;
	string Property0074;
	string Property0075;
	string Property0076;
	string Property0077;
	string Property0078;
	string Property0079;
	string Property0080;
	string Property0081;
	string Property0082;
	string Property0083;
	string Property0084;
	string Property0085;
	string Property0086;
	string Property0087;
	string Property0088;
	string Property0089;
	string Property0090;
	string Property0091;
	string Property0092;
	string Property0093;
	string Property0094;
	string Property0095;
	string Property0096;
	string Property0097;
	string Property0098;
	string Property0099;
	string Property0100;
	string Property0101;
	string Property0102;
	string Property0103;
	string Property0104;
	string Property0105;
	string Property0106;
	string Property0107;
	string Property0108;
	string Property0109;
	string Property0110;
	string Property0111;
	string Property0112;
	string Property0113;
	string Property0114;
	string Property0115;
	string Property0116;
	string Property0117;
	string Property0118;
	string Property0119;
	string Property0120;
	string Property0121;
	string Property0122;
	string Property0123;
	string Property0124;
	string Property0125;
	string Property0126;
	string Property0127;
	string Property0128;
	string Property0129;
	string Property0130;
	string Property0131;
	string Property0132;
	string Property0133;
	string Property0134;
	string Property0135;
	string Property0136;
	string Property0137;
	string Property0138;
	string Property0139;
	string Property0140;
	string Property0141;
	string Property0142;
	string Property0143;
	string Property0144;
	string Property0145;
	string Property0146;
	string Property0147;
	string Property0148;
	string Property0149;
	string Property0150;
	string Property0151;
	string Property0152;
	string Property0153;
	string Property0154;
	string Property0155;
	string Property0156;
	string Property0157;
	string Property0158;
	string Property0159;
	string Property0160;
	string Property0161;
	string Property0162;
	string Property0163;
	string Property0164;
	string Property0165;
	string Property0166;
	string Property0167;
	string Property0168;
	string Property0169;
	string Property0170;
	string Property0171;
	string Property0172;
	string Property0173;
	string Property0174;
	string Property0175;
	string Property0176;
	string Property0177;
	string Property0178;
	string Property0179;
	string Property0180;
	string Property0181;
	string Property0182;
	string Property0183;
	string Property0184;
	string Property0185;
	string Property0186;
	string Property0187;
	string Property0188;
	string Property0189;
	string Property0190;
	string Property0191;
	string Property0192;
	string Property0193;
	string Property0194;
	string Property0195;
	string Property0196;
	string Property0197;
	string Property0198;
	string Property0199;
	string Property0200;
};

[Version ("1.0.0")] class benchmarkClassP00400S00010I00001
{
        [key] uint32 Identifier;
	string Property0001;
	string Property0002;
	string Property0003;
	string Property0004;
	string Property0005;
	string Property0006;
	string Property0007;
	string Property0008;
	string Property0009;
	string Property0010;
	string Property0011;
	string Property0012;
	string Property0013;
	string Property0014;
	string Property0015;
	string Property0016;
	string Property0017;
	string Property0018;
	string Property0019;
	string Property0020;
	string Property0021;
	string Property0022;
	string Property0023;
	string Property0024;
	string Property0025;
	string Property0026;
	string Property0027;
	string Property0028;
	string Property0029;
	string Property0030;
	string Property0031;
	string Property0032;
	string Property0033;
	string Property0034;
	string Property0035;
	string Property0036;
	string Property0037;
	string Property0038;
	string Property0039;
	string Property0040;
	string Property0041;
	string Property0042;
	string Property0043;
	string Property0044;
	string Property0045;
	string Property0046;
	string Property0047;
	string Property0048;
	string Property0049;
	string Property0050;
	string Property0051;
	string Property0052;
	string Property0053;
	string Property0054;
	string Property0055;
	string Property0056;
	string Property0057;
	string Property0058;
	string Property0059;
	string Property0060;
	string Property0061;
	string Property0062;
	string Property0063;
	string Property0064;
	string Property0065;
	string Property0066;
	string Property0067;
	string Property0068;
	string Property0069;
	string Property0070;
	string Property0071;
	string Property0072;
	string Property0073;
	string Property0074;
	string Property0075;
	string Property0076;
	string Property0077;
	string Property0078;
	string Property0079;
	string Property0080;
	string Property0081;
	string Property0082;
	string Property0083;
	string Property0084;
	string Property0085;
	string Property0086;
	string Property0087;
	string Property0088;
	string Property0089;
	string Property0090;
	string Property0091;
	string Property0092;
	string Property0093;
	string Property0094;
	string Property0095;
	string Property0096;
	string Property0097;
	string Property0098;
	string Property0099;
	string Property0100;
	string Property0101;
	string Property0102;
	string Property0103;
	string Property0104;
	string Property0105;
	string Property0106;
	string Property0107;
	string Property0108;
	string Property0109;
	string Property0110;
	string Property0111;
	string Property0112;
	string Property0113;
	string Property0114;
	string Property0115;
	string Property0116;
	string Property0117;
	string Property0118;
	string Property0119;
	string Property0120;
	string Property0121;
	string Property0122;
	string Property0123;
	string Property0124;
	string Property0125;
	string Property0126;
	string Property0127;
	string Property0128;
	string Property0129;
	string Property0130;
	string Property0131;
	string Property0132;
	string Property0133;
	string Property0134;
	string Property0135;
	string Property0136;
	string Property0137;
	string Property0138;
	string Property0139;
	string Property0140;
	string Property0141;
	string Property0142;
	string Property0143;
	string Property0144;
	string Property0145;
	string Property0146;
	string Property0147;
	string Property0148;
	string Property0149;
	string Property0150;
	string Property0151;
	string Property0152;
	string Property0153;
	string Property0154;
	string Property0155;
	string Property0156;
	string Property0157;
	string Property0158;
	string Property0159;
	string Property0160;
	string Property0161;
	string Property0162;
	string Property0163;
	string Property0164;
	string Property0165;
	string Property0166;
	string Property0167;
	string Property0168;
	string Property0169;
	string Property0170;
	string Property0171;
	string Property0172;
	string Property0173;
	string Property0174;
	string Property0175;
	string Property0176;
	string Property0177;
	string Property0178;
	string Property0179;
	string Property0180;
	string Property0181;
	string Property0182;
	string Property0183;
	string Property0184;
	string Property0185;
	string Property0186;
	string Property0187;
	string Property0188;
	string Property0189;
	string Property0190;
	string Property0191;
	string Property0192;
	string Property0193;
	string Property0194;
	string Property0195;
	string Property0196;
	string Property0197;
	string Property0198;
	string Property0199;
	string Property0200;
	string Property0201;
	string Property0202;
	string Property0203;
	string Property0204;
	string Property0205;
	string Property0206;
	string Property0207;
	string Property0208;
	string Property0209;
	string Property0210;
	string Property0211;
	string Property0212;
	string Property0213;
	string Property0214;
	string Property0215;
	string Property0216;
	string Property0217;
	string Property0218;
	string Property0219;
	string Property0220;
	string Property0221;
	string Property0222;
	string Property0223;
	string Property0224;
	string Property0225;
	string Property0226;
	string Property0227;
	string Property0228;
	string Property0229;
	string Property0230;
	string Property0231;
	string Property0232;
	string Property0233;
	string Property0234;
	string Property0235;
	string Property0236;
	string Property0237;
	string Property0238;
	string Property0239;
	string Property0240;
	string Property0241;
	string Property0242;
	string Property0243;
	string Property0244;
	string Property0245;
	string Property0246;
	string Property0247;
	string Property0248;
	string Property0249;
	string Property0250;
	string Property0251;
	string Property0252;
	string Property0253;
	string Property0254;
	string Property0255;
	string Property0256;
	string Property0257;
	string Property0258;
	string Property0259;
	string Property0260;
	string Property0261;
	string Property0262;
	string Property0263;
	string Property0264;
	string Property0265;
	string Property0266;
	string Property0267;
	string Property0268;
	string Property0269;
	string Property0270;
	string Property0271;
	string Property0272;
	string Property0273;
	string Property0274;
	string Property0275;
	string Property0276;
	string Property0277;
	string Property0278;
	string Property0279;
	string Property0280;
	string Property0281;
	string Property0282;
	string Property0283;
	string Property0284;
	string Property0285;
	string Property0286;
	string Property0287;
	string Property0288;
	string Property0289;
	string Property0290;
	string Property0291;
	string Property0292;
	string Property0293;
	string Property0294;
	string Property0295;
	string Property0296;
	string Property0297;
	string Property0298;
	string Property0299;
	string Property0300;
	string Property0301;
	string Property0302;
	string Property0303;
	string Property0304;
	string Property0305;
	string Property0306;
	string Property0307;
	string Property0308;
	string Property0309;
	string Property0310;
	string Property0311;
	string Property0312;
	string Property0313;
	string Property0314;
	string Property0315;
	string Property0316;
	string Property0317;
	string Property0318;
	string Property0319;
	string Property0320;
	string Property0321;
	string Property0322;
	string Property0323;
	string Property0324;
	string Property0325;
	string Property0326;
	string Property0327;
	string Property0328;
	string Property0329;
	string Property0330;
	string Property0331;
	string Property0332;
	string Property0333;
	string Property0334;
	string Property0335;
	string Property0336;
	string Property0337;
	string Property0338;
	string Property0339;
	string Property0340;
	string Property0341;
	string Property0342;
	string Property0343;
	string Property0344;
	string Property0345;
	string Property0346;
	string Property0347;
	string Property0348;
	string Property0349;
	string Property0350;
	string Property0351;
	string Property0352;
	string Property0353;
	string Property0354;
	string Property0355;
	string Property0356;
	string Property0357;
	string Property0358;
	string Property0359;
	string Property0360;
	string Property0361;
	string Property0362;
	string Property0363;
	string Property0364;
	string Property0365;
	string Property0366;
	string Property0367;
	string Property0368;
	string Property0369;
	string Property0370;
	string Property0371;
	string Property0372;
	string Property0373;
	string Property0374;
	string Property0375;
	string Property0376;
	string Property0377;
	string Property0378;
	string Property0379;
	string Property0380;
	string Property0381;
	string Property0382;
	string Property0383;
	string Property0384;
	string Property0385;
	string Property0386;
	string Property0387;
	string Property0388;
	string Property0389;
	string Property0390;
	string Property0391;
	string Property0392;
	string Property0393;
	string Property0394;
	string Property0395;
	string Property0396;
	string Property0397;
	string Property0398;
	string Property0399;
	string Property0400;
};

[Version ("1.0.0")] class benchmarkClassP00001S04000I00100
{
        [key] uint32 Identifier;
	string Property0001;
};

[Version ("1.0.0")] class benchmarkClassP00010S00400I00100
{
        [key] uint32 Identifier;
	string Property0001;
	string Property0002;
	string Property0003;
	string Property0004;
	string Property0005;
	string Property0006;
	string Property0007;
	string Property0008;
	string Property0009;
	string Property0010;
};

[Version ("1.0.0")] class benchmarkClassP00100S00040I00100
{
        [key] uint32 Identifier;
	string Property0001;
	string Property0002;
	string Property0003;
	string Property0004;
	string Property0005;
	string Property0006;
	string Property0007;
	string Property0008;
	string Property0009;
	string Property0010;
	string Property0011;
	string Property0012;
	string Property0013;
	string Property0014;
	string Property0015;
	string Property0016;
	string Property0017;
	string Property0018;
	string Property0019;
	string Property0020;
	string Property0021;
	string Property0022;
	string Property0023;
	string Property0024;
	string Property0025;
	string Property0026;
	string Property0027;
	string Property0028;
	string Property0029;
	string Property0030;
	string Property0031;
	string Property0032;
	string Property0033;
	string Property0034;
	string Property0035;
	string Property0036;
	string Property0037;
	string Property0038;
	string Property0039;
	string Property0040;
	string Property0041;
	string Property0042;
	string Property0043;
	string Property0044;
	string Property0045;
	string Property0046;
	string Property0047;
	string Property0048;
	string Property0049;
	string Property0050;
	string Property0051;
	string Property0052;
	string Property0053;
	string Property0054;
	string Property0055;
	string Property0056;
	string Property0057;
	string Property0058;
	string Property0059;
	string Property0060;
	string Property0061;
	string Property0062;
	string Property0063;
	string Property0064;
	string Property0065;
	string Property0066;
	string Property0067;
	string Property0068;
	string Property0069;
	string Property0070;
	string Property0071;
	string Property0072;
	string Property0073;
	string Property0074;
	string Property0075;
	string Property0076;
	string Property0077;
	string Property0078;
	string Property0079;
	string Property0080;
	string Property0081;
	string Property0082;
	string Property0083;
	string Property0084;
	string Property0085;
	string Property0086;
	string Property0087;
	string Property0088;
	string Property0089;
	string Property0090;
	string Property0091;
	string Property0092;
	string Property0093;
	string Property0094;
	string Property0095;
	string Property0096;
	string Property0097;
	string Property0098;
	string Property0099;
	string Property0100;
};

[Version ("1.0.0")] class benchmarkClassP00200S00020I00100
{
        [key] uint32 Identifier;
	string Property0001;
	string Property0002;
	string Property0003;
	string Property0004;
	string Property0005;
	string Property0006;
	string Property0007;
	string Property0008;
	string Property0009;
	string Property0010;
	string Property0011;
	string Property0012;
	string Property0013;
	string Property0014;
	string Property0015;
	string Property0016;
	string Property0017;
	string Property0018;
	string Property0019;
	string Property0020;
	string Property0021;
	string Property0022;
	string Property0023;
	string Property0024;
	string Property0025;
	string Property0026;
	string Property0027;
	string Property0028;
	string Property0029;
	string Property0030;
	string Property0031;
	string Property0032;
	string Property0033;
	string Property0034;
	string Property0035;
	string Property0036;
	string Property0037;
	string Property0038;
	string Property0039;
	string Property0040;
	string Property0041;
	string Property0042;
	string Property0043;
	string Property0044;
	string Property0045;
	string Property0046;
	string Property0047;
	string Property0048;
	string Property0049;
	string Property0050;
	string Property0051;
	string Property0052;
	string Property0053;
	string Property0054;
	string Property0055;
	string Property0056;
	string Property0057;
	string Property0058;
	string Property0059;
	string Property0060;
	string Property0061;
	string Property0062;
	string Property0063;
	string Property0064;
	string Property0065;
	string Property0066;
	string Property0067;
	string Property0068;
	string Property0069;
	string Property0070;
	string Property0071;
	string Property0072;
	string Property0073;
	string Property0074;
	string Property0075;
	string Property0076;
	string Property0077;
	string Property0078;
	string Property0079;
	string Property0080;
	string Property0081;
	string Property0082;
	string Property0083;
	string Property0084;
	string Property0085;
	string Property0086;
	string Property0087;
	string Property0088;
	string Property0089;
	string Property0090;
	string Property0091;
	string Property0092;
	string Property0093;
	string Property0094;
	string Property0095;
	string Property0096;
	string Property0097;
	string Property0098;
	string Property0099;
	string Property0100;
	string Property0101;
	string Property0102;
	string Property0103;
	string Property0104;
	string Property0105;
	string Property0106;
	string Property0107;
	string Property0108;
	string Property0109;
	string Property0110;
	string Property0111;
	string Property0112;
	string Property0113;
	string Property0114;
	string Property0115;
	string Property0116;
	string Property0117;
	string Property0118;
	string Property0119;
	string Property0120;
	string Property0121;
	string Property0122;
	string Property0123;
	string Property0124;
	string Property0125;
	string Property0126;
	string Property0127;
	string Property0128;
	string Property0129;
	string Property0130;
	string Property0131;
	string Property0132;
	string Property0133;
	string Property0134;
	string Property0135;
	string Property0136;
	string Property0137;
	string Property0138;
	string Property0139;
	string Property0140;
	string Property0141;
	string Property0142;
	string Property0143;
	string Property0144;
	string Property0145;
	string Property0146;
	string Property0147;
	string Property0148;
	string Property0149;
	string Property0150;
	string Property0151;
	string Property0152;
	string Property0153;
	string Property0154;
	string Property0155;
	string Property0156;
	string Property0157;
	string Property0158;
	string Property0159;
	string Property0160;
	string Property0161;
	string Property0162;
	string Property0163;
	string Property0164;
	string Property0165;
	string Property0166;
	string Property0167;
	string Property0168;
	string Property0169;
	string Property0170;
	string Property0171;
	string Property0172;
	string Property0173;
	string Property0174;
	string Property0175;
	string Property0176;
	string Property0177;
	string Property0178;
	string Property0179;
	string Property0180;
	string Property0181;
	string Property0182;
	string Property0183;
	string Property0184;
	string Property0185;
	string Property0186;
	string Property0187;
	string Property0188;
	string Property0189;
	string Property0190;
	string Property0191;
	string Property0192;
	string Property0193;
	string Property0194;
	string Property0195;
	string Property0196;
	string Property0197;
	string Property0198;
	string Property0199;
	string Property0200;
	string Property0201;
	string Property0202;
	string Property0203;
	string Property0204;
	string Property0205;
	string Property0206;
	string Property0207;
	string Property0208;
	string Property0209;
	string Property0210;
	string Property0211;
	string Property0212;
	string Property0213;
	string Property0214;
	string Property0215;
	string Property0216;
	string Property0217;
	string Property0218;
	string Property0219;
	string Property0220;
	string Property0221;
	string Property0222;
	string Property0223;
	string Property0224;
	string Property0225;
	string Property0226;
	string Property0227;
	string Property0228;
	string Property0229;
	string Property0230;
	string Property0231;
	string Property0232;
	string Property0233;
	string Property0234;
	string Property0235;
	string Property0236;
	string Property0237;
	string Property0238;
	string Property0239;
	string Property0240;
	string Property0241;
	string Property0242;
	string Property0243;
	string Property0244;
	string Property0245;
	string Property0246;
	string Property0247;
	string Property0248;
	string Property0249;
	string Property0250;
	string Property0251;
	string Property0252;
	string Property0253;
	string Property0254;
	string Property0255;
	string Property0256;
	string Property0257;
	string Property0258;
	string Property0259;
	string Property0260;
	string Property0261;
	string Property0262;
	string Property0263;
	string Property0264;
	string Property0265;
	string Property0266;
	string Property0267;
	string Property0268;
	string Property0269;
	string Property0270;
	string Property0271;
	string Property0272;
	string Property0273;
	string Property0274;
	string Property0275;
	string Property0276;
	string Property0277;
	string Property0278;
	string Property0279;
	string Property0280;
	string Property0281;
	string Property0282;
	string Property0283;
	string Property0284;
	string Property0285;
	string Property0286;
	string Property0287;
	string Property0288;
	string Property0289;
	string Property0290;
	string Property0291;
	string Property0292;
	string Property0293;
	string Property0294;
	string Property0295;
	string Property0296;
	string Property0297;
	string Property0298;
	string Property0299;
	string Property0300;
};

[Version ("1.0.0")] class benchmarkClassP00400S00010I00100
{
        [key] uint32 Identifier;
	string Property0001;
	string Property0002;
	string Property0003;
	string Property0004;
	string Property0005;
	string Property0006;
	string Property0007;
	string Property0008;
	string Property0009;
	string Property0010;
	string Property0011;
	string Property0012;
	string Property0013;
	string Property0014;
	string Property0015;
	string Property0016;
	string Property0017;
	string Property0018;
	string Property0019;
	string Property0020;
	string Property0021;
	string Property0022;
	string Property0023;
	string Property0024;
	string Property0025;
	string Property0026;
	string Property0027;
	string Property0028;
	string Property0029;
	string Property0030;
	string Property0031;
	string Property0032;
	string Property0033;
	string Property0034;
	string Property0035;
	string Property0036;
	string Property0037;
	string Property0038;
	string Property0039;
	string Property0040;
	string Property0041;
	string Property0042;
	string Property0043;
	string Property0044;
	string Property0045;
	string Property0046;
	string Property0047;
	string Property0048;
	string Property0049;
	string Property0050;
	string Property0051;
	string Property0052;
	string Property0053;
	string Property0054;
	string Property0055;
	string Property0056;
	string Property0057;
	string Property0058;
	string Property0059;
	string Property0060;
	string Property0061;
	string Property0062;
	string Property0063;
	string Property0064;
	string Property0065;
	string Property0066;
	string Property0067;
	string Property0068;
	string Property0069;
	string Property0070;
	string Property0071;
	string Property0072;
	string Property0073;
	string Property0074;
	string Property0075;
	string Property0076;
	string Property0077;
	string Property0078;
	string Property0079;
	string Property0080;
	string Property0081;
	string Property0082;
	string Property0083;
	string Property0084;
	string Property0085;
	string Property0086;
	string Property0087;
	string Property0088;
	string Property0089;
	string Property0090;
	string Property0091;
	string Property0092;
	string Property0093;
	string Property0094;
	string Property0095;
	string Property0096;
	string Property0097;
	string Property0098;
	string Property0099;
	string Property0100;
	string Property0101;
	string Property0102;
	string Property0103;
	string Property0104;
	string Property0105;
	string Property0106;
	string Property0107;
	string Property0108;
	string Property0109;
	string Property0110;
	string Property0111;
	string Property0112;
	string Property0113;
	string Property0114;
	string Property0115;
	string Property0116;
	string Property0117;
	string Property0118;
	string Property0119;
	string Property0120;
	string Property0121;
	string Property0122;
	string Property0123;
	string Property0124;
	string Property0125;
	string Property0126;
	string Property0127;
	string Property0128;
	string Property0129;
	string Property0130;
	string Property0131;
	string Property0132;
	string Property0133;
	string Property0134;
	string Property0135;
	string Property0136;
	string Property0137;
	string Property0138;
	string Property0139;
	string Property0140;
	string Property0141;
	string Property0142;
	string Property0143;
	string Property0144;
	string Property0145;
	string Property0146;
	string Property0147;
	string Property0148;
	string Property0149;
	string Property0150;
	string Property0151;
	string Property0152;
	string Property0153;
	string Property0154;
	string Property0155;
	string Property0156;
	string Property0157;
	string Property0158;
	string Property0159;
	string Property0160;
	string Property0161;
	string Property0162;
	string Property0163;
	string Property0164;
	string Property0165;
	string Property0166;
	string Property0167;
	string Property0168;
	string Property0169;
	string Property0170;
	string Property0171;
	string Property0172;
	string Property0173;
	string Property0174;
	string Property0175;
	string Property0176;
	string Property0177;
	string Property0178;
	string Property0179;
	string Property0180;
	string Property0181;
	string Property0182;
	string Property0183;
	string Property0184;
	string Property0185;
	string Property0186;
	string Property0187;
	string Property0188;
	string Property0189;
	string Property0190;
	string Property0191;
	string Property0192;
	string Property0193;
	string Property0194;
	string Property0195;
	string Property0196;
	string Property0197;
	string Property0198;
	string Property0199;
	string Property0200;
	string Property0201;
	string Property0202;
	string Property0203;
	string Property0204;
	string Property0205;
	string Property0206;
	string Property0207;
	string Property0208;
	string Property0209;
	string Property0210;
	string Property0211;
	string Property0212;
	string Property0213;
	string Property0214;
	string Property0215;
	string Property0216;
	string Property0217;
	string Property0218;
	string Property0219;
	string Property0220;
	string Property0221;
	string Property0222;
	string Property0223;
	string Property0224;
	string Property0225;
	string Property0226;
	string Property0227;
	string Property0228;
	string Property0229;
	string Property0230;
	string Property0231;
	string Property0232;
	string Property0233;
	string Property0234;
	string Property0235;
	string Property0236;
	string Property0237;
	string Property0238;
	string Property0239;
	string Property0240;
	string Property0241;
	string Property0242;
	string Property0243;
	string Property0244;
	string Property0245;
	string Property0246;
	string Property0247;
	string Property0248;
	string Property0249;
	string Property0250;
	string Property0251;
	string Property0252;
	string Property0253;
	string Property0254;
	string Property0255;
	string Property0256;
	string Property0257;
	string Property0258;
	string Property0259;
	string Property0260;
	string Property0261;
	string Property0262;
	string Property0263;
	string Property0264;
	string Property0265;
	string Property0266;
	string Property0267;
	string Property0268;
	string Property0269;
	string Property0270;
	string Property0271;
	string Property0272;
	string Property0273;
	string Property0274;
	string Property0275;
	string Property0276;
	string Property0277;
	string Property0278;
	string Property0279;
	string Property0280;
	string Property0281;
	string Property0282;
	string Property0283;
	string Property0284;
	string Property0285;
	string Property0286;
	string Property0287;
	string Property0288;
	string Property0289;
	string Property0290;
	string Property0291;
	string Property0292;
	string Property0293;
	string Property0294;
	string Property0295;
	string Property0296;
	string Property0297;
	string Property0298;
	string Property0299;
	string Property0300;
	string Property0301;
	string Property0302;
	string Property0303;
	string Property0304;
	string Property0305;
	string Property0306;
	string Property0307;
	string Property0308;
	string Property0309;
	string Property0310;
	string Property0311;
	string Property0312;
	string Property0313;
	string Property0314;
	string Property0315;
	string Property0316;
	string Property0317;
	string Property0318;
	string Property0319;
	string Property0320;
	string Property0321;
	string Property0322;
	string Property0323;
	string Property0324;
	string Property0325;
	string Property0326;
	string Property0327;
	string Property0328;
	string Property0329;
	string Property0330;
	string Property0331;
	string Property0332;
	string Property0333;
	string Property0334;
	string Property0335;
	string Property0336;
	string Property0337;
	string Property0338;
	string Property0339;
	string Property0340;
	string Property0341;
	string Property0342;
	string Property0343;
	string Property0344;
	string Property0345;
	string Property0346;
	string Property0347;
	string Property0348;
	string Property0349;
	string Property0350;
	string Property0351;
	string Property0352;
	string Property0353;
	string Property0354;
	string Property0355;
	string Property0356;
	string Property0357;
	string Property0358;
	string Property0359;
	string Property0360;
	string Property0361;
	string Property0362;
	string Property0363;
	string Property0364;
	string Property0365;
	string Property0366;
	string Property0367;
	string Property0368;
	string Property0369;
	string Property0370;
	string Property0371;
	string Property0372;
	string Property0373;
	string Property0374;
	string Property0375;
	string Property0376;
	string Property0377;
	string Property0378;
	string Property0379;
	string Property0380;
	string Property0381;
	string Property0382;
	string Property0383;
	string Property0384;
	string Property0385;
	string Property0386;
	string Property0387;
	string Property0388;
	string Property0389;
	string Property0390;
	string Property0391;
	string Property0392;
	string Property0393;
	string Property0394;
	string Property0395;
	string Property0396;
	string Property0397;
	string Property0398;
	string Property0399;
	string Property0400;
};
