// Copyright (c) 2005 DMTF.  All rights reserved.
   [Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Device::Modems" ), 
    Description ( 
       "The DSLModem class represents the superclass for Digital "
       "Subscriber Line (DSL) Devices. Properties will be defined in a "
       "future release of the model." )]
class CIM_DSLModem : CIM_ConnectionBasedModem {


};
