// Copyright (c) 2005 DMTF.  All rights reserved.
   [Abstract, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Device::UserDevices" ), 
    Description ( 
       "Display is a superclass for grouping the miscellaneous display "
       "devices that exist." )]
class CIM_Display : CIM_UserDevice {


};
