// Copyright (c) 2005 DMTF.  All rights reserved.
   [Version ( "2.10.0" ), 
    UMLPackagePath ( "CIM::Device::Controller" ), 
    Description ( 
       "Capabilities and management of a ManagementController. An I2C "
       "microcontroller is a type of ManagementController." )]
class CIM_ManagementController : CIM_Controller {


};
