// Copyright (c) 2005 DMTF.  All rights reserved.
   [Association, Version ( "2.10.0" ), 
    UMLPackagePath ( "CIM::Device::Printing" ), 
    Description ( 
       "This association indicates that PrintJobs can be passed to a "
       "Printer from a particular Queue." )]
class CIM_PrinterServicingQueue : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Description ( 
          "A destination Printer for Jobs enqueued on the Dependent Queue."
           )]
   CIM_Printer REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( 
          "A Queue that is providing Jobs to the Printer." )]
   CIM_PrintQueue REF Dependent;


};
