// Copyright (c) 2005 DMTF.  All rights reserved.
   [Association, Aggregation, Version ( "2.10.0" ), 
    UMLPackagePath ( "CIM::Device::Printing" ), 
    Description ( 
       "This association indicates which files are associated with a "
       "PrintJob." )]
class CIM_PrintJobFile : CIM_Component {

      [Aggregate, Override ( "GroupComponent" ), 
       Description ( 
          "The PrintJob that is based on one or more Files." )]
   CIM_PrintJob REF GroupComponent;

      [Override ( "PartComponent" ), 
       Description ( "The Files that make up a PrintJob." )]
   CIM_DataFile REF PartComponent;


};
