// Copyright (c) 2005 DMTF.  All rights reserved.
   [Association, Version ( "2.10.0" ), 
    UMLPackagePath ( "CIM::Device::Modems" ), 
    Description ( 
       "WakeUpServiceOnModem defines where the WakeUpService is "
       "implemented. The Service can either employ a Modem or "
       "NetworkAdapter to receive a wakeup signal." )]
class CIM_WakeUpServiceOnModem : CIM_DeviceServiceImplementation {

      [Override ( "Antecedent" ), 
       Max ( 1 ), 
       Description ( "The Modem that implements the WakeUpService." )]
   CIM_Modem REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( 
          "The wakeup Service that is provided on the Modem." )]
   CIM_WakeUpService REF Dependent;


};
