// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_BootService
// ==================================================================
   [UMLPackagePath ( "CIM::System::Boot" ), Version ( "2.6.0" ), 
    Description (
       "BootService represents the functionality provided by a Device, "
       "software or via a Network to load an Operating System on a "
       "UnitaryComputerSystem.")]
class CIM_BootService : CIM_Service {
};
