// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_CorrespondingSettingsRecord
// ==================================================================
   [Association, UMLPackagePath ( "CIM::System::Diagnostics" ),
    Version ( "2.9.0" ), Description (
       "CorrespondingSettingsRecord is used to tie a log record to its "
       "corresponding setting data record.")]
class CIM_CorrespondingSettingsRecord {

      [Key, Description (
          "The record containing the result data.")]
   CIM_DiagnosticRecord REF DataRecord;

      [Key, Description (
          "The record containing the DiagnosticSetting data that were "
          "used when the result was created.")]
   CIM_DiagnosticSettingRecord REF SettingsRecord;

};
