//%LICENSE////////////////////////////////////////////////////////////////
//
// Licensed to The Open Group (TOG) under one or more contributor license
// agreements.  Refer to the OpenPegasusNOTICE.txt file distributed with
// this work for additional information regarding copyright ownership.
// Each contributor licenses this file to you under the OpenPegasus Open
// Source License; you may not use this file except in compliance with the
// License.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included
// in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
// CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
// SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//
//////////////////////////////////////////////////////////////////////////

instance of CQL_TestElement
{
   InstanceID = 0;
};

instance of CQL_TestPropertyTypes
{
   InstanceID = 1;

   PropertyString = "BERT RULES";
   PropertyStringArray = { "CQL0","CQL1","CQL2","CQL3" };

   PropertyStringUint = NULL;
   PropertyStringSint = NULL;
   PropertystringReal = NULL;	

   PropertyUint8 = 255;
   PropertyUint8Array = { 0,1,2,3,4,5,6,7,8 };

   PropertyUint16 = 16;
   PropertyUint16Array = { 16,15,14,13,12,11,10 };

   PropertyUint32 = 32;
   PropertyUint32Array = { 32,31,30,29,28,27,26 };

   PropertyUint64 = 0xFFFFFFFFFFFFFFFF;
   PropertyUint64Array = { 0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFE,0xFFFFFFFFFFFFFFFD,0xFFFFFFFFFFFFFFFC,0xFFFFFFFFFFFFFFFB,0xFFFFFFFFFFFFFFFA };

   PropertySint8 = -8;
   PropertySint8Lower = -128;
   PropertySint8Upper = 127;
   PropertySint8Array = { 0,-1,-2,-3,-4,-5,-6,7,8 };

   PropertySint16 = 32767;
   PropertySint16Array = { -16,-15,-14,-13,12,11,10 };

   PropertySint32 = -32;
   PropertySint32Array = { -32,-31,-30,-29,-28,-27,-26 };

   PropertySint64 = -64;
   PropertySint64Lower = -9223372036854775808;
   PropertySint64Upper = 9223372036854775807;
   PropertySint64Array = { 0x7FFFFFFFFFFFFFFF, 0x7FFFFFFFFFFFFFFE, 0x7FFFFFFFFFFFFFFD, 0x7FFFFFFFFFFFFFFC, 0x7FFFFFFFFFFFFFFB, 0x7FFFFFFFFFFFFFFA };

   PropertyBoolean = true;
   PropertyBooleanArray = { true,false,false,true,true,true,false };

   PropertyReal32 = -32.0;

//  Due to issues with precision, the real number boundaries are removed for now
//   PropertyReal32NegOverflow = -3.4028235677973365E+38;
//   PropertyReal32NegNormUpper = -3.4028234663852886E+38;
//   PropertyReal32NegNormLower = -1.1754943508222875E-38;
//   PropertyReal32NegDeNormUpper = -1.1754942106924411E-38;
//   PropertyReal32NegDeNormLower = -1.4012984643248170E-45;
//   PropertyReal32NegUnderflow = -7.0064923216240861E-46;
//   PropertyReal32PosUnderflow = 7.0064923216240861E-46;
//   PropertyReal32PosDeNormLower = 1.4012984643248170E-45;
//   PropertyReal32PosDeNormUpper = 1.1754942106924411E-38;
//   PropertyReal32PosNormLower = 1.1754943508222875E-38;
//   PropertyReal32PosNormUpper = 3.4028234663852886E+38;
//   PropertyReal32PosOverflow = 3.4028235677973365E+38;
   PropertyReal32Array = { 32.001,31.001,30.001,29.001,28.001,27.001,-26.001 };

   PropertyReal64 = 64.0;

//  Due to issues with precision, the real number boundaries are removed for now
//   PropertyReal64NegNormUpper = -1.7976931348623157E+308;
//   PropertyReal64NegNormLower = -2.2250738585072014E-308;
//   PropertyReal64NegDeNormUpper = -2.2250738585072010E-308;
//   PropertyReal64NegDeNormLower = -2.4703282292062328E-324;
//   PropertyReal64NegDeNormLower = -4.9406564584124654E-324;
//   PropertyReal64PosDeNormLower = 2.4703282292062328E-324;
//   PropertyReal64PosDeNormLower = 4.9406564584124654E-324;
//   PropertyReal64PosDeNormUpper = 2.2250738585072010E-308;
//   PropertyReal64PosNormLower = 2.2250738585072014E-308;
//   PropertyReal64PosNormUpper = 1.7976931348623157E+308;
   PropertyReal64Array = { 64.001,63.001,62.001,61.001,60.001,59.001,-58.001 };

   PropertyDatetime = "20040811105625.000000-360";
   PropertyInterval = "12345678223344.123456:000";
   PropertyDatetimeArray = { "20040811105625.000000-360", "20030811105625.000000-360", "20020811105625.000000-360" };

   PropertyChar16 = "A";
   PropertyChar16Array = { "A","a" };

   PropertyValueMap = 1;
};

instance of CQL_TestPropertyTypes
{
   InstanceID = 2;

   PropertyString = "Bert Rules";
   PropertyStringArray = { "CQL0","CQL1","CQL2","CQL3" };

   PropertyStringUint = "347";
   PropertyStringSint = "-743";
   PropertystringReal = "9.1250000000000000E1";	

   PropertyUint8 = 8;
   PropertyUint8Array = { 0,1,2,3,4,5,6,7,8 };

   PropertyUint16 = 16;
   PropertyUint16Array = { 16,15,14,13,12,11,10 };

   PropertyUint32 = 6811;
   PropertyUint32Array = { 32,31,30,29,28,27,26 };

   PropertyUint64 = 0xFFFFFFFFFFFFFFFF;
   PropertyUint64Array = { 0xFFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFFE,0xFFFFFFFFFFFFFFFD,0xFFFFFFFFFFFFFFFC,0xFFFFFFFFFFFFFFFB,0xFFFFFFFFFFFFFFFA };

   PropertySint8 = 16;
   PropertySint8Lower = -128;
   PropertySint8Upper = 127;
   PropertySint8Array = { 0,-1,-2,-3,-4,-5,-6,7,8 };

   PropertySint16 = 16;
   PropertySint16Array = { -16,-15,-14,-13,12,11,10 };

   PropertySint32 = -6811;
   PropertySint32Array = { -32,-31,-30,-29,-28,-27,-26 };

   PropertySint64 = 0x7FFFFFFFFFFFFFFF;
   PropertySint64Lower = -808;
   PropertySint64Upper = 807;
   PropertySint64Array = { 0x7FFFFFFFFFFFFFFF, 0x7FFFFFFFFFFFFFFE, 0x7FFFFFFFFFFFFFFD, 0x7FFFFFFFFFFFFFFC, 0x7FFFFFFFFFFFFFFB, 0x7FFFFFFFFFFFFFFA };

   PropertyBoolean = true;
   PropertyBooleanArray = { true,false,false,true,true,true,false };

   PropertyReal32 = 32.2;
   PropertyReal32Array = { 32.001,31.001,30.001,29.001,28.001,27.001,-26.001 };

   PropertyReal64 = 64.64;
   PropertyReal64Array = { 64.001,63.001,62.001,61.001,60.001,59.001,-58.001 };

   PropertyDatetime = "20040811105625.000000-360";
   PropertyInterval = "00005678223344.000056:000";
   PropertyDatetimeArray = { "20040811105625.000000-360", "20030811105625.000000-360", "20020811105625.000000-360" };

   PropertyChar16 = "A";
   PropertyChar16Array = { "A","a" };

   PropertyValueMap = 2;

};

instance of CQL_TestPropertyTypesMissing
{
   InstanceID = 3;
};

instance of CIM_ComputerSystem
{
   CreationClassName = "CIM_RunningOS";
   Name = "sysName";
   Description = "Computer System";
   EnabledState = 2;
   ResetCapability = 3;
};

instance of CQL_TestNullValueTypes
{
   InstanceId = 1;
   stringProperty = "stringProperty";
   sint64Property = -5332;
   uint64Property = 5332;
   real64Property = -123.567;
   datetimeProperty = "20040811105625.000000-360";
   char16Property = "I";
};
