// Copyright (c) 2005 DMTF.  All rights reserved.
   [Abstract, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::User::SecurityServices" ), 
    Description ( "A service providing security functionaity." )]
class CIM_SecurityService : CIM_Service {


};
