// Copyright (c) 2005 DMTF.  All rights reserved.
   [Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::User::SecurityServices" ), 
    Description ( 
       "CIM_LocalCredentialManagementService is a credential "
       "management service that provides management of credentials "
       "used by the local system." )]
class CIM_LocalCredentialManagementService : CIM_CredentialManagementService {


};
