// Copyright (c) 2013 DMTF.  All rights reserved.
   [Association, Deprecated { 
       "CIM_OwningCollectionElement.OwningElement" }, 
    Aggregation, Version ( "2.37.0" ), 
    UMLPackagePath ( "CIM::User::Org" ), 
    Description ( 
       "CIM_CollectionInSystem is deprecated in lieu of "
       "CIM_OwningCollectionElement, which is semantically equivalent. \n"
       "CIM_CollectionInSystem is an association used to establish a "
       "parent-child relationship between a collection and an \'owning\' "
       "System such as an AdminDomain or ComputerSystem. A single "
       "collection should not have both a CollectionInOrganization and "
       "a CollectionInSystem association." )]
class CIM_CollectionInSystem {

      [Deprecated { "CIM_OwningCollectionElement.OwningElement" }, 
       Key, Aggregate, Max ( 1 ), 
       Description ( 
          "The parent system responsible for the collection." )]
   CIM_System REF Parent;

      [Deprecated { "CIM_OwningCollectionElement.OwnedElement" }, 
       Key, Description ( "The collection." )]
   CIM_Collection REF Child;


};
