// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_IKESecretIsNamed
// ==================================================================
   [Association, UMLPackagePath ( "CIM::User::SharedSecret" ),
    Version ( "2.6.0" ), Description (
       "CIM_IKESecretIsNamed association provides the relationship "
       "between a SharedSecretService and a NamedSharedIKESecret.")]
class CIM_IKESecretIsNamed : CIM_ManagedCredential {

      [Override ( "Antecedent" ), Min ( 1 ), Max ( 1 ), Description (
          "The SharedSecretService that manages a "
          "NamedSharedIKESecret.")]
   CIM_SharedSecretService REF Antecedent;

      [Override ( "Dependent" ), Weak, Description (
          "The managed NamedSharedIKESecret.")]
   CIM_NamedSharedIKESecret  REF Dependent;
};
