.TA c \" lowercase initial letter of .TH name
.TH cimreparchive 8 
.SH NAME
cimreparchive \- create an archive copy of the CIM Server repository
.SH SYNOPSIS

\fBcimreparchive \fParchive_file

\fBcimreparchive --help

\fBcimreparchive --version
.SH DESCRIPTION
The 
.B cimreparchive 
command creates an archive copy of the CIM Server
repository in the specified \fParchive_file. The archive copy is assured to
contain a consistent repository state even if it is created while the
CIM Server is running.
.PP
The \fParchive_file is created using the tar(1) command.  To restore the
repository from the \fParchive_file, stop the cimserver, move the active
repository files to a different location, use tar(2) to extract the
archived repository files, and restart the cimserver.  (Note that the
repository location is printed when an archive file is created.)
.SS Options
.B cimreparchive 
recognizes the following options:
.RS
.TP 15
.B --help
Displays the command help message.  
.TP
.B --version
Displays the CIM Server version number.
.SH EXIT STATUS
When an error occurs, an error message is written to the standard error
stream and a non-zero exit status value is returned. The following exit
status values are defined:
.RS
.TP
.B 0
Success
.PD
.TP
.B 1
General error
.PD
.TP
.B 2
Failed to initiate archive operation
.PD
.TP
.B 3
Archive operation failed
.PD
.RE
.SH SEE ALSO
.PP
cimserver(8), tar(1).
