.\" .TA c \" lowercase initial letter of .TH name
.TH "cimuser" "8" "" "" ""
.SH "NAME"
cimuser \- add, modify, remove, or list CIM users
.SH "SYNOPSIS"
\fBcimuser\fP \fB\-a\fP \fB\-u\fP username [ \fB\-w\fP password ] 

\fBcimuser\fP \fB\-m\fP \fB\-u\fP username [ \fB\-w\fP old password ] [ \fB\-n\fP new password ]

\fBcimuser\fP \fB\-r\fP \fB\-u\fP username 

\fBcimuser\fP \fB\-l\fP

\fBcimuser\fP \fB\-h\fP

\fBcimuser\fP \fB\-\-help\fP

\fBcimuser\fP \fB\-\-version\fP

.SH "REMARKS"
This command can be executed only by privileged user(s).
.SH "DESCRIPTION"
.PP 
The 
.B cimuser 
command command provides a command line interface to manage CIM users. If the password is not specified at the command line, the user will be prompted for it. If more than 8 characters are entered for the password, then the first eight characters will be used. There is no default authorization permissions set for newly added users. For more information on adding authorization information see cimauth(8).
.SS Options
.PP 
The 
.B cimuser
command recognizes the following options:
.RS
.TP 15
.B  \-a
Add a new CIM user.
.TP 
.B \-h, \-\-help
Display command usage information.
.TP 
.B \-l
List the names of CIM users.
.TP 
.B \-m
Modify a CIM user password.
.TP 
.B \-n
Supply a new password for the specified user name.
WARNING: Passwords should not be specified on the command line on a multi-user
system, since command-line options are typically world-readable for a short
window of time.  If no password is provided on the command line,
.B cimuser 
will prompt for one.
.TP 
.B \-r
Remove the specified CIM user.
.TP 
.B \-u
Specify a CIM user name.
.TP 
.B \-\-version
Display CIM Server version number.
.TP 
.B \-w
Supply a password for the specified user name.
WARNING: Passwords should not be specified on the command line on a multi-user
system, since command-line options are typically world-readable for a short
window of time.  If no password is provided on the command line,
.B cimuser 
will prompt for one.
.RE
.SH "EXIT STATUS"
.PP 
When an error occurs, an
error message is written to stderr and an error value of 1 is returned. The
following return values are returned:
.RS
.TP 
.B 0
Successful completion
.PD 0
.TP 
.B 1
Error
.PD
.RE
.SH "USAGE NOTE"
.PP 
The 
.B cimuser 
command requires that the CIM Server is running.
.SH "EXAMPLES"
.PP 
The following command adds user "guest", a new CIM user. The password for this user is "guest".
.IP 
.B "cimuser \-a \-u guest \-w guest"
.PP 
The following command adds user "guest", a new CIM user. Since the password is not specified on the command line, the user will be prompted for it.
.IP 
.B "cimuser \-a \-u guest "

Please enter your password:

Please re\-enter your password:

.PP 
The following command modifies the password  for user "guest", with the new password "bar".
.IP 
.B "cimuser \-m \-u guest \-w foo \-n bar"
.PP 
The following command removes the CIM user "guest".
.IP 
.B "cimuser \-r \-u guest"
.PP 
The following command displays the list of CIM user names.
.IP 
.B "cimuser \-l"
.SH "SEE ALSO"
.PP 
cimserver(8), cimconfig(8).
