#//%LICENSE////////////////////////////////////////////////////////////////
#//
#// Licensed to The Open Group (TOG) under one or more contributor license
#// agreements.  Refer to the OpenPegasusNOTICE.txt file distributed with
#// this work for additional information regarding copyright ownership.
#// Each contributor licenses this file to you under the OpenPegasus Open
#// Source License; you may not use this file except in compliance with the
#// License.
#//
#// Permission is hereby granted, free of charge, to any person obtaining a
#// copy of this software and associated documentation files (the "Software"),
#// to deal in the Software without restriction, including without limitation
#// the rights to use, copy, modify, merge, publish, distribute, sublicense,
#// and/or sell copies of the Software, and to permit persons to whom the
#// Software is furnished to do so, subject to the following conditions:
#//
#// The above copyright notice and this permission notice shall be included
#// in all copies or substantial portions of the Software.
#//
#// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
#// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
#// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
#// CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
#// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
#// SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#//
#//////////////////////////////////////////////////////////////////////////

ROOT = ../../../../../../../../../..

include $(ROOT)/mak/config.mak
include $(ROOT)/test/config.mak

XMLSCRIPTS = \
	CreateInstance53000 \
	CreateInstance53002 \
	CreateInstance53003 \
	CreateInstance53004 \
	CreateInstance53005 \
	CreateInstance53006 \
	CreateInstance53007 \
	CreateInstance53008 \
	CreateInstance53009 \
	CreateInstance53010 \
	CreateInstance53011 \
	CreateInstance53012 \
	CreateInstance53013 \
	CreateInstance53014 \
	CreateInstance53015 \
	CreateInstance53016 \
	CreateInstance53017 \
	CreateInstance53018 \
	CreateInstance53019 \
	CreateInstance53020 \
	CreateInstance53021 \
	CreateInstance53022 \
	CreateInstance53023 \
	CreateInstance53024 \
	CreateInstance53025 \
	CreateInstance53026 \
	CreateInstance53027 \
	CreateInstance53028 \
	CreateInstance53029 \
	CreateInstance53030 \
	CreateInstance53031 \
	CreateInstance53032 \
	CreateInstance53033 \
	CreateInstance53034 \
	CreateInstance53035 \
	CreateInstance53036 \
	CreateInstance53037 \
	CreateInstance53038 \
	CreateInstance53039 \
	CreateInstance53040 \
	CreateInstance53041 \
	CreateInstance53042 \
	CreateInstance53043 \
	CreateInstance53044 \
	CreateInstance53045 \
	CreateInstance53046 \
	CreateInstance53047 \
	CreateInstance53048 \
	CreateInstance53049 \
	CreateInstance53050 \
	CreateInstance53051 \
	CreateInstance53052 \
	CreateInstance53053 \
	CreateInstance53054

ifndef SECURITY_ENABLED
XMLSCRIPTS += CreateInstance53001
endif

include $(ROOT)/test/configend.mak
