// Copyright (c) 2005 DMTF.  All rights reserved.
   [Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Device::Modems" ), 
    Description ( 
       "The CableModem class represents a device for transmission "
       "across a cable infrastructure." )]
class CIM_CableModem : CIM_ConnectionBasedModem {


};
