#pragma include("CIM2131/CIM_Schema.mof")
#pragma include("Pegasus/InterOp/VER20/PG_Events20.mof")
#pragma include("Pegasus/ManagedSystem/VER20/PG_ManagedSystemSchema20.mof")
#pragma include("Pegasus/ManagedSystem/VER20/PG_ManagedSystemTestSchema20.mof")
