// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_DependencyContext
// ==================================================================
   [Association, UMLPackagePath ( "CIM::Core::Settings" ), Aggregation,
    Version ( "2.6.0" ), Description (
       "This relationship associates a Dependency with one or more "
       "Configuration objects. For example, a ComputerSystem's "
       "dependencies could change based on the site/network to which "
       "the System is attached.")]
class CIM_DependencyContext {

      [Key, Aggregate, Description (
          "The Configuration object that aggregates the Dependency.")]
   CIM_Configuration REF Context;

      [Key, Description (
          "An aggregated Dependency.")]
   CIM_Dependency REF Dependency;
};
