// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_ElementConfiguration
// ==================================================================
   [Association, UMLPackagePath ( "CIM::Core::Settings" ),
       Version ( "2.6.0" ), Description (
       "This association relates a Configuration object to one or more "
       "ManagedSystemElements. The Configuration object represents a "
       "certain behavior, or a desired functional state for the "
       "associated ManagedSystemElements.")]
class CIM_ElementConfiguration {

      [Key, Description (
          "The ManagedSystemElement.")]
   CIM_ManagedSystemElement REF Element;

      [Key, Description (
          "The Configuration object that groups the Settings and "
          "dependencies associated with the ManagedSystemElement.")]
   CIM_Configuration REF Configuration;
};
