// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_FRUIncludesProduct
// ==================================================================
   [Association, UMLPackagePath ( "CIM::Core::ProductFRU" ),
    Aggregation, Composition, Version ( "2.7.0" ), Description (
       "Indicates that a FRU may be composed of other Product(s).")]
class CIM_FRUIncludesProduct {

      [Key, Aggregate, Max ( 1 ), Description (
          "The FRU.")]
   CIM_FRU REF FRU;

      [Key, Description (
          "The Product which is a part of the FRU.")]
   CIM_Product REF Component;
};
