M-POST /cimlistener/browser HTTP/1.1
HOST: http://localhost:2003
Content-Type: application/xml; charset=utf-8
Content-Length: 964
Man: http://www.dmtf.org/cim/mapping/http/v1.0 ; ns=40
40-CIMExport: MethodRequest
40-CIMExportMethod: ExportIndication

<?xml version="1.0" encoding="utf-8" ?> 
<CIM CIMVERSION="2.0" DTDVERSION="2.0"> 
 <MESSAGE ID="1007" PROTOCOLVERSION="1.0"> 
  <SIMPLEEXPREQ> 
    <EXPMETHODCALL NAME="ExportIndication"> 
     <EXPPARAMVALUE NAME="NewIndication"> 
      <INSTANCE CLASSNAME="CIM_AlertIndication" > 
        <PROPERTY NAME="Description" TYPE="string"> 
          <VALUE>Sample CIM_AlertIndication indication</VALUE> 
        </PROPERTY> 
        <PROPERTY NAME="AlertType" TYPE="uint16"> 
          <VALUE>1</VALUE> 
        </PROPERTY> 
        <PROPERTY NAME="PerceivedSeverity" TYPE="uint16"> 
          <VALUE>3</VALUE> 
        </PROPERTY> 
        <PROPERTY NAME="ProbableCause" TYPE="uint16"> 
          <VALUE>2</VALUE> 
        </PROPERTY> 
        <PROPERTY NAME="IndicationTime" TYPE="datetime"> 
          <VALUE>20010515104354.000000:000</VALUE> 
        </PROPERTY> 
      </INSTANCE> 
    </EXPPARAMVALUE> 
  </EXPMETHODCALL> 
 </SIMPLEEXPREQ> 
 </MESSAGE> 
</CIM> 
