#pragma locale ("en_US")
instance of PG_ProviderModule
{
    Description = "Instance Provider for the TestClass";
    Caption = "Instance Provider for the TestClass";
    Name = "ExceptionsTestModule";
    Vendor = "OpenPegasus";
    Version = "1.0";
    InterfaceType = "C++Default";
    InterfaceVersion = "2.1.0";
    Location = "ExceptionsTest";
};

instance of PG_Provider
{
    ProviderModuleName = "ExceptionsTestModule";
    Name = "ExceptionsTest";
};

instance of PG_ProviderCapabilities
{
    ProviderModuleName = "ExceptionsTestModule";
    ProviderName = "ExceptionsTest";
    CapabilityID = "ExceptionsTest";
    ClassName = "FirstClass";
    Namespaces = { "root/SampleProvider" };
    ProviderType = { 2 };
    SupportedProperties = NULL;
    SupportedMethods = NULL;
};

instance of PG_ProviderCapabilities
{
    ProviderModuleName = "ExceptionsTestModule";
    ProviderName = "ExceptionsTest";
    CapabilityID = "ExceptionsTest";
    ClassName = "SecondClass";
    Namespaces = { "root/SampleProvider" };
    ProviderType = { 2 };
    SupportedProperties = NULL;
    SupportedMethods = NULL;
};

instance of PG_ProviderCapabilities
{
    ProviderModuleName = "ExceptionsTestModule";
    ProviderName = "ExceptionsTest";
    CapabilityID = "ExceptionsTest";
    ClassName = "ThirdClass";
    Namespaces = { "root/SampleProvider" };
    ProviderType = { 2 };
    SupportedProperties = NULL;
    SupportedMethods = NULL;
};

