#pragma locale ("en_US")
instance of PG_ProviderModule
{
    Description = "Instance Provider for the CIMOMSampleClass";
    Caption = "Instance Provider for the CIMOMSampleClass";
    Name = "LargeDataProviderModule";
    Vendor = "OpenPegasus";
    Version = "1.0";
    InterfaceType = "C++Default";
    InterfaceVersion = "2.1.0";
    Location = "LargeDataProvider";
};

instance of PG_Provider
{
    ProviderModuleName = "LargeDataProviderModule";
    Name = "LargeDataProvider";
};

instance of PG_ProviderCapabilities
{
    ProviderModuleName = "LargeDataProviderModule";
    ProviderName = "LargeDataProvider";
    CapabilityID = "LargeDataProvider";
    ClassName = "SampleClass";
    Namespaces = { "root/SampleProvider" };
    ProviderType = { 2 };
    SupportedProperties = NULL;
    SupportedMethods = NULL;
};
