class MultithreadingSampleClass
{
	[key, read]
	Uint16 Ident;
};

class ThreadSampleOne:MultithreadingSampleClass
{
	[key, read]
	Uint16 Id;
	String Message;
};

class ThreadSampleTwo:MultithreadingSampleClass
{
	[key, read]
	String ClName;
};

class ThreadSampleThree:MultithreadingSampleClass
{
	[key, read]
	Uint16 Id;
	Uint8 GroupId;
};

