// ===================================================================
// 	ParserTestProvider
// ===================================================================

instance of PG_ProviderModule
{
   Description = "A simple test provider";
   Name = "ParserTestProviderModule";
   Location = "ParserTestProviderModule";
   Vendor = "OpenPegasus";
   Version = "2.1.0";
   InterfaceType = "C++Default";
   InterfaceVersion = "2.1.0";
};

instance of PG_Provider
{
   ProviderModuleName = "ParserTestProviderModule";
   // The provider name as referenced in the code.
   Name = "XMLParserTestProvider";	
};

instance of PG_ProviderCapabilities
{
   ProviderModuleName = "ParserTestProviderModule";
   ProviderName = "ParserTestProvider";
   CapabilityID = "1";
   // Name of the CIM class as defined in the mof.
   ClassName = "SampleXMLParserTestClass";
   Namespaces = {"root/cimv2"};
   ProviderType = { 2 }; // Instance
   SupportedProperties = NULL; // All properties
   SupportedMethods = NULL; // All methods
};
