class TimingSampleClass
{
	[key, read]
	string listName;
};

class TimeOne:TimingSampleClass
{
	[key, read]
	Uint16 Id;
	
	[read, write]
	string Message;
};

class TimeTwo:TimingSampleClass
{
	[key, read]
	Uint8 Srno;
	[read]
	Uint16 TimeVar;
};

class TimeThree:TimingSampleClass
{
	[read, write]
	string CName;
};
