// Copyright (c) 2013 DMTF.  All rights reserved.
   [Association, Experimental, Version ( "2.38.0" ), 
    UMLPackagePath ( "CIM::System::FileStatistics" ), 
    Description ( 
       "Instances of this class associate a "
       "CIM_FileSystemStatisticsManifestCollection to the "
       "StatisticsCollection to which it applies. The "
       "ManifestCollection contains the Manifests that are used to "
       "filter requests for the retrieval of statistics." )]
class CIM_AssociatedFileSystemStatisticsManifestCollection {

      [Key, Min ( 1 ), 
       Max ( 1 ), 
       Description ( 
          "The collection of statistics filtered by the "
          "FileSystemStatisticsManifestCollection." )]
   CIM_StatisticsCollection REF Statistics;

      [Key, Description ( 
          "The collection of Manifests applied to the StatisticsCollection."
           )]
   CIM_FileSystemStatisticsManifestCollection REF ManifestCollection;


};
