// Copyright (c) 2012 DMTF.  All rights reserved.
   [Experimental, Version ( "2.31.0" ), 
    UMLPackagePath ( "CIM::System::Diagnostics" ), 
    Description ( 
       "This class defines the permissible settings that can be used "
       "for optical drive diagnostic tests." )]
class CIM_OpticalDriveDiagnosticServiceCapabilities : CIM_DiagnosticServiceCapabilities {

      [Description ( 
          "This property is used by a provider to define whether or "
          "not the client can specify the seed for the tests that "
          "generate a random number sequence for testing. If True, "
          "then the provider uses the value of "
          "CIM_OpticalDriveDiagnosticSettingData.Seed to initiate "
          "the random number sequence generation." ), 
       ModelCorrespondence { 
          "CIM_OpticalDriveDiagnosticSettingData.Seed" }]
   boolean SeedSupported;

      [Description ( 
          "This array property is used by a provider to define the "
          "list of data patterns supported by the test. A data "
          "pattern is a string interpreted as a 16-digit hex value. "
          "For example, a data pattern of all ones would be "
          "0xFFFFFFFFFFFFFFFF while alternating ones and zeros "
          "would be 0x5555555555555555 or 0xAAAAAAAAAAAAAAAA . The "
          "pattern will be repeated as necessary to fill the "
          "specified data buffer." ), 
       ModelCorrespondence { 
          "CIM_OpticalDriveDiagnosticSettingData.DataPatterns" }]
   string DataPatternsSupported[];


};
