// Copyright (c) 2012 DMTF.  All rights reserved.
   [Experimental, Version ( "2.31.0" ), 
    UMLPackagePath ( "CIM::System::Diagnostics" ), 
    Description ( 
       "This class specializes CIM_DiagnosticTest to define the tests "
       "specific to Optical Disk Drives" )]
class CIM_OpticalDriveDiagnosticTest : CIM_DiagnosticTest {

      [Description ( 
          "The descriptions for each Optical Disk Drive test type "
          "are below: * \"Media Detection\" (value=2) is specified "
          "for the test that verifies that the Optical Disk Drive "
          "can properly detect whether or not media is present. "
          "CIM_DiagnosticTest.TestTypes shall be set to Functional "
          "(value=2). * \"Mechanical Tray\" (value=3) is specified "
          "for the test that verifies that the physical components "
          "of the optical device tray are operating properly. "
          "CIM_DiagnosticTest.TestTypes shall be set to Functional "
          "(value=2). * \"Activity Indicator\" (value=3) is "
          "specified for the test that verifies that the Activity "
          "Indicator LED operates properly. "
          "CIM_DiagnosticTest.TestTypes shall be set to Functional "
          "(value=2). * \"Transfer Rate\" (value=5) is specified "
          "for the test that verifies that the Optical Disk Drive "
          "operates properly when performing I/O operations at all "
          "supported data transfer rates. "
          "CIM_DiagnosticTest.TestTypes shall be set to Functional "
          "(value=2). * \"Sequential Internal Verify\" (value=6) is "
          "specified for the test that verifies the ability to "
          "perform read and verify operations in sequential order "
          "to each sector of the media. "
          "CIM_DiagnosticTest.TestTypes shall be set to Functional "
          "(value=2). * \"Sequential Read\" (value=7) is specified "
          "for the test that performs a read operation in "
          "sequential order from all sectors of the media.. "
          "CIM_DiagnosticTest.TestTypes shall be set to Functional "
          "(value=2) and Medai Verify (value=6). * \"Sequential "
          "Seek\" (value=8) is specified for the test that performs "
          "a seek operation in sequential order to all sectors of "
          "the media. CIM_DiagnosticTest.TestTypes shall be set to "
          "Functional (value=2) and Medai Verify (value=6). * "
          "\"Sequential Write\" (value=9) is specified for the test "
          "that performs a write operation in sequential order to "
          "all sectors of the media and then verifies that the data "
          "is written accurately. CIM_DiagnosticTest.TestTypes "
          "shall be set to Functional (value=2) and Medai Verify "
          "(value=6). * \"Random Read\" (value=10) is specified for "
          "the test that performs a read operation in random order "
          "from selected sectors of the media. "
          "CIM_DiagnosticTest.TestTypes shall be set to Functional "
          "(value=2) and Medai Verify (value=6). * \"Random Seek\" "
          "(value=11) is specified for the test that performs a "
          "seek operation in random order from selected sectors of "
          "the media. CIM_DiagnosticTest.TestTypes shall be set to "
          "Functional (value=2) and Medai Verify (value=6). * "
          "\"Status\" (value=12) is specified for the test that "
          "verifies that the Optical Disk Drive is ready to be "
          "tested. CIM_DiagnosticTest.TestTypes shall be set to "
          "Health Check (value=4). * \"Reset Drive\" (value=13) is "
          "specified for the test that verifies that the Optical "
          "Disk Drive properly responds to a Reset command. "
          "CIM_DiagnosticTest.TestTypes shall be set to Functional "
          "(value=2). * \"System Inteface\" (value=14) is specified "
          "for the test that verifies that all system interface for "
          "cables and connectors are working properly. "
          "CIM_DiagnosticTest.TestTypes shall be set to Functional "
          "(value=2). * \"Load / Eject\" (value=15) is specified "
          "for the test that verifies that the Optical Disk Drive "
          "properly responds to a Load/Eject command. "
          "CIM_DiagnosticTest.TestTypes shall be set to Functional "
          "(value=2)." ), 
       ValueMap { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", 
          "10", "11", "12", "13", "14", "15", "..", "0x8000.." }, 
       Values { "Unknown", "Other", "Media Detection", 
          "Mechanical Tray", "Activity Indicator", "Transfer Rate", 
          "Sequential Internal Verify", "Sequential Read", 
          "Sequential Seek", "Sequential Write", "Random Read", 
          "Random Seek", "Status", "Reset Drive", "System Inteface", 
          "Load/Eject", "Vendor Reserved", "DMTF Reserved" }, 
       ModelCorrespondence { 
          "CIM_OpticalDriveDiagnosticTest.OtherOpticalDriveTestType" }]
   uint16 OpticalDriveTestType;

      [Description ( 
          "A string that describes the test when the "
          "OpticalDriveTestType property is set to 1 (\"Other\"). "
          "This property must be set to null when "
          "OpticalDriveTestType is any value other than 1." ), 
       ModelCorrespondence { 
          "CIM_OpticalDriveDiagnosticTest.OpticalDriveTestType" }]
   string OtherOpticalDriveTestType;


};
