// Copyright (c) 2011 DMTF.  All rights reserved.
   [Experimental, Version ( "2.31.0" ), 
    UMLPackagePath ( "CIM::System::Diagnostics" ), 
    Description ( 
       "This class defines the permissible settings that can be used "
       "for EthenetNIC diagnostic tests." )]
class CIM_EthernetNICDiagnosticServiceCapabilities : CIM_DiagnosticServiceCapabilities {

      [Description ( 
          "This array property is used by a provider to specify the "
          "list of link speeds supported by some EthernetNIC tests. "
          "The client should only select one of these values." ), 
       ModelCorrespondence { 
          "CIM_EthernetNICDiagnosticSettingData.LinkSpeeds" }, 
       PUnit ( "bit / second * 10^6" )]
   uint64 LinkSpeedsSupported[];

      [Description ( 
          "This array property is used by a provider to specify the "
          "list of of layers (e.g. PHY, MAC, etc) supported by some "
          "EthernetNIC tests. The client should only select one of "
          "these values." ), 
       ValueMap { "1", "2", "3" }, 
       Values { "Other", "PHY Layer", "MAC Layer" }, 
       ModelCorrespondence { 
          "CIM_EthernetNICDiagnosticSettingData.LoopbackLayers", 
          "CIM_EthernetNICDiagnosticServiceCapabilities.OtherLoopbackLayersSupported" }]
   uint16 LoopbackLayersSupported[];

      [Description ( 
          "This array property is used by a provider to specify the "
          "layers supported by the test when LoopbackLayers has "
          "value set to 1 (\"Other\"). The client should only "
          "select one of these values." ), 
       ModelCorrespondence { 
          "CIM_EthernetNICDiagnosticServiceCapabilities.LoopbackLayersSupported", 
          "CIM_EthernetNICDiagnosticSettingData.OtherLoopbackLayers" }]
   string OtherLoopbackLayersSupported[];

      [Description ( 
          "This array property is used by a provider to specify the "
          "list of packet sizes supported by some Ethernet NIC "
          "tests. The client should only select one of these "
          "values." ), 
       ModelCorrespondence { 
          "CIM_EthernetNICDiagnosticSettingData.PacketSizes" }, 
       PUnit ( "Byte" )]
   uint16 PacketSizesSupported[];


};
