// Copyright (c) 2012 DMTF.  All rights reserved.
   [Experimental, Version ( "2.31.0" ), 
    UMLPackagePath ( "CIM::System::Diagnostics" ), 
    Description ( 
       "This class defines the permissible settings that can be used "
       "for disk drive diagnostic tests." )]
class CIM_DiskDriveDiagnosticServiceCapabilities : CIM_DiagnosticServiceCapabilities {

      [Description ( 
          "This property is used by a provider to define whether or "
          "not the client can specify start and end disk sectors "
          "for the region." ), 
       ModelCorrespondence { 
          "CIM_DiskDriveDiagnosticSettingData.LBAStart", 
          "CIM_DiskDriveDiagnosticSettingData.LBAEnd" }]
   boolean Region;

      [Description ( 
          "This property is used by a provider to define whether or "
          "not the client can specify the seed for the tests that "
          "generate a random number sequence for testing." ), 
       ModelCorrespondence { 
          "CIM_DiskDriveDiagnosticSettingData.Seed" }]
   boolean Seed;

      [Description ( 
          "This array property is used by a provider to define the "
          "list of data sizes supported by the test." ), 
       ModelCorrespondence { 
          "CIM_DiskDriveDiagnosticSettingData.DataSizes" }, 
       PUnit ( "Bytes" )]
   uint64 DataSizes[];

      [Description ( 
          "This array property is used by a provider to define the "
          "list of data patterns supported by the test. A data "
          "pattern is a string interpreted as a 16-digit hex value. "
          "For example, a data pattern of all ones would be "
          "FFFFFFFFFFFFFFFF while alternating ones and zeros would "
          "be 5555555555555555 or AAAAAAAAAAAAAAAA . The pattern "
          "will be repeated as necessary to fill the specified data "
          "buffer." ), 
       ModelCorrespondence { 
          "CIM_DiskDriveDiagnosticSettingData.DataPatterns" }]
   string DataPatterns[];


};
