// Copyright (c) 2013 DMTF.  All rights reserved.
   [Association, Experimental, Version ( "2.40.0" ), 
    UMLPackagePath ( "CIM::System::FileServices" ), 
    Description ( 
       "CIM_SAPAvailableForFileShare conveys the semantics of a "
       "Service Access Point that is available for a ManagedElement. "
       "When CIM_SAPAvailableForElement is not instantiated, then the "
       "SAP is assumed to be generally available. If instantiated, the "
       "SAP is available only for the associated ManagedElements. For "
       "example, a device might provide management access through a "
       "URL. This association allows the URL to be advertised for the "
       "device." )]
class CIM_SAPAvailableForFileShare : CIM_SAPAvailableForElement {

      [Key, Override ( "ManagedElement" ), 
       Description ( "The FileShare for which the SAP is available." )]
   CIM_FileShare REF ManagedElement;


};
