// Copyright (c) 2013 DMTF.  All rights reserved.
   [Experimental, Version ( "2.37.0" ), 
    UMLPackagePath ( "CIM::System::FileServerServices" ), 
    Description ( 
       "The CIFSSettingData is a derived class of Settingdata that "
       "specifies CIFS specific properties for a Fileserver." )]
class CIM_CIFSSettingData : CIM_SettingData {

      [Description ( 
          "True indicates that CIFS is enabled for a FileServer. "
          "False indicates CIFS is disabled." )]
   boolean Enabled;

      [Description ( 
          "The charset that will be used by a Fileserver for CIFS "
          "processing. The default is Standard-ASCII." ), 
       ValueMap { "0", "1", "2", "..", "0x8000.." }, 
       Values { "Standard-ASCII", "IBM-437", "IBM-480", 
          "DMTF Reserved", "Vendor Defined" }]
   uint16 Charset = 0;

      [Description ( 
          "True indicates that only TCP transport connections are "
          "allowed. False indicates both TCP and Netbios transport "
          "connections are allowed. The default is to allow both "
          "TCP and Netbios." )]
   boolean UseTCPOnly = false;

      [Description ( "TThe NetBIOS name of the FileServer" )]
   string NETBIOSName;

      [Description ( 
          "An array of IP Addresses of Windows Internet Name "
          "Servers. The address type can be either IP4 or IP6." )]
   string WINSIP[];

      [Description ( 
          "Name of CIFS domain to which the File Server is joined. "
          "Represents either the NTLM domain or the ActiveDirectory "
          "domain." )]
   string AuthenticationDomain;

      [Description ( 
          "Specifies if authentication is to be performed against "
          "NTLM or ActiveDirectory domains. Valid values are NTLM "
          "or ActiveDirectory." ), 
       ValueMap { "0", "1" }, 
       Values { "NTLM", "Active Directory" }]
   uint8 AuthenticationMode;

      [Description ( 
          "Determines how ActiveDirectory authentication is "
          "performed. True indicates that ActiveDirectory "
          "authentication will use Kerberos. False indicates not to "
          "limit authentication to Kerberos only." )]
   boolean UseKerberos;

      [Description ( 
          "True indicates that CIFS opportunistic locking should be "
          "performed False indicates to not use oportunistic "
          "locking." )]
   boolean UseOpportunisticLocking;

      [Description ( 
          "This boolean determines if CIFS clients are allowed to "
          "connect if they use SMB signing for security. True "
          "indicates that CIFS clients are required to use SMB "
          "signing. False indicates that clients do not have to use "
          "SMB signing." )]
   boolean SMBSigningOnly;

      [Description ( 
          "This boolean dictates if the FileServer joins the CIFS "
          "Domain Controller anonymously or if a user and password "
          "are required. True indicates to join anonymously. False "
          "indicates to use the DomainControllerUser and "
          "DomainControllerPassword to join." )]
   boolean ClientsConnectAnonymously;

      [Description ( 
          "This boolean dictates if the FileServer joins the CIFS "
          "Domain Controller anonymously or if a user and password "
          "are required. True indicates to join anonymously. False "
          "indicates to use the DomainControllerUser and "
          "DomainControllerPassword to join." )]
   boolean JoinDomainAnonymously;

      [Description ( 
          "User name to use when the Fileserver joins the CIFS "
          "Domain Controller." )]
   string DomainControllerUser;

      [Description ( 
          "Password to use when the Fileserver joins the CIFS "
          "Domain Controller." )]
   string DomainControllerPassword;

      [Description ( "Name of the CIFS Domain Controller." )]
   string CIFSDomainController;

      [Description ( 
          "This property applies to CIFS/SMB shares only. If it is "
          "true, it means that \"Continuous Availability\" is "
          "supported for CIFS shares. Continuous Availability (CA) "
          "- Client/Server mediated recovery from network and "
          "server failure with application transparency. Like "
          "Multi-Channel IO, this feature is somewhat analogous to "
          "capabilities available in NFSv4." )]
   boolean CASupported;

      [Description ( 
          "This property applies to CIFS/SMB protocol only. If it "
          "is true, it means that \"Multi-Channel\" feature is "
          "supported for CIFS/SMB. Multi-Channel (MPIO) - Provides "
          "the ability to access multiple Ethernet links as a "
          "logical pool supporting multiple SMB sessions and "
          "providing native bandwidth aggregation, link failover, "
          "MPIO intelligence. This feature enables the use of "
          "multiple physical network interfaces in an SMB 2.2 "
          "client and server. This enhancement in SMB 2.2 provides "
          "capabilities analogous to those currently available in "
          "NFSv4." )]
   boolean MultiChannelSupported;

      [Description ( 
          "An array of strings listing the versions of the CIFS "
          "file sharing protocol supported by the File Server." ), 
       ModelCorrespondence { 
          "CIM_ExportedFileShareSetting.ProtocolVersions", 
          "CIM_ExportedFileShareCapabilities.FileSharingProtocol" }]
   string ProtocolVersions[];


};
