// Copyright (c) 2013 DMTF.  All rights reserved.
   [Experimental, Version ( "2.38.0" ), 
    UMLPackagePath ( "CIM::System::FileStatistics" ), 
    Description ( 
       "Instances of this class define a list of supported or desired "
       "properties of FileSystemStatisticalData instances. In the case "
       "where a FileSystemStatisticsManifest instance is a member of a "
       "FileSystemStatisticsManifestCollection used in a "
       "FileSystemStatisticsService.GetStatisticsCollection request, "
       "for each of the boolean \"include\" properties set to true in "
       "that FileSystemStatisticsManifest, the corresponding "
       "FileSystemStatisticalData property will be included, if "
       "available, in the statistics returned for "
       "FileSystemStatisticalData instances whose ElementType matches "
       "the ElementType of the FileSystemStatisticsManifest." )]
class CIM_FileSystemStatisticsManifest : CIM_ManagedElement {

      [Key, Override ( "InstanceID" ), 
       Description ( 
          "Within the scope of the instantiating Namespace, "
          "InstanceID opaquely and uniquely identifies an instance "
          "of this class. To ensure uniqueness within the "
          "NameSpace, the value of InstanceID should be constructed "
          "using the following \"preferred\" algorithm: \n"
          "<OrgID>:<LocalID> \n"
          "Where <OrgID> and <LocalID> are separated by a colon "
          "(:), and where <OrgID> must include a copyrighted, "
          "trademarked, or otherwise unique name that is owned by "
          "the business entity that is creating or defining the "
          "InstanceID or that is a registered ID assigned to the "
          "business entity by a recognized global authority. (This "
          "requirement is similar to the <Schema Name>_<Class Name> "
          "structure of Schema class names.) In addition, to ensure "
          "uniqueness, <OrgID> must not contain a colon (:). When "
          "using this algorithm, the first colon to appear in "
          "InstanceID must appear between <OrgID> and <LocalID>. \n"
          "<LocalID> is chosen by the business entity and should "
          "not be reused to identify different underlying "
          "(real-world) elements. If the above \"preferred\" "
          "algorithm is not used, the defining entity must assure "
          "that the resulting InstanceID is not reused across any "
          "InstanceIDs produced by this or other providers for the "
          "NameSpace of this instance. \n"
          "For DMTF-defined instances, the \"preferred\" algorithm "
          "must be used with the <OrgID> set to CIM." )]
   string InstanceID;

      [Description ( 
          "Determines the type of element that this "
          "FileSystemStatisticsManifest can be applied to (e.g., "
          "during a GetStatisticsCollection request). This is used "
          "when the same set of statistical metrics is calculated "
          "for several types of elements. In this way, a single "
          "FileSystemStatisticsManifest instance can be used to "
          "filter all the StatisticalData instances that contain "
          "metrics for the same type of element in a "
          "StatisticsCollection. If used, a subclass should "
          "override this property to specify the element types "
          "supported by that class, preferably through ValueMap and "
          "Values qualifiers to allow clients to programmatically "
          "retrieve those supported types." ), 
       ValueMap { "1", "102", "103", "104", "..", "0x8000.." }, 
       Values { "Other", "Local Filesystem", "Exported File Share", 
          "Exporting Port", "DMTF Reserved", "Vendor Specific" }, 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.ElementType" }]
   uint16 ElementType;

      [Description ( 
          "A string describing the type of element when the "
          "ElementType property of this class (or any of its "
          "subclasses) is set to 1 (i.e., \"Other\"). This property "
          "should be set to NULL when the ElementType property is "
          "any value other than 1." ), 
       MaxLen ( 64 ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.OtherElementTypeDescription" }]
   string OtherElementTypeDescription;

      [Description ( 
          "Indicates whether or not the Statistics property of "
          "StatisticsService.GetStatisticsCollection method will "
          "include the time at time when statistics for this "
          "FileSystemStatisticsManifest were first captured." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.StartStatisticTime" }]
   boolean IncludeStartStatisticTime = false;

      [Description ( 
          "Indicates whether or not the Statistics property of "
          "StatisticsService.GetStatisticsCollection method will "
          "include the time when statistics for this "
          "FileSystemStatisticsManifest were last captured." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.StatisticTime" }]
   boolean IncludeStatisticTime = false;

      [Description ( 
          "Whether to include in a filter for a metered element the "
          "cumulative count of file I/O operations for that "
          "element, including metadata I/O operations." ), 
       ModelCorrespondence { "CIM_FileSystemStatisticalData.TotalIOs" }]
   boolean IncludeTotalIOs = false;

      [Description ( 
          "Whether to include in a filter for a metered element the "
          "cumulative count of bytes transferred for all of the "
          "file I/O operations for the element, as defined in the "
          "\"TotalIOs\" property." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.TotalBytesTransferred" }]
   boolean IncludeTotalBytesTransferred = false;

      [Description ( 
          "Whether to include in a filter for a metered element the "
          "cumulative count of all file I/O operations that were "
          "directed to that element and that performed a transfer "
          "of data from the contents of a file." ), 
       ModelCorrespondence { "CIM_FileSystemStatisticalData.ReadIOs" }]
   boolean IncludeReadIOs = false;

      [Description ( 
          "Whether to include in a filter for a metered element the "
          "cumulative count of all file I/O operations that were "
          "directed to that element and that performed a transfer "
          "of data to the contents of a file." ), 
       ModelCorrespondence { "CIM_FileSystemStatisticalData.WriteIOs" }]
   boolean IncludeWriteIOs = false;

      [Description ( 
          "Whether to include in a filter for a metered element the "
          "cumulative count of all file I/O operations that were "
          "directed to that element and that did not perform a "
          "transfer of data either to or from the contents of a "
          "file. This count excludes metadata I/O operations (both "
          "read and write)." ), 
       ModelCorrespondence { "CIM_FileSystemStatisticalData.OtherIOs" }]
   boolean IncludeOtherIOs = false;

      [Description ( 
          "Whether to include in a filter for a metered element the "
          "cumulative count of all file I/O operations that were "
          "directed to that element and that performed a read "
          "transfer of metadata." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.MetadataReadIOs" }]
   boolean IncludeMetadataReadIOs = false;

      [Description ( 
          "Whether to include in a filter for a metered element the "
          "cumulative count of all file I/O operations that were "
          "directed to that element and that performed a write "
          "transfer of metadata." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.MetadataWriteIOs" }]
   boolean IncludeMetadataWriteIOs = false;

      [Description ( 
          "Whether to include in a filter for a metered element the "
          "cumulative elapsed I/O operation time (number of "
          "ClockTickIntervals) for all file I/O operations for that "
          "element as defined in \"Total I/Os\"." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.TotalIOTimeCounter" }]
   boolean IncludeTotalIOTimeCounter = false;

      [Description ( 
          "Whether to include in a filter for a metered element the "
          "cumulative elapsed idle time for that element." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.TotalIdleTimeCounter" }]
   boolean IncludeTotalIdleTimeCounter = false;

      [Description ( 
          "Whether to include in a filter for a metered element the "
          "cumulative elapsed I/O operation time for all Read I/O "
          "operations (as defined by the \"ReadIOs\" property) for "
          "that element." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.ReadIOTimeCounter" }]
   boolean IncludeReadIOTimeCounter = false;

      [Description ( 
          "Whether to include in a filter for a metered element the "
          "cumulative count of bytes transferred by all Read I/O "
          "operations (as defined by the \"ReadIOs\" property) for "
          "that element." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.BytesRead" }]
   boolean IncludeBytesRead = false;

      [Description ( 
          "Whether to include in a filter for a metered element the "
          "cumulative elapsed I/O operation time for all Write I/O "
          "operations (as defined by the \"WriteIOs\" property) for "
          "that element." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.WriteIOTimeCounter" }]
   boolean IncludeWriteIOTimeCounter = false;

      [Description ( 
          "Whether to include in a filter for a metered element the "
          "cumulative count of bytes transferred by all Write I/O "
          "operations (as defined by the \"WriteIOs\" property) for "
          "that element." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.BytesWritten" }]
   boolean IncludeBytesWritten = false;

      [Description ( 
          "Whether to include in a filter for a metered element the "
          "cumulative count of metadata bytes read by all Metadata "
          "read I/O operations (as defined by the \"MetadataReadIOs\" "
          "property) for that element." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.MetadataBytesRead" }]
   boolean IncludeMetadataBytesRead = false;

      [Description ( 
          "Whether to include in a filter for a metered element the "
          "cumulative count of metadata bytes read by all Metadata "
          "write I/O operations (as defined by the "
          "\"MetadataWriteIOs\" property) for that element." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.MetadataBytesWritten" }]
   boolean IncludeMetadataBytesWritten = false;

      [Description ( 
          "Whether to include in a filter for a metered element the "
          "percentage of total opens for which clients requested "
          "durability for that element." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.PercentDurableOpens" }]
   boolean IncludePercentDurableOpens = false;

      [Description ( 
          "Whether to include in a filter for a metered element the "
          "percentage of total opens for which clients requested "
          "resiliency for that element." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.PercentResilientOpens" }]
   boolean IncludePercentResilientOpens = false;

      [Description ( 
          "Whether to include in a filter for a metered element the "
          "percentage of total handles for which clients requested "
          "persistency for that element." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.PercentPersistentOpens" }]
   boolean IncludePercentPersistentOpens = false;

      [Description ( 
          "Whether to include in a filter for a share the average "
          "number of seconds that elapse between the time at which "
          "a read request to that share is received and the time at "
          "which the SMB2 File Server sends the corresponding "
          "response." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.AverageReadResponseTime" }]
   boolean IncludeAverageReadResponseTime = false;

      [Description ( 
          "Whether to include in a filter for a share the average "
          "number of seconds that elapse between the time at which "
          "a write request to that share is received and the time "
          "at which the SMB2 File Server sends the corresponding "
          "response" ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.AverageWriteResponseTime" }]
   boolean IncludeAverageWriteResponseTime = false;

      [Description ( 
          "Whether to include in a filter for a share the average "
          "number of seconds that elapse between the time at which "
          "the SMB2 File Server receives a request for that share "
          "and the time at which the SMB2 File Server sends the "
          "corresponding response." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.AverageRequestResponseTime" }]
   boolean IncludeAverageRequestResponseTime = false;

      [Description ( 
          "Whether to include in a filter for a share the rate, in "
          "seconds, at which data is being written to that share." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.BytesReadPerSec" }]
   boolean IncludeBytesReadPerSec = false;

      [Description ( 
          "Whether to include in a filter for a share the number of "
          "bytes that have been received for requests related to "
          "that share." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.TotalBytesReceived" }]
   boolean IncludeTotalBytesReceived = false;

      [Description ( 
          "Whether to include in a filter for a share the rate at "
          "which bytes are being received for requests related to "
          "that share." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.BytesReceivedPerSec" }]
   boolean IncludeBytesReceivedPerSec = false;

      [Description ( 
          "Whether to include in a filter for a share the number of "
          "bytes that have been sent by the SMB2 File Server "
          "related to that share to its clients since the server "
          "started. This value includes both data bytes and "
          "protocol bytes for that share." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.TotalBytesSent" }]
   boolean IncludeTotalBytesSent = false;

      [Description ( 
          "Whether to include in a filter for a share the rate, in "
          "seconds, at which bytes are being sent from the SMB2 "
          "File Server related to that share to its clients. This "
          "value includes both data bytes and protocol bytes for "
          "that share." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.BytesSentPerSec" }]
   boolean IncludeBytesSentPerSec = false;

      [Description ( 
          "Whether to include in a filter for a share the sum of "
          "bytes transferred/sec related to that share." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.BytesTranferredPerSec" }]
   boolean IncludeBytesTranferredPerSec = false;

      [Description ( 
          "Whether to include in a filter for a share the rate, in "
          "seconds, at which data is being written to that share." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.BytesWrittenPerSec" }]
   boolean IncludeBytesWrittenPerSec = false;

      [Description ( 
          "Whether to include in a filter for a share the rate, in "
          "seconds, at which files are being opened for the SMB2 "
          "File Server/\'s clients on that share." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.FilesOpenedPerSec" }]
   boolean IncludeFilesOpenedPerSec = false;

      [Description ( 
          "Whether to include in a filter for a share the number of "
          "files that have been opened by the SMB2 File Server on "
          "behalf of its clients on that share since the server "
          "started." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.TotalOpenFileCount" }]
   boolean IncludeTotalOpenFileCount = false;

      [Description ( 
          "Whether to include in a filter for a share the number of "
          "requests related to that share that are waiting to be "
          "processed by the SMB2 File Server." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.CurrentPendingRequests" }]
   boolean IncludeCurrentPendingRequests = false;

      [Description ( 
          "Whether to include in a filter for a share the Read "
          "requests processed/sec related to that share." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.ReadRequestsProcessedPerSec" }]
   boolean IncludeReadRequestsProcessedPerSec = false;

      [Description ( 
          "Whether to include in a filter for a share the number of "
          "requests that have been received for that share." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.TotalRequestsReceived" }]
   boolean IncludeTotalRequestsReceived = false;

      [Description ( 
          "Whether to include in a filter for a share the rate at "
          "which requests are being received for that share." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.RequestsReceivedPerSec" }]
   boolean IncludeRequestsReceivedPerSec = false;

      [Description ( 
          "Whether to include in a filter for a share the number of "
          "durable opens on that share that have been recovered "
          "after a temporary network disconnect since the SMB2 File "
          "Server started." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.TotalDurableHandleReopenCount" }]
   boolean IncludeTotalDurableHandleReopenCount = false;

      [Description ( 
          "Whether to include in a filter for a share the number of "
          "durable opens on that share that could not be recovered "
          "after a temporary network disconnect since the SMB2 File "
          "Server Started." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.TotalFailedDurableHandleReopenCount" }]
   boolean IncludeTotalFailedDurableHandleReopenCount = false;

      [Description ( 
          "Whether to include in a filter for a share the number of "
          "resilient opens on that share that could not be "
          "recovered after a temporary network disconnect since the "
          "SMB2 File Server Started." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.TotalFailedResilientHandleReopenCount" }]
   boolean IncludeTotalFailedResilientHandleReopenCount = false;

      [Description ( 
          "Whether to include in a filter for a share the number of "
          "file handles that are currently open in that share." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.CurrentOpenFileCount" }]
   boolean IncludeCurrentOpenFileCount = false;

      [Description ( 
          "Whether to include in a filter for a share the number of "
          "resilient opens on that share that have been recovered "
          "after a temporary network disconnect since the SMB2 File "
          "Server started." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.TotalResilientHandleReopenCount" }]
   boolean IncludeTotalResilientHandleReopenCount = false;

      [Description ( 
          "Whether to include in a filter for a share the number of "
          "persistent opens on that share that have been recovered "
          "after a temporary network disconnect since the SMB2 File "
          "Server started." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.TotalPersistentHandleReopenCount" }]
   boolean IncludeTotalPersistentHandleReopenCount = false;

      [Description ( 
          "Whether to include in a filter for a share the number of "
          "persistent opens on that share that could not be "
          "recovered after a temporary network disconnect since the "
          "SMB2 File Server Started." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.TotalFailedPersistentHandleReopenCount" }]
   boolean IncludeTotalFailedPersistentHandleReopenCount = false;

      [Description ( 
          "Whether to include in a filter for a share the number of "
          "tree connects to that share." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.TreeConnectCount" }]
   boolean IncludeTreeConnectCount = false;

      [Description ( 
          "Whether to include in a filter for a share the write "
          "requests processed/sec related to that share." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.WriteRequestsProcessedPerSec" }]
   boolean IncludeWriteRequestsProcessedPerSec = false;

      [Description ( 
          "Whether to include in a filter for a share the total "
          "number of metadata requests received related to that "
          "share." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.TotalMetadataRequestsReceived" }]
   boolean IncludeTotalMetadataRequestsReceived = false;

      [Description ( 
          "Whether to include in a filter for a share the rate, in "
          "seconds, at which metadata requests are being sent to "
          "that share." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.MetadataRequestsReceivedPerSec" }]
   boolean IncludeMetadataRequestsReceivedPerSec = false;

      [Description ( 
          "Whether to include in a filter for a share the average "
          "number of seconds that elapse between the time at which "
          "a read or write request to that share is received and "
          "the time at which the SMB2 File Server processes the "
          "request." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.AverageTimePerDataRequest" }]
   boolean IncludeAverageTimePerDataRequest = false;

      [Description ( 
          "Whether to include in a filter for a share the average "
          "number of bytes per read or write request." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.AverageBytesPerDataRequest" }]
   boolean IncludeAverageBytesPerDataRequest = false;

      [Description ( 
          "Whether to include in a filter for a share the average "
          "number of bytes per read request." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.AverageBytesPerReadRequest" }]
   boolean IncludeAverageBytesPerReadRequest = false;

      [Description ( 
          "Whether to include in a filter for a share the average "
          "number of bytes per write request." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.AverageBytesPerWriteRequest" }]
   boolean IncludeAverageBytesPerWriteRequest = false;

      [Description ( 
          "Whether to include in a filter for a share the average "
          "number of read requests that were queued for that share." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.AverageReadQueueLength" }]
   boolean IncludeAverageReadQueueLength = false;

      [Description ( 
          "Whether to include in a filter for a share the average "
          "number of write requests that were queued for that "
          "share." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.AverageWriteQueueLength" }]
   boolean IncludeAverageWriteQueueLength = false;

      [Description ( 
          "Whether to include in a filter for a share the average "
          "number of read and write requests that were queued for "
          "that share." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.AverageDataQueueLength" }]
   boolean IncludeAverageDataQueueLength = false;

      [Description ( 
          "Whether to include in a filter for a share the rate, in "
          "seconds, at which data is being written to or read from "
          "that share." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.DataBytesPerSec" }]
   boolean IncludeDataBytesPerSec = false;

      [Description ( 
          "Whether to include in a filter for a share the rate, in "
          "seconds, at which read or write requests are received "
          "for that share." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.DataRequestsPerSec" }]
   boolean IncludeDataRequestsPerSec = false;

      [Description ( 
          "Whether to include in a filter for a share the current "
          "number of read or write requests outstanding on that "
          "share." ), 
       ModelCorrespondence { 
          "CIM_FileSystemStatisticalData.CurrentDataQueueLength" }]
   boolean IncludeCurrentDataQueueLength = false;


};
