#!/bin/bash

#
# The following set of commands tests the new Classes configured through the
# Test provider interface. If the ProviderModule registers one or more test
# providers and every provider has in turn multiple classes within itself then
# the following set should be run for each and every class of all the providers.

namespace="root/SampleProvider"


#enumerateinstances
CLI -v ei -n $namespace ExceptionsTestClass 2>&1 | tee CLI.output

#enumerateclasses
CLI -v ec -n $namespace ExceptionsTestClass 2>&1 | tee -a CLI.output

#enumerateinstancenames
CLI -v ni -n $namespace ExceptionsTestClass 2>&1 | tee -a CLI.output

#enumerateclassnames
CLI -v nc -n $namespace ExceptionsTestClass 2>&1 | tee -a CLI.output

#getclass
CLI -v gc -n $namespace ExceptionsTestClass 2>&1 | tee -a CLI.output

#getinstance
CLI -v gi -n $namespace ExceptionsTestClass 2>&1 | tee -a CLI.output
