#!/bin/bash

# Running the client commands after rebuilding the sources and re-registering
# the Test providers (by running cimmof and cimmofl).
# If the classes are already present in cimv2 and PG_InterOp then first both
# the classes are removed and then re-registered.
# Restart the cimserver.

# Compile the TestProvider Code and register the static and dynamic instances
# of all the Classes defined in the MOFs present in this directory

make clean
make
make repository

make regprovider

./clitests
