// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_StartedUoW
// ==================================================================
   [Association, UMLPackagePath ( "CIM::Metrics::UnitOfWork" ),
    Version ( "2.6.0" ), Description (
       "This association links a UnitOfWork (which is a 'started' "
       "transaction) to its Definition.")]
class CIM_StartedUoW : CIM_Dependency {

      [Override ( "Antecedent" ), Min ( 1 ), Max ( 1 ), Description (
          "The Definition object for the UnitOfWork.")]
   CIM_UnitOfWorkDefinition REF Antecedent;

      [Override ( "Dependent" ), Weak, Description (
          "An instance of a UnitOfWork that has started executing.")]
   CIM_UnitOfWork REF Dependent;
};
