//%LICENSE////////////////////////////////////////////////////////////////
//
// Licensed to The Open Group (TOG) under one or more contributor license
// agreements.  Refer to the OpenPegasusNOTICE.txt file distributed with
// this work for additional information regarding copyright ownership.
// Each contributor licenses this file to you under the OpenPegasus Open
// Source License; you may not use this file except in compliance with the
// License.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included
// in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
// CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
// SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//
//////////////////////////////////////////////////////////////////////////
// ===================================================================
// Title      : PG_ConfigSetting MOF
// Filename   : PG_ConfigSetting20.mof
// Version    : 1.0
// Date       : 06/28/2001
// Description: This MOF file uses Pegasus convention. It provides definitions
//              for PG_ConfigSetting  (subclassed from CIM_Setting).
//
//====================================================================

// ===================================================================
// PG_ConfigSetting
// ===================================================================
[Version ("2.10.0"), Description (
   "PG_ConfigSetting is a representation of CIMOM specific"
   " configuration properties.")]

class PG_ConfigSetting 
{
    [Key, 
     MaxLen (256), 
     Description (
         "The label by which the Configuration setting object is known.")
    ]
    string        PropertyName;

    [Description ("Default Value")
    ]
    string        DefaultValue;

    [Description ("Current Value")
    ]
    string        CurrentValue;

    [Description ("Planned Value")
    ]
    string        PlannedValue;

    [Description ("Dynamic Property")
    ]
    boolean    DynamicProperty;

    [Description ("Descriptive text about the Property. This is a "
        "preformatted string.") ]
    string      Description;

       [Description (
          "Updates the planned value and current value using the "
          "timeout period.")]
    boolean UpdatePropertyValue(
          [IN,Description (
             "Property Value.")]
      string PropertyValue,
          [IN,Description (
             "Reset value to Default Value.")]
      boolean ResetValue,
          [IN,Description (
             "Set Current Value.")]
      boolean SetCurrentValue,
          [IN,Description (
             "Set Planned Value.")]
      boolean SetPlannedValue,
          [IN,Description (
             "Timeout period in seconds.")]
      uint32 TimeoutPeriod);
};
