//%LICENSE////////////////////////////////////////////////////////////////
//
// Licensed to The Open Group (TOG) under one or more contributor license
// agreements.  Refer to the OpenPegasusNOTICE.txt file distributed with
// this work for additional information regarding copyright ownership.
// Each contributor licenses this file to you under the OpenPegasus Open
// Source License; you may not use this file except in compliance with the
// License.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included
// in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
// CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
// SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//
//////////////////////////////////////////////////////////////////////////

// ===================================================================
// Title      : PG_GeneratedIndicationData MOF
// Filename   : PG_GeneratedIndicationData20.mof
// Version    : 1.0
// Date       : 04/24/2008
// Description: This MOF file defines the PG_ProviderIndicationData class and
//              the PG_SubscriptionIndicationData class.
//              The PG_ProviderIndicationData class provides definitions for
//              PG_ProviderIndicationData which represents generated
//              indications count by an active provider.
//              The PG_SubscriptionIndicationData class provides definitions
//              for PG_SubscriptionIndicationData which represents the number
//              of generated indications by an active provider for each
//              subscription it serves.
//
// ===================================================================

// ===================================================================
// PG_ProviderIndicationData
// ===================================================================
[Version("2.8.0"), Description (
    "PG_ProviderIndicationData is a representation of generated indications "
    "count by an active provider.")]

class PG_ProviderIndicationData
{
        [Key, Propagated ("PG_ProviderModule.Name"),
         Description ("Module name of an active provider.")]
    string ProviderModuleName;

        [Key, Propagated ("PG_Provider.Name"),
         Description ("Name of an active provider.")]
    string ProviderName;

        [Description ("Number of indications generated by this "
             "provider since it became active.")]
    uint32 IndicationCount;

        [Description ("The number of indications generated by this"
             "provider that did not match a subscription.")]
    uint32 OrphanIndicationCount;
};

[Version("2.8.0"), Description (
    "PG_SubscriptionIndicationData represents the number of generated "
    "indications by an active provider for each subscription it serves.")]
class PG_SubscriptionIndicationData
{
        [Key,
         Description ("Name of the filter that defines the criteria and "
             "data of the indications for this subscription. The format is "
             "namespace:filtername where the namespace is the namespace "
             "of filter instance created, and the filtername is the value "
             "of property Name in the filter instance.")]
    string FilterName;

        [Key,
         Description ("Name of the handler that addresses delivery of the "
             "indications for this subscription. The format is "
             "namespace:classname.handlername where namespace is the "
             "namespace of handler instance created, the classname is "
             "the class of the handler instance, and handlername is the "
             "value of property Name in the handler instance.")]
    string HandlerName;

        [Key,
         Description ("Source namespace of this subscription.")]
    string SourceNamespace;

        [Key, Propagated ("PG_ProviderModule.Name"),
         Description ("Module name of an active indication provider "
             "which serves this subscription.")]
    string ProviderModuleName;

        [Key, Propagated ("PG_Provider.Name"),
         Description ("Name of an active indication provider "
             "which serves this subscription.")]
    string ProviderName;

        [Description ("The number of indications generated by this "
             "provider that match this subscription.")]
    uint32 MatchedIndicationCount;
};
