//%LICENSE////////////////////////////////////////////////////////////////
//
// Licensed to The Open Group (TOG) under one or more contributor license
// agreements.  Refer to the OpenPegasusNOTICE.txt file distributed with
// this work for additional information regarding copyright ownership.
// Each contributor licenses this file to you under the OpenPegasus Open
// Source License; you may not use this file except in compliance with the
// License.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included
// in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
// CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
// SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//
//////////////////////////////////////////////////////////////////////////
// ===================================================================
// Title      : PG_ShutdownService MOF
// Filename   : PG_ShutdownService20.mof
// Version    : 1.0
// Date       : 11/09/2001
// Description: This MOF file defines the PG_ShutdownService class.  The
//              PG_ShutdownService class defines the shutdown method serviced 
//              by the ShutdownProvider to shut down CIMOM gracefully.  
//              It is subclassed from CIM_Service.  
//
//====================================================================

// ===================================================================
// PG_ShutdownService    
// ===================================================================
[Version("2.7.0"), Description (
   "PG_ShutdownService is a representation of the Pegasus Shutdown Service")]

class PG_ShutdownService
{
     [Static,
      Description 
         ("Method to shutdown the CIM server. If force is set "
          "to TRUE, the CIM server will be shutdown regardless if there "
          "are outstanding CIM operation requests. The timeout value "
          "is the amount of time in seconds that the CIM Server will "
          "wait for all the outstanding CIM operation requests to complete "
          "before shutting down the CIM server. If the specified timeout "
          "expires and force is FALSE, CIM server will not be shutdown.") ]
           
     Uint32 shutdown( [IN] boolean force, [IN] uint32 timeout);
};
