// Copyright (c) 2005 DMTF.  All rights reserved.
   [Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Event" ), 
    Description ( 
       "CIM_ListenerDestinationLog describes that Indications are "
       "delivered to one or more associated CIM_Logs. The specific "
       "logs are defined using the association, CIM_LogOfIndication." )]
class CIM_ListenerDestinationLog : CIM_ListenerDestination {


};
