// Copyright (c) 2011 DMTF.  All rights reserved.
   [Experimental, Version ( "2.28.0" ), 
    UMLPackagePath ( "CIM::Policy" ), 
    Description ( 
       "CIM_AccessControlPolicyGroup represents a group of access "
       "control policies. The CIM_AccessControlPolicyGroup extends the "
       "CIM_PolicyGroup. and is associated with "
       "CIM_AccessControlPolicy through PolicySetComponent. Through "
       "the CIM_AccessControlPolicyGroupInLogicalElement association, "
       "the CIM_AccessControlPolicyGroup shall be associated with at "
       "least one CIM_LogicalElement instance which represents a "
       "policy repository on a managed system." )]
class CIM_AccessControlPolicyGroup : CIM_PolicyGroup {


};
