// Copyright (c) 2011 DMTF.  All rights reserved.
   [Experimental, Version ( "2.28.0" ), 
    UMLPackagePath ( "CIM::Policy" ), 
    Description ( 
       "CIM_AccessControlServiceSettingData is used to specify the "
       "types of principals and resources supported by a specific "
       "access control service. Using the type information, a system "
       "administrator composes access control policies for the service "
       "from a remote client host. An instance of "
       "CIM_AccessControlService is associated with more than one "
       "instances of the CIM_AccessControlServiceSettingData. A "
       "supported principal type is specified in the "
       "CIM_AccessControlServiceSettingData.PrincipalType property. "
       "For each supported principal type, corresponding supported "
       "resource types are specified in the "
       "CIM_AccessControlServiceSettingData.ResourceType." )]
class CIM_AccessControlServiceSettingData : CIM_SettingData {

      [Experimental, Description ( 
          "PrincipalType indicates a type of principal identifiers "
          "that are referred to by an associated access control "
          "service." ), 
       ValueMap { "1", "2", "3", "..", "0x8000.." }, 
       Values { "Users", "Accounts", "Groups", "DMTF Reserved", 
          "Vendor Reserved" }]
   uint16 PrincipalType;

      [Experimental, Description ( 
          "A string that describes the resource type when a well "
          "defined value is not available and ResourceType is set "
          "to 1 for Other." ), 
       ModelCorrespondence { 
          "CIM_AccessControlServiceSettingData.ResourceType" }]
   string OtherResourceType;

      [Experimental, Description ( 
          "For each PrincipalType, a set of resource types are "
          "defined in the ResourceType. ResourceType indicates the "
          "types of resources that can be targets of access control "
          "by a specific access control service. Access control "
          "policies for an access control service is described with "
          "some resource instances having the specified resource "
          "type." ), 
       ValueMap { "1", "2", "3", "4", "5", "6", "7", "8", "..", 
          "0x8000.." }, 
       Values { "Other", "File System", "Virtual Machine", 
          "RDB Table", "Database", "Table Column", "Resource Pool", 
          "Virtualization", "DMTF Reserved", "Vendor Reserved" }]
   uint16 ResourceType[];


};
