// Copyright (c) 2005 DMTF.  All rights reserved.
   [Abstract, Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::Application::J2eeAppServer" ), 
    Description ( 
       "The CIM_J2eeSessionBean class is a base class that represents "
       "specific types of deployed Session beans." )]
class CIM_J2eeSessionBean : CIM_J2eeEJB {


};
