// Copyright (c) 2005 DMTF.  All rights reserved.
   [Association, Deprecated { "CIM_ElementSettingData", 
       "CIM_CollectionSetting" }, 
    Version ( "2.10.0" ), 
    UMLPackagePath ( "CIM::Core::Settings" ), 
    Description ( 
       "Note: The Configuration class is being deprecated in lieu of "
       "using a ConcreteComponent relationship to indicate a hierarchy "
       "of instances of Setting or SettingData. This relationship "
       "allows the reuse of the collection-to-Setting and "
       "element-to-SettingData associations instead of defining peer "
       "associations specifically for Configurations. \n"
       "Deprecated description: This association relates a "
       "Configuration object to one or more CollectionOfMSEs objects. "
       "The Configuration object represents a certain behavior or a "
       "desired functional state for the associated Collection." )]
class CIM_CollectionConfiguration {

      [Deprecated { "CIM_ElementSettingData.ManagedElement", 
          "CIM_CollectionSetting.Collection" }, 
       Key, Description ( 
          "Note: The use of this element is deprecated. Deprecated "
          "description: The CollectionOfMSEs." )]
   CIM_CollectionOfMSEs REF Collection;

      [Deprecated { "CIM_ElementSettingData.SettingData", 
          "CIM_CollectionSetting.Setting" }, 
       Key, Description ( 
          "Note: The use of this element is deprecated. Deprecated "
          "description: The Configuration object that groups the "
          "Settings and dependencies that are associated with the "
          "Collection." )]
   CIM_Configuration REF Configuration;


};
