//%LICENSE////////////////////////////////////////////////////////////////
//
// Licensed to The Open Group (TOG) under one or more contributor license
// agreements.  Refer to the OpenPegasusNOTICE.txt file distributed with
// this work for additional information regarding copyright ownership.
// Each contributor licenses this file to you under the OpenPegasus Open
// Source License; you may not use this file except in compliance with the
// License.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included
// in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
// CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
// SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//
//////////////////////////////////////////////////////////////////////////

// ==================================================================
// JMPICIMInstance2_TestElement
// ==================================================================
[ Abstract,
  Version ("2.2.0"),
  Description ("JMPICIMInstance2_TestElement is an abstract class that provides a common "
               "superclass (or top of the inheritance tree) for the "
               "non-association classes in the test Schema.")
]
class JMPICIMInstance2_TestElement
{
   [ Key,
     MaxLen (256),
     Description ("CreationClassName indicates the name of the class or the "
                  "subclass used in the creation of an instance. When used "
                  "with the other key properties of this class, this property "
                  "allows all instances of this class and its subclasses to "
                  "be uniquely identified.")
   ]
   string CreationClassName;

   [ Key,
     Description ("An identifier that uniquely identifies each instance "
                  "of the JMPICIMInstance2_TestElement hierarchy.")
   ]
   uint64 InstanceId;
};

// ===================================================================
// JMPICIMInstance2_TestPropertyTypes
// ===================================================================
[ Version ("2.2.0"),
  Description ("JMPICIMInstance2_TestPropertyTypes is a concrete class derived from "
	       "JMPICIMInstance2_TestElement"),
  provider ("JMPICIMInstance2_TestPropertyTypes")
]
class JMPICIMInstance2_TestPropertyTypes : JMPICIMInstance2_TestElement
{
   [ Maxlen (256),
     Description ("a string property of JMPICIMInstance2_TestPropertyTypes")
   ]
   string PropertyString;

   [ Description ("a uint8 property of JMPICIMInstance2_TestPropertyTypes")
   ]
   uint8 PropertyUint8;

   [ Description ("a uint16 property of JMPICIMInstance2_TestPropertyTypes")
   ]
   uint16 PropertyUint16;

   [ Description ("a uint32 property of JMPICIMInstance2_TestPropertyTypes")
   ]
   uint32 PropertyUint32;

   [ Description ("a uint64 property of JMPICIMInstance2_TestPropertyTypes")
   ]
   uint64 PropertyUint64;

   [ Description ("a sint8 property of JMPICIMInstance2_TestPropertyTypes")
   ]
   sint8 PropertySint8;

   [ Description ("a sint16 property of JMPICIMInstance2_TestPropertyTypes")
   ]
   sint16 PropertySint16;

   [ Description ("a sint32 property of JMPICIMInstance2_TestPropertyTypes")
   ]
   sint32 PropertySint32;

   [ Description ("a sint64 property of JMPICIMInstance2_TestPropertyTypes")
   ]
   sint64 PropertySint64;

   [ Description ("a boolean property of JMPICIMInstance2_TestPropertyTypes")
   ]
   boolean PropertyBoolean;

   [ Description ("a real32 property of JMPICIMInstance2_TestPropertyTypes")
   ]
   real32 PropertyReal32;

   [ Description ("a real64 property of JMPICIMInstance2_TestPropertyTypes")
   ]
   real64 PropertyReal64;

   [ Description ("a datetime property of JMPICIMInstance2_TestPropertyTypes")
   ]
   datetime PropertyDatetime;

   [ Description ("a char16 property of JMPICIMInstance2_TestPropertyTypes")
   ]
   char16 PropertyChar16;

   [ Description ("an object property of JMPICIMInstance2_TestPropertyTypes"),
     EmbeddedObject
   ]
   string PropertyObject;

// [ Description ("a reference property of JMPICIMInstance2_TestPropertyTypes")
// ]
// ref PropertyReference;

   [ Description ("an array of uint8s property of JMPICIMInstance2_TestPropertyTypes")
   ]
   uint8 PropertyArrayUint8[];

   [ Description ("an array of uint16s property of JMPICIMInstance2_TestPropertyTypes")
   ]
   uint16 PropertyArrayUint16[];

   [ Description ("an array of uint32s property of JMPICIMInstance2_TestPropertyTypes")
   ]
   uint32 PropertyArrayUint32[];

   [ Description ("an array of uint64s property of JMPICIMInstance2_TestPropertyTypes")
   ]
   uint64 PropertyArrayUint64[];

   [ Description ("an array of sint8s property of JMPICIMInstance2_TestPropertyTypes")
   ]
   sint8 PropertyArraySint8[];

   [ Description ("an array of sint16s property of JMPICIMInstance2_TestPropertyTypes")
   ]
   sint16 PropertyArraySint16[];

   [ Description ("an array of sint32s property of JMPICIMInstance2_TestPropertyTypes")
   ]
   sint32 PropertyArraySint32[];

   [ Description ("an array of sint64s property of JMPICIMInstance2_TestPropertyTypes")
   ]
   sint64 PropertyArraySint64[];

   [ Description ("an array of booleans property of JMPICIMInstance2_TestPropertyTypes")
   ]
   boolean PropertyArrayBoolean[];

   [ Description ("an array of real32s property of JMPICIMInstance2_TestPropertyTypes")
   ]
   real32 PropertyArrayReal32[];

   [ Description ("an array of real64s property of JMPICIMInstance2_TestPropertyTypes")
   ]
   real64 PropertyArrayReal64[];

   [ Description ("an array of datetimes property of JMPICIMInstance2_TestPropertyTypes")
   ]
   datetime PropertyArrayDatetime[];

   [ Description ("an array of char16s property of JMPICIMInstance2_TestPropertyTypes")
   ]
   char16 PropertyArrayChar16[];

   [ Description ("an object property of JMPICIMInstance2_TestPropertyTypes"),
     EmbeddedObject
   ]
   string PropertyArrayObject[];

   [ Description ("a function that returns a string which says hello")
   ]
   String sayHello ();

   [ Description ("a function which tells the provider to allow modifications")
   ]
   boolean enableModifications (boolean fState);

   [ Description ("a function that resets the provider state")
   ]
   boolean resetProvider ();
};
