//%LICENSE////////////////////////////////////////////////////////////////
//
// Licensed to The Open Group (TOG) under one or more contributor license
// agreements.  Refer to the OpenPegasusNOTICE.txt file distributed with
// this work for additional information regarding copyright ownership.
// Each contributor licenses this file to you under the OpenPegasus Open
// Source License; you may not use this file except in compliance with the
// License.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included
// in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
// CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
// SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//
//////////////////////////////////////////////////////////////////////////
#pragma locale ("en_US")

// ===================================================================
// 	cmpiPerf_TestClassB
// ===================================================================

instance of PG_ProviderModule
{
   Name = "cmpiPerf_TestClassProviderModule";
   //The library name on disk
   Location = "cmpiPerf_TestClassProvider";
   Vendor = "IBM";
   Version = "2.0.0";
   InterfaceType = "CMPI";
   Bitness = 2;
   InterfaceVersion = "2.0.0";
};

instance of PG_Provider
{
   //The provider module as defined in PG_ProviderModule
   ProviderModuleName = "cmpiPerf_TestClassProviderModule";
   // The provider name as referenced in the code
   Name = "cmpiPerf_TestClassProvider";
};

instance of PG_ProviderCapabilities
{
   //The provider module as defined in PG_ProviderModule
   ProviderModuleName = "cmpiPerf_TestClassProviderModule";
   //The provider name as defined in PG_Provider
   ProviderName = "cmpiPerf_TestClassProvider";
   CapabilityID = "1";
   //Name of the CIM class as defined in the mof
   ClassName = "cmpiPerf_TestClassB";
   Namespaces = {"test/TestProvider"};
   ProviderType = { 2 }; // Instance
   SupportedProperties = NULL; // All properties
   SupportedMethods = NULL; // All methods
};

// ===================================================================
// 	cmpiPerf_TestClassA
// ===================================================================

instance of PG_ProviderModule
{
   Name = "cmpiPerf_TestClassAProviderModule";
   //The library name on disk
   Location = "cmpiPerf_TestClassAProvider";
   Vendor = "IBM";
   Version = "2.0.0";
   InterfaceType = "CMPI";
   Bitness = 2;
   InterfaceVersion = "2.0.0";
};

instance of PG_Provider
{
   //The provider module as defined in PG_ProviderModule
   ProviderModuleName = "cmpiPerf_TestClassAProviderModule";
   // The provider name as referenced in the code
   Name = "cmpiPerf_TestClassAProvider";
};

instance of PG_ProviderCapabilities
{
   //The provider module as defined in PG_ProviderModule
   ProviderModuleName = "cmpiPerf_TestClassAProviderModule";
   //The provider name as defined in PG_Provider
   ProviderName = "cmpiPerf_TestClassAProvider";
   CapabilityID = "1";
   //Name of the CIM class as defined in the mof
   ClassName = "cmpiPerf_TestClassA";
   Namespaces = {"test/TestProvider"};
   ProviderType = { 2 }; // Instance
   SupportedProperties = NULL; // All properties
   SupportedMethods = NULL; // All methods
};

// ===================================================================
// 	cmpiPerf_TestAssocClass
// ===================================================================

instance of PG_ProviderModule
{
   Name = "cmpiPerf_TestAssocClassProviderModule";
   //The library name on disk
   Location = "cmpiPerf_TestAssocClassProvider";
   Vendor = "IBM";
   Version = "2.0.0";
   InterfaceType = "CMPI";
   Bitness = 2;
   InterfaceVersion = "2.0.0";
};

instance of PG_Provider
{
   //The provider module as defined in PG_ProviderModule
   ProviderModuleName = "cmpiPerf_TestAssocClassProviderModule";
   // The provider name as referenced in the code
   Name = "cmpiPerf_TestAssocClassProvider";
};

instance of PG_ProviderCapabilities
{
   //The provider module as defined in PG_ProviderModule
   ProviderModuleName = "cmpiPerf_TestAssocClassProviderModule";
   //The provider name as defined in PG_Provider
   ProviderName = "cmpiPerf_TestAssocClassProvider";
   CapabilityID = "1";
   //Name of the CIM class as defined in the mof
   ClassName = "cmpiPerf_TestAssocClass";
   Namespaces = {"test/TestProvider"};
   ProviderType = { 2,3 }; // Instance, Association
   SupportedProperties = NULL; // All properties
   SupportedMethods = NULL; // All methods
};

instance of PG_ProviderModule
{
    Description = "The Test CMPI Association Provider Module implements the CMPI_TEST_PERSON, Class";
    Caption = "Test CMPI Association Pegasus Provider Module";
    Name = "TestCMPIAssociationProviderModule";
    Vendor = "OpenPegasus";
    Version = "2.0.0";
    InterfaceType = "CMPI";
    Bitness = 2;
    InterfaceVersion = "2.0.0";
    Location = "TestCMPIAssociationProvider";
};

instance of PG_Provider
{
    ProviderModuleName = "TestCMPIAssociationProviderModule";
    Name = "TestCMPIAssociationProvider";
};

instance of PG_ProviderCapabilities
{
    ProviderModuleName = "TestCMPIAssociationProviderModule";
    ProviderName = "TestCMPIAssociationProvider";
    CapabilityID = "TestCMPIAssociationProviderPerson";
    ClassName = "CMPI_TEST_Person";
    Namespaces = { "test/TestProvider", "test/Remote/Localhost" };
    ProviderType = { 3 };
    SupportedProperties = NULL;
    SupportedMethods = NULL;
};

instance of PG_ProviderCapabilities
{
    ProviderModuleName = "TestCMPIAssociationProviderModule";
    ProviderName = "TestCMPIAssociationProvider";
    CapabilityID = "TestCMPIAssociationProviderVehicle";
    ClassName = "CMPI_TEST_Vehicle";
    Namespaces = { "test/TestProvider", "test/Remote/Localhost" };
    ProviderType = { 3 };
    SupportedProperties = NULL;
    SupportedMethods = NULL;
};

instance of PG_ProviderCapabilities
{
    ProviderModuleName = "TestCMPIAssociationProviderModule";
    ProviderName = "TestCMPIAssociationProvider";
    CapabilityID = "TestCMPIAssociationProviderRacing";
    ClassName = "CMPI_TEST_Racing";
    Namespaces = { "test/TestProvider", "test/Remote/Localhost" };
    ProviderType = { 3 };
    SupportedProperties = NULL;
    SupportedMethods = NULL;
};
