// ===================================================================
// Title:       Master MOF
// Filename:    CIM_Schema25.mof
// Version:     2.5
// Release:     0
// Status:      Final
// Date:        06/12/2001
// ===================================================================
// Copyright "2001" Distributed Management Task Force, Inc. (DMTF).
// All rights reserved.  
// DMTF is a not-for-profit association of industry members dedicated 
// to promoting enterprise and systems management and interoperability. 
// DMTF specifications and documents may be reproduced for uses
// consistent with this purpose by members and non-members, 
// provided that correct attribution is given. 
// As DMTF specifications may be revised from time to time, 
// the particular version and release cited should always be noted.
// Description: These object classes define the user and security 
//              model for CIM and includes classes needed to represent
//              users, groups and organizational entities as well as 
//              security services and authentication and authorization 
//              information.
//              The object classes below are listed in an order that
//              avoids forward references. Required objects, defined 
//		    by other working groups, are omitted. 
// ===================================================================
// Description: This is overall Schema 
// ===================================================================
// Author     : DMTF Technical Committee
// ===================================================================
// includes
// ===================================================================
#pragma include ("CIM_Core25.mof")
#pragma include ("CIM_Events25.mof")
#pragma include ("CIM_User25.mof")
#pragma include ("CIM_Policy25.mof")
#pragma include ("CIM_Application25.mof")
#pragma include ("CIM_System25.mof")
#pragma include ("CIM_Device25.mof")
#pragma include ("CIM_Physical25.mof")
#pragma include ("CIM_Network25.mof")
#pragma include ("CIM_Metrics25.mof")
#pragma include ("CIM_Support25.mof")





