#//%LICENSE////////////////////////////////////////////////////////////////
#//
#// Licensed to The Open Group (TOG) under one or more contributor license
#// agreements.  Refer to the OpenPegasusNOTICE.txt file distributed with
#// this work for additional information regarding copyright ownership.
#// Each contributor licenses this file to you under the OpenPegasus Open
#// Source License; you may not use this file except in compliance with the
#// License.
#//
#// Permission is hereby granted, free of charge, to any person obtaining a
#// copy of this software and associated documentation files (the "Software"),
#// to deal in the Software without restriction, including without limitation
#// the rights to use, copy, modify, merge, publish, distribute, sublicense,
#// and/or sell copies of the Software, and to permit persons to whom the
#// Software is furnished to do so, subject to the following conditions:
#//
#// The above copyright notice and this permission notice shall be included
#// in all copies or substantial portions of the Software.
#//
#// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
#// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
#// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
#// CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
#// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
#// SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#//
#//////////////////////////////////////////////////////////////////////////

ROOT = ../../../../../../../../../..

include $(ROOT)/mak/config.mak
include $(ROOT)/test/config.mak

XMLSCRIPTS = \
	BadAttributeName01 \
	BadBooleanValue01 \
	BadInstanceClassName01 \
	BadMethodName01 \
	BadQualDecl01 \
	BadQualDeclType01 \
	DuplicateProperty01 \
	DuplicateQualifier01 \
	MissingBooleanValue01 \
	MissingCIMEndTag01 \
	MissingClassName01 \
	MissingClassNameStartTag01 \
	MissingIParamvalueEndTag01 \
	MissingIParamvalueStartTag01 \
	MissingKeyValue01 \
	MissingKeyValueEndTag01 \
	MissingMessageEndTag01 \
	MissingMethodCallEndTag01 \
	MissingPropertyReferenceEndTag01 \
	MissingReqEndTag01 \
	MissingValueArray01 \
	MissingXmlVersion01 \
	BadChar16Value01 \
	BadDateTimeValue01 \
	BadOpeningElement01 \
	BadQualValueElement01 \
	BadReal32Value01 \
	BadReal64Value01 \
	IllegalValueClassName01 \
	MissingInstanceNameClassName01 \
	MissingParamValueName01 \
	MissingValueElementEndTag01 \
	BadCharacterReference01 \
	BadCharacterReference02 \
	BadCharacterReference03 \
	BadCharacterReference04 \
	BadCharacterReference05 \
	BadCharacterReference06 \
	BadCharacterReference07 \
	BadEntityReference01 \
	BadEntityReference02 \
	BadEntityReference03 \
	GoodCharacterReference01 \
	GoodCharacterReference02 \
	GoodCharacterReference03 \
	GoodCharacterReference04 \
	GoodEntityReference01

include $(ROOT)/test/configend.mak
