#!/bin/bash

# Delete the existing Sample Classes and respective instances for our testing
# functionality. The class is registered in the default cim namespace on our
# system i.e.# root/cimv2


rm -f $PEGASUS_HOME/repository/root\#cimv2/classes/Sample*
rm -f $PEGASUS_HOME/repository/root\#cimv2/classes/Sample*
